#ifndef __LINUX__
#define NET_TASK_LISTEN 0
#endif
#define HAVE_SOCKLEN_T 1
#define HAVE_AMD3DNOW 0
#define HAVE_MMX 0
#define HAVE_NANOSLEEP 1
#define CONFIG_MEMALIGN_HACK 0
#define HAVE_CBRTF 1
#define HAVE_RINT 1
#ifdef __ANDRIOD__
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_TRUNC 1
#define HAVE_TRUNCF 1
#endif
#define FFMPEG_CONFIGURATION "--enable-gpl --enable-postproc"
#define FFMPEG_LICENSE "GPL version 2 or later"
#define av_restrict restrict
#define HAVE_THREADS 0
#define CONFIG_FTRAPV 0
#define CONFIG_ZLIB 0
#define HAVE_MMX2 0
#define HAVE_MMXEXT 0
#define CONFIG_MUXERS 1
#define CONFIG_DEMUXERS 1
#define CONFIG_FLV_MUXER 1
#define CONFIG_LIBMP3LAME 0
#define CONFIG_MATROSKA_MUXER 0
#define CONFIG_MATROSKA_DEMUXER 1
#define CONFIG_MOV_MUXER 0
#define CONFIG_MOV_DEMUXER 1
#define CONFIG_AVI_DEMUXER 1
#define CONFIG_AVI_MUXER 1
#define CONFIG_WAV_MUXER 1
#define CONFIG_DV_DEMUXER 1
#define CONFIG_MPEGTS_DEMUXER 1
#define CONFIG_MPEGTSRAW_DEMUXER 1
#define CONFIG_MP3_DEMUXER 1
#define CONFIG_WAV_DEMUXER 1
#define CONFIG_W64_DEMUXER 1
#define CONFIG_NETWORKING 1
#define CONFIG_LIVE555 1
#define CONFIG_MJPEG_DEMUXER 1
//#define CONFIG_UDP_PROTOCOL 1
//#define CONFIG_MPEGAUDIO_PARSER 1
#ifdef __LINUX__
#define CONFIG_H264_PARSER 1
#define CONFIG_MPEGVIDEO_PARSER 1
#define CONFIG_MPEG_XVMC_DECODER 0
#define CONFIG_VDPAU 0
#define CONFIG_GRAY 0
#define CONFIG_WMV2_DECODER 0
#define CONFIG_WMV2_ENCODER 0
#define CONFIG_H264_DECODER 1
#define CONFIG_H261_ENCODER 0
#define CONFIG_H261_DECODER 0
#define CONFIG_H264_VDPAU_DECODER 0
#define CONFIG_SVQ3_DECODER 0
#define CONFIG_SMALL 0
#ifndef __ANDRIOD__
#define CONFIG_ASS 1
#define CONFIG_ASS_INTERNAL 1
#endif
#define HAVE_POLL_H 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_UNISTD_H 1
//#define CONFIG_NETWORK 1

#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#ifdef CONFIG_MT_ENABLE_OPEN_SSL
#define CONFIG_OPENSSL 1
#else
#define CONFIG_OPENSSL 0
#endif
#define CONFIG_TLS_PROTOCOL 1
#define CONFIG_HTTPS_PROTOCOL 1
#else
#define CONFIG_H264_PARSER 1
#define CONFIG_MPEGVIDEO_PARSER 1
#define CONFIG_MPEG_XVMC_DECODER 0
#define CONFIG_VDPAU 0
#define CONFIG_GRAY 0
#define CONFIG_WMV2_DECODER 0
#define CONFIG_WMV2_ENCODER 0
#define CONFIG_H264_DECODER 1
#define CONFIG_H261_ENCODER 0
#define CONFIG_H261_DECODER 0
#define CONFIG_H264_VDPAU_DECODER 0
#define CONFIG_SVQ3_DECODER 0
#define CONFIG_SMALL 0


#ifdef CONFIG_MT_ENABLE_OPEN_SSL
#define CONFIG_OPENSSL 1
#else
#define CONFIG_OPENSSL 0
#endif

#ifdef ENABLE_OPEN_HTTPS
#define CONFIG_TLS_PROTOCOL 1
#define CONFIG_HTTPS_PROTOCOL 1
#else
#define CONFIG_TLS_PROTOCOL 0
#define CONFIG_HTTPS_PROTOCOL 0
#endif

#endif

#define CONFIG_AC3_DEMUXER 1
#define CONFIG_EAC3_DEMUXER 1
#define CONFIG_HLS_DEMUXER 1
#define CONFIG_HDS_DEMUXER 1
#define CONFIG_DASH_DEMUXER 1
#define CONFIG_FLV_DEMUXER 1
#define CONFIG_ASF_DEMUXER 1
#define CONFIG_RTMP_PROTOCOL 1
#define CONFIG_FFRTMPCRYPT_PROTOCOL 0
#define CONFIG_TCP_PROTOCOL 1
#define CONFIG_CRYPTO_PROTOCOL 1
#define CONFIG_HTTP_PROTOCOL 1
#define CONFIG_LIBRTMP_PROTOCOL 1
#define CONFIG_LIBRTMPE_PROTOCOL 1
#define CONFIG_LIBRTMPS_PROTOCOL 1
#define CONFIG_LIBRTMPT_PROTOCOL 1
#define CONFIG_LIBRTMPTE_PROTOCOL 1
