include ${SDK_DIR}/build/script/base.mk

INCLUDE_PATH = -I../include -I../av/include/ -I$(COMMON_UNF_INCLUDE) -I$(INCLUDE_DIR)
OBJS := satip_player.o
LIB := libsatip

HEADER_FILES := ../include/satip_player.h
HEADER_FILES_INSTALL_SUBDIR=dlna

include ${SDK_DIR}/build/script/Makefile-lib.rule
