#*****************************************************************
#
# Copyright (C) Microsoft Corporation. All rights reserved.
#
#*****************************************************************

include $(MSPK_ROOT)/Platform/$(MSPK_PLATFORM)/Build/MspkMakeLib.mk
