#!/bin/sh
TIMEOUT         30
ABORT           '\nBUSY\r'
ABORT           '\nERROR\r'
ABORT           '\nNO ANSWER\r'
ABORT           '\nNO CARRIER\r'
ABORT           '\nNO DIALTONE\r'
ABORT           '\nRINGING\r\n\r\nRINGING\r'
''              'AT\r'
OK              'AT+CGMR\r'
OK              'AT+CGSN\r'
OK              'AT+CIMI\r'
OK              'AT+CPIN?\r'
OK              'AT+CREG?\r'
OK              'AT+CSQ\r'
OK              'AT+CGDCONT=1,"ip","3gnet"\r'
OK              'ATDT*99#\r'
CONNECT         ""