include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall

all:
	$(MAKE) -f app.mk

clean:
	$(MAKE) -f app.mk clean

install:
	$(MAKE) -f app.mk install

uninstall:
	$(MAKE) -f app.mk uninstall

distclean:
	$(MAKE) -f app.mk distclean

