-include .config
export

.PHONY: modules
modules:
	@$(MAKE) -C $(KLIB_BUILD) $(MT_KERNEL_OUTPUT_OPT) M=$(BACKPORT_PWD) modules

.PHONY: clean
clean:
	@$(MAKE) -C $(KLIB_BUILD) $(MT_KERNEL_OUTPUT_OPT) M=$(BACKPORT_PWD) clean
