include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall

all:
	$(MAKE) -f sample_dmx_pat.mk
	$(MAKE) -f sample_dmx_pmt.mk
	$(MAKE) -f sample_dmx_nit.mk
	$(MAKE) -f sample_dmx_sdt.mk
	$(MAKE) -f sample_dmx_eit.mk
	$(MAKE) -f sample_dmx_cat.mk
	$(MAKE) -f sample_dmx_section.mk

clean:
	$(MAKE) -f sample_dmx_pat.mk clean
	$(MAKE) -f sample_dmx_pmt.mk clean
	$(MAKE) -f sample_dmx_nit.mk clean
	$(MAKE) -f sample_dmx_sdt.mk clean
	$(MAKE) -f sample_dmx_eit.mk clean
	$(MAKE) -f sample_dmx_cat.mk clean
	$(MAKE) -f sample_dmx_section.mk clean

install:
	$(MAKE) -f sample_dmx_pat.mk install
	$(MAKE) -f sample_dmx_pmt.mk install
	$(MAKE) -f sample_dmx_nit.mk install
	$(MAKE) -f sample_dmx_sdt.mk install
	$(MAKE) -f sample_dmx_eit.mk install
	$(MAKE) -f sample_dmx_cat.mk install
	$(MAKE) -f sample_dmx_section.mk install

uninstall:
	$(MAKE) -f sample_dmx_pat.mk uninstall
	$(MAKE) -f sample_dmx_pmt.mk uninstall
	$(MAKE) -f sample_dmx_nit.mk uninstall
	$(MAKE) -f sample_dmx_sdt.mk uninstall
	$(MAKE) -f sample_dmx_eit.mk uninstall
	$(MAKE) -f sample_dmx_cat.mk uninstall
	$(MAKE) -f sample_dmx_section.mk uninstall
