include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall

all:
	$(MAKE) -f app1.mk
#	$(MAKE) -f app2.mk
#	$(MAKE) -f app3.mk
#	$(MAKE) -f app4.mk
#	$(MAKE) -f app5.mk
#	$(MAKE) -f app6.mk
#	$(MAKE) -f app7.mk

clean:
	$(MAKE) -f app1.mk clean
#	$(MAKE) -f app2.mk clean
#	$(MAKE) -f app3.mk clean
#	$(MAKE) -f app4.mk clean
#	$(MAKE) -f app5.mk clean
#	$(MAKE) -f app6.mk clean
#	$(MAKE) -f app7.mk clean

install:
	$(MAKE) -f app1.mk install
#	$(MAKE) -f app2.mk install
#	$(MAKE) -f app3.mk install
#	$(MAKE) -f app4.mk install
#	$(MAKE) -f app5.mk install
#	$(MAKE) -f app6.mk install
#	$(MAKE) -f app7.mk install

uninstall:
	$(MAKE) -f app1.mk uninstall
#	$(MAKE) -f app2.mk uninstall
#	$(MAKE) -f app3.mk uninstall
#	$(MAKE) -f app4.mk uninstall
#	$(MAKE) -f app5.mk uninstall
#	$(MAKE) -f app6.mk uninstall
#	$(MAKE) -f app7.mk uninstall

distclean:
	$(MAKE) -f app1.mk distclean
#	$(MAKE) -f app2.mk distclean
#	$(MAKE) -f app3.mk distclean
#	$(MAKE) -f app4.mk distclean
#	$(MAKE) -f app5.mk distclean
#	$(MAKE) -f app6.mk distclean
#	$(MAKE) -f app7.mk distclean
