///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
//  This file is marked as "read only".
//
///////////////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "CSocketDiags.h"
#include "ISocket.h"
#include "Trace.h"

// ===============================================================================================================
// Base event class used for various socket related events
// Fills in basic information about the current tune parameters and
// common properties for all types of supported sockets
// ===============================================================================================================

void CDiagsSocketEvent::DiagsGetEventData(void)
{
    //Type of socket
    if (SocketType != eSocketType_Unknown)
    {
        DiagsLogString(L"Type", ISocketFactory::SocketNameFromType(SocketType));
    }
    //Pipe ID this socket is streaming to
    DiagsLogPipeId(L"PipeId", PipeIdN);
    //Unique ids associates with this tune
    DiagsLogValue(L"MTId", MediaTransportId);
    DiagsLogValue(L"UId", UniqueId);
    DiagsLogGuid(L"ServiceId", ContentId);
    //Channel number
    DiagsLogValue(L"Channel", Channel);
    //BitRate
    DiagsLogValue(L"BitRate", BitRate);
}

// ===============================================================================================================
// Periodic diagnostics event generated by each socket currently active in the system
// ===============================================================================================================

void CDiagsSocketUpdateEvent::DiagsGetEventData(void)
{
    //Base class stuff
    CDiagsSocketEvent::DiagsGetEventData();

    //Number of packets processed downstream
    DiagsLogValue(L"PacketsProcessed", PacketsProcessed);
    //Number of packets with parse errors
    DiagsLogValue(L"ParseErrors", PacketsWithParseErrors);
}

// ===============================================================================================================
// ===============================================================================================================
