///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
//  This file is marked as "read only".
//
///////////////////////////////////////////////////////////////////////////////

#pragma once

// ===============================================================================================================
// Different types of sockets supported - add when new types of sockets are introduced
// ===============================================================================================================

//NOTE: When changing this list, make sure to update gSocketTypeStrings array in CSocketFactory.cpp
enum eSocketType
{
    eSocketType_Unknown,
    eSocketType_Mbr,
    eSocketType_MbrChunk,
    eSocketType_Max,
};

// ===============================================================================================================
// Generic errors generated by calls to receive packets from different sockets
// ===============================================================================================================

enum eSocketRecvError
{
    eRecvErrorNone = 0,
    eRecvErrorUnknown = -1,
    eRecvErrorEOF = -2,
    eRecvErrorReadFailed = -3,
    eRecvErrorBadData = -4,
    eRecvErrorDrmInit = -5,
};

// ===============================================================================================================
// ===============================================================================================================

