/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2022 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
#ifndef __INC_MT_CLOCK_TOP_H__
#define __INC_MT_CLOCK_TOP_H__

#ifndef MKSTR
#define MKSTR(x)					#x
#endif

/* TOPCLK_CTRL0_REG */
#define TOP_AXI_CLK					MKSTR(TOP_AXI_CLK)
#define TOP_DDROMC_CLK				MKSTR(TOP_DDROMC_CLK)
#define TOP_HDMI_AUD_CLK			MKSTR(TOP_HDMI_AUD_CLK)
#define TOP_AHB_CLK					MKSTR(TOP_AHB_CLK)
#define TOP_APB_CLK					MKSTR(TOP_APB_CLK)
#define TOP_APBACKUP_CLK			MKSTR(TOP_APBACKUP_CLK)

/* TOPCLK_CTRL1_REG */
#define TOP_AVCPU_CLK				MKSTR(TOP_AVCPU_CLK)
#define TOP_SMC_90M_CLK				MKSTR(TOP_SMC_90M_CLK)
#define TOP_SMC_XTAL_D2_CLK			MKSTR(TOP_SMC_XTAL_D2_CLK)
#define TOP_SPI_CLK					MKSTR(TOP_SPI_CLK)
#define TOP_DS_CLK					MKSTR(TOP_DS_CLK)
#define TOP_PKA_CLK					MKSTR(TOP_PKA_CLK)
#define TOP_SDIO_0_CLK				MKSTR(TOP_SDIO_0_CLK)
#define TOP_SDIO_1_CLK				MKSTR(TOP_SDIO_1_CLK)
#define TOP_GRA_CLK					MKSTR(TOP_GRA_CLK)
#define TOP_JPG_262M_CLK			MKSTR(TOP_JPG_262M_CLK)
#define TOP_JPG_206M_CLK			MKSTR(TOP_JPG_206M_CLK)
#define TOP_JPG_144M_CLK			MKSTR(TOP_JPG_144M_CLK)
#define TOP_JPG_288M_CLK			MKSTR(TOP_JPG_288M_CLK)

/* TOPCLK_CTRL2_REG */
#define TOP_HDMI_XCLK				MKSTR(TOP_HDMI_XCLK)
#define TOP_HDMI_CEC_CLK			MKSTR(TOP_HDMI_CEC_CLK)
#define TOP_HDMI_OSC_CLK			MKSTR(TOP_HDMI_OSC_CLK)
#define TOP_VDEC_CLK				MKSTR(TOP_VDEC_CLK)
#define TOP_AOUT_CLK				MKSTR(TOP_AOUT_CLK)
#define TOP_AUDIOPLL_SCAN_CLK		MKSTR(TOP_AUDIOPLL_SCAN_CLK)
#define TOP_USB0_CORE_SCAN_CLK		MKSTR(TOP_USB0_CORE_SCAN_CLK)
#define TOP_AVSYNC_CLK				MKSTR(TOP_AVSYNC_CLK)
#define TOP_PNG_262M_CLK			MKSTR(TOP_PNG_262M_CLK)
#define TOP_PNG_206M_CLK			MKSTR(TOP_PNG_206M_CLK)
#define TOP_PNG_144M_CLK			MKSTR(TOP_PNG_144M_CLK)
#define TOP_PNG_288M_CLK			MKSTR(TOP_PNG_288M_CLK)
#define TOP_SDVENC_CLK				MKSTR(TOP_SDVENC_CLK)
#define TOP_HDVENC_CLK				MKSTR(TOP_HDVENC_CLK)
#define TOP_TSI_CLK					MKSTR(TOP_TSI_CLK)
#define TOP_HDMI_TMDS_CLK			MKSTR(TOP_HDMI_TMDS_CLK)

/* TOPCLK_CTRL3_REG */
#define TOP_IFCP_SYS_CLK			MKSTR(TOP_IFCP_SYS_CLK)
#define TOP_IFCP_CRYPTO_CLK			MKSTR(TOP_IFCP_CRYPTO_CLK)
#define TOP_OTP_80M_CLK				MKSTR(TOP_OTP_80M_CLK)
#define TOP_OTP_86P5M_CLK			MKSTR(TOP_OTP_86P5M_CLK)
#define TOP_SWTIMER_CLK				MKSTR(TOP_SWTIMER_CLK)
#define TOP_IFCP_TIMER_CLK			MKSTR(TOP_IFCP_TIMER_CLK)
#define TOP_GLITCH_CLK				MKSTR(TOP_GLITCH_CLK)

/* TOPCLK_CTRL4_REG */
#define TOP_SOSC_173M_CLK			MKSTR(TOP_SOSC_173M_CLK)
#define TOP_SOSC_FAST_SCAN_CLK		MKSTR(TOP_SOSC_FAST_SCAN_CLK)
#define TOP_SECURE_CLK				MKSTR(TOP_SECURE_CLK)
#define TOP_M2M_CIPHER_CLK			MKSTR(TOP_M2M_CIPHER_CLK)
#define TOP_DMA_CLK					MKSTR(TOP_DMA_CLK)
#define TOP_GPU_CLK					MKSTR(TOP_GPU_CLK)
#define TOP_UART_CLK				MKSTR(TOP_UART_CLK)
#define TOP_USB3_CLK				MKSTR(TOP_USB3_CLK)
#define TOP_DAI_RX_CLK				MKSTR(TOP_DAI_RX_CLK)
#define TOP_DAI_TX_CLK				MKSTR(TOP_DAI_TX_CLK)
#define TOP_AUDIO_SPDF_CLK			MKSTR(TOP_AUDIO_SPDF_CLK)

/* TOPCLK_CTRL5_REG */
#define TOP_DISP_CCLK				MKSTR(TOP_DISP_CCLK)
#define TOP_DISP_DI_CLK				MKSTR(TOP_DISP_DI_CLK)
#define TOP_DISP_OSDC_CLK			MKSTR(TOP_DISP_OSDC_CLK)
#define TOP_DISP_VDC_CLK			MKSTR(TOP_DISP_VDC_CLK)
#define TOP_ETHERNET_CLK			MKSTR(TOP_ETHERNET_CLK)
#define TOP_PNAND_CLK				MKSTR(TOP_PNAND_CLK)
#define TOP_PNAND_ACSCAN_CLK		MKSTR(TOP_PNAND_ACSCAN_CLK)
#define TOP_GMAC_CLK				MKSTR(TOP_GMAC_CLK)

/* TOPCLK_CTRL6_REG */
#define TOP_DMA_XTAL_MUX			MKSTR(TOP_DMA_XTAL_MUX)
#define TOP_JPG_XTAL_MUX			MKSTR(TOP_JPG_XTAL_MUX)
#define TOP_DISP_XTAL_MUX			MKSTR(TOP_DISP_XTAL_MUX)
#define TOP_VDEC_XTAL_MUX			MKSTR(TOP_VDEC_XTAL_MUX)
#define TOP_AOUT_XTAL_MUX			MKSTR(TOP_AOUT_XTAL_MUX)
#define TOP_PNG_XTAL_MUX			MKSTR(TOP_PNG_XTAL_MUX)
#define TOP_IFCPCRYPTO_XTAL_MUX		MKSTR(TOP_IFCPCRYPTO_XTAL_MUX)
#define TOP_TSI_XTAL_MUX			MKSTR(TOP_TSI_XTAL_MUX)
#define TOP_DS_XTAL_MUX				MKSTR(TOP_DS_XTAL_MUX)
#define TOP_SECURE_XTAL_MUX			MKSTR(TOP_SECURE_XTAL_MUX)
#define TOP_CIPHER_XTAL_MUX			MKSTR(TOP_CIPHER_XTAL_MUX)
#define TOP_VHDPLL_D5_MUX			MKSTR(TOP_VHDPLL_D5_MUX)
#define TOP_AVCPU_XTAL_MUX			MKSTR(TOP_AVCPU_XTAL_MUX)
#define TOP_TEST_CLK				MKSTR(TOP_TEST_CLK)
#define TOP_GPU_XTAL_MUX			MKSTR(TOP_GPU_XTAL_MUX)
#define TOP_ETHPLL_D5_MUX			MKSTR(TOP_ETHPLL_D5_MUX)
#define TOP_SDVENC_D4_XTAL_MUX		MKSTR(TOP_SDVENC_D4_XTAL_MUX)

#endif

