/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2022 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
/******************************************************************************
 * Copyright (C) 2022, Montage LZ Technology Co., Ltd.
 *
 * File Name      : mt_crm_top_reg.h
 * Version        : V0.9
 * Author         : MA-SW
 * Created        : 2022/06/29
 * Description    : MT Symphony6 CRM top registers.
 * History        :
 * 1.Date         : 2022/06/29
 *   Author       : LZ100218
 *   Modification : Created file
 *
*****************************************************************************/
#ifndef __INC__MT_CRM_TOP_REG_H__
#define __INC__MT_CRM_TOP_REG_H__

/* Symphony6 CRM Module TOP Registers Definition */

#define REG_TOPCLK_CTRL0				(REG_CRM_BASE+0xF800)
#define TOP_APBACKUP_CLKEN_SHIFT		20
#define TOP_APB_CLKEN_SHIFT				16
#define TOP_AHB_CLKEN_SHIFT				8
#define TOP_HDMI_AUD_CLKEN_SHIFT		2
#define TOP_DDROMC_CLKEN_SHIFT			1
#define TOP_AXI_CLKEN_SHIFT				0
#define TOP_APBACKUP_CLKEN_MASK			(0x1 << TOP_APBACKUP_CLKEN_SHIFT)
#define TOP_APB_CLKEN_MASK				(0x1 << TOP_APB_CLKEN_SHIFT)
#define TOP_AHB_CLKEN_MASK				(0x1 << TOP_AHB_CLKEN_SHIFT)
#define TOP_HDMI_AUD_CLKEN_MASK			(0x1 << TOP_HDMI_AUD_CLKEN_SHIFT)
#define TOP_DDROMC_CLKEN_MASK			(0x1 << TOP_DDROMC_CLKEN_SHIFT)
#define TOP_AXI_CLKEN_MASK				(0x1 << TOP_AXI_CLKEN_SHIFT)

#define REG_TOPCLK_CTRL1				(REG_CRM_BASE+0xF804)
#define TOP_JPG_288M_CLKEN_SHIFT		31
#define TOP_JPG_144M_CLKEN_SHIFT		30
#define TOP_JPG_206M_CLKEN_SHIFT		29
#define TOP_JPG_262M_CLKEN_SHIFT		28
#define TOP_JPG_CLKEN_SHIFT				28

#define TOP_GRA_CLKEN_SHIFT				24

#define TOP_SDIO1_CLKEN_SHIFT			21
#define TOP_SDIO0_CLKEN_SHIFT			20
#define TOP_SDIO_CLKEN_SHIFT			20

#define TOP_PKA_CLKEN_SHIFT				17
#define TOP_DS_CLKEN_SHIFT				16
#define TOP_SPI_CLKEN_SHIFT				11

#define TOP_SMC_XTAL_D2_CLKEN_SHIFT		9
#define TOP_SMC_90M_CLKEN_SHIFT			8
#define TOP_SMC_CLKEN_SHIFT				8

#define TOP_AVCPU_CLKEN_SHIFT			0
#define TOP_JPG_CLKEN_MASK				(0xF << TOP_JPG_CLKEN_SHIFT)
#define TOP_GRA_CLKEN_MASK				(0x1 << TOP_GRA_CLKEN_SHIFT)
#define TOP_SDIO_CLKEN_MASK				(0x3 << TOP_SDIO_CLKEN_SHIFT)
#define TOP_PKA_CLKEN_MASK				(0x1 << TOP_PKA_CLKEN_SHIFT)
#define TOP_DS_CLKEN_MASK				(0x1 << TOP_DS_CLKEN_SHIFT)
#define TOP_SPI_CLKEN_MASK				(0x1 << TOP_SPI_CLKEN_SHIFT)
#define TOP_SMC_CLKEN_MASK				(0x3 << TOP_SMC_CLKEN_SHIFT)
#define TOP_AVCPU_CLKEN_MASK			(0x1 << TOP_AVCPU_CLKEN_SHIFT)

#define REG_TOPCLK_CTRL2				(REG_CRM_BASE+0xF808)
#define TOP_HDMI_TMDS_CLKEN_SHIFT		27
#define TOP_TSI_CLKEN_SHIFT				26

#define TOP_HDVENC_OSC_CLKEN_SHIFT		25
#define TOP_SDVENC_CLKEN_SHIFT			24
#define TOP_VENC_CLKEN_SHIFT			24

#define TOP_PNG_288M_CLKEN_SHIFT		23
#define TOP_PNG_144M_CLKEN_SHIFT		22
#define TOP_PNG_206M_CLKEN_SHIFT		21
#define TOP_PNG_262M_CLKEN_SHIFT		20
#define TOP_PNG_CLKEN_SHIFT				20

#define TOP_AVSYNC_CLKEN_SHIFT			19
#define TOP_USB0_CORE_SCAN_CLKEN_SHIFT	18
#define TOP_AUDIOPLL_SCAN_CLKEN_SHIFT	17
#define TOP_AOUT_CLKEN_SHIFT			8
#define TOP_VDEC_CLKEN_SHIFT			4
#define TOP_HDMI_OSC_CLKEN_SHIFT		3
#define TOP_HDMI_CEC_CLKEN_SHIFT		2
#define TOP_HDMI_XCLK_CLKEN_SHIFT		1
#define TOP_HDMI_CLKEN_SHIFT			0
#define TOP_HDMI_TMDS_CLKEN_MASK		(0x1 << TOP_HDMI_TMDS_CLKEN_SHIFT)
#define TOP_TSI_CLKEN_MASK				(0x1 << TOP_TSI_CLKEN_SHIFT)
#define TOP_VENC_CLKEN_MASK				(0x3 << TOP_VENC_CLKEN_SHIFT)
#define TOP_PNG_CLKEN_MASK				(0xF << TOP_PNG_CLKEN_SHIFT)
#define TOP_AVSYNC_CLKEN_MASK			(0x1 << TOP_AVSYNC_CLKEN_SHIFT)
#define TOP_USB0_CORE_SCAN_CLKEN_MASK	(0x1 << TOP_USB0_CORE_SCAN_CLKEN_SHIFT)
#define TOP_AUDIOPLL_SCAN_CLKEN_MASK	(0x1 << TOP_AUDIOPLL_SCAN_CLKEN_SHIFT)
#define TOP_AOUT_CLKEN_MASK				(0x1 << TOP_AOUT_CLKEN_SHIFT)
#define TOP_VDEC_CLKEN_MASK				(0x1 << TOP_VDEC_CLKEN_SHIFT)
#define TOP_HDMI_CLKEN_MASK				(0xF << TOP_HDMI_CLKEN_SHIFT)

#define REG_TOPCLK_CTRL3				(REG_CRM_BASE+0xF80C)
#define TOP_GLITCH_CLKEN_SHIFT			28
#define TOP_IFCPTIMER_CLKEN_SHIFT		24
#define TOP_SWTIMER_CLKEN_SHIFT			20

#define TOP_OTP_86P5_CLKEN_SHIFT		17
#define TOP_OTP_80M_CLKEN_SHIFT			16
#define TOP_OTP_CLKEN_SHIFT				16

#define TOP_IFCP_CRYPTO_CLKEN_SHIFT		8
#define TOP_IFCP_SYS_CLKEN_SHIFT		0
#define TOP_GLITCH_CLKEN_MASK			(0x1 << TOP_GLITCH_CLKEN_SHIFT)
#define TOP_IFCPTIMER_CLKEN_MASK		(0x1 << TOP_IFCPTIMER_CLKEN_SHIFT)
#define TOP_SWTIMER_CLKEN_MASK			(0x1 << TOP_SWTIMER_CLKEN_SHIFT)
#define TOP_OTP_CLKEN_MASK				(0x3 << TOP_OTP_CLKEN_SHIFT)
#define TOP_IFCP_CRYPTO_CLKEN_MASK		(0x1 << TOP_IFCP_CRYPTO_CLKEN_SHIFT)
#define TOP_IFCP_SYS_CLKEN_MASK			(0x1 << TOP_IFCP_SYS_CLKEN_SHIFT)

#define REG_TOPCLK_CTRL4				(REG_CRM_BASE+0xF810)
#define TOP_AUDIO_SPDF_CLKEN_SHIFT		30
#define TOP_DAI_TX_CLKEN_SHIFT			29
#define TOP_DAI_RX_CLKEN_SHIFT			28
#define TOP_USB3_CLKEN_SHIFT			27
#define TOP_UART_CLKEN_SHIFT			26
#define TOP_GPU_CLKEN_SHIFT				16
#define TOP_DMA_CLKEN_SHIFT				12
#define TOP_M2MCIPHER_CLKEN_SHIFT		8
#define TOP_SECURE_CLKEN_SHIFT			4

#define TOP_SOSC_180M_CLKEN_SHIFT		1
#define TOP_SOSC_173M_CLKEN_SHIFT		0
#define TOP_SOSC_CLKEN_SHIFT			0

#define TOP_AUDIO_SPDF_CLKEN_MASK		(0x1 << TOP_AUDIO_SPDF_CLKEN_SHIFT)
#define TOP_DAI_TX_CLKEN_MASK			(0x1 << TOP_DAI_TX_CLKEN_SHIFT)
#define TOP_DAI_RX_CLKEN_MASK			(0x1 << TOP_DAI_RX_CLKEN_SHIFT)
#define TOP_USB3_CLKEN_MASK				(0x1 << TOP_USB3_CLKEN_SHIFT)
#define TOP_UART_CLKEN_MASK				(0x1 << TOP_UART_CLKEN_SHIFT)
#define TOP_GPU_CLKEN_MASK				(0x1 << TOP_GPU_CLKEN_SHIFT)
#define TOP_DMA_CLKEN_MASK				(0x1 << TOP_DMA_CLKEN_SHIFT)
#define TOP_M2MCIPHER_CLKEN_MASK		(0x1 << TOP_M2MCIPHER_CLKEN_SHIFT)
#define TOP_SECURE_CLKEN_MASK			(0x1 << TOP_SECURE_CLKEN_SHIFT)
#define TOP_SOSC_CLKEN_MASK				(0x3 << TOP_SOSC_CLKEN_SHIFT)

#define REG_TOPCLK_CTRL5				(REG_CRM_BASE+0xF814)
#define TOP_GMAC_CLKEN_SHIFT			28
#define TOP_PNAND_ACSCAN_CLKEN_SHIFT	23
#define TOP_PNAND_CLKEN_SHIFT			22
#define TOP_XTAL_DIV_NUMB_SHIFT			16
#define TOP_ETHERNET_CLKEN_SHIFT		15

#define TOP_DISP_VDC_CLKEN_SHIFT		3
#define TOP_DISP_OSDC_CLKEN_SHIFT		2
#define TOP_DISP_DI_CLKEN_SHIFT			1
#define TOP_DISP_CCLK_CLKEN_SHIFT		0
#define TOP_DISP_CLKEN_SHIFT			0

#define TOP_GMAC_CLKEN_MASK				(0x1 << TOP_GMAC_CLKEN_SHIFT)
#define TOP_PNAND_ACSCAN_CLKEN_MASK		(0x1 << TOP_PNAND_ACSCAN_CLKEN_SHIFT)
#define TOP_PNAND_CLKEN_MASK			(0x1 << TOP_PNAND_CLKEN_SHIFT)
#define TOP_XTAL_DIV_NUMB_MASK			(0x3F << TOP_XTAL_DIV_NUMB_SHIFT)
#define TOP_ETHERNET_CLKEN_MASK			(0x1 << TOP_ETHERNET_CLKEN_SHIFT)
#define TOP_DISP_CLKEN_MASK				(0xF << TOP_DISP_CLKEN_SHIFT)

//!TOPCLK_CTRL6_REG
//<CN> 选择是否用晶振频率:
//1: 是
//0: 不是
#define REG_TOPCLK_CTRL6				(REG_CRM_BASE+0xF818)
#define APCPU_MBIST_RST_RELEASE_SHIFT	31

/* SYS_ECO_CTRL_SHIFT 30:25 */
#define PCM_DATA_SEL_SHIFT				30
#define DEMO_SRESET_SHIFT				28
#define DEMO_CLKEN_SHIFT				27
#define GPU_MBIST_CLKEN_SHIFT			26
#define SDVENC_CLK_D4_XTAL_SEL_SHIFT	25

#define TOP_ETHPLL_D5_SEL_SHIFT			24
#define GPU_XTAL_SEL_SHIFT				23
#define APBACKUP_GROUP_CLKSEL_MODE_SHIFT	22
#define ARMPLL_CFG_PROTECT_SHIFT		21

#define TESTCLK_CLOSED_SHIFT			20
#define AVCPU_XTAL_SEL_SHIFT			19
#define TOP_VHDPLL_D5_SEL_SHIFT			18
#define CIPHER_XTAL_SEL_SHIFT			17
#define SECURE_XTAL_SEL_SHIFT			16
#define DESCRAMBLE_XTAL_SEL_SHIFT		15
#define TSI_XTAL_SEL_SHIFT				14
#define IFCPCRYPTO_XTAL_SEL_SHIFT		13
#define PNG_XTAL_SEL_SHIFT				12
#define AOUT_XTAL_SEL_SHIFT				11
#define VDEC_XTAL_SEL_SHIFT				10
#define DISP_XTAL_SEL_SHIFT				9
#define JPG_XTAL_SEL_SHIFT				8

#define DMA_XTAL_SEL_SHIFT				6
#define USB30PLL_D4D5_DUTY_SEL_SHIFT	5
#define USB_D15_DIV3_DUTY_SEL_SHIFT		4
#define USB_D10_DIV3_DUTY_SEL_SHIFT		3
#define USB_D7_DIV3_DUTY_SEL_SHIFT		2
#define USB_D5_DIV3_DUTY_SEL_SHIFT		1
#define USB_D3_DIV3_DUTY_SEL_SHIFT		0

#define REG_TOPCLK_CTRL7				(REG_CRM_BASE+0xF854)
#define APCPU_MBIST_REQ_SHIFT			15
#define APCPU_MBIST_RST_SHIFT			14
#define AOUT_MCLK_CLKSEL_SHIFT			12
#define DEMO_CLKSEL_SHIFT				11
#define DEMO_DRV1_CLKSEL_SHIFT			10
#define DEMO_DRV0_CLKSEL_SHIFT			8
#define IFCP_BSRAM_MBIST_SHIFT			7
#define GPU_AHB_MODE_SHIFT				6
#define SUBAHB_MODE_SHIFT				5
#define TOP_ARMPLL_DELAY_SET_SHIFT		0

/* <CN> 硬件自动时钟门控 */
#define REG_SYS_CLK_HW_EN				(REG_CRM_BASE+0xF900)
#define AHB_CLK_HW_EN_SHIFT				2
#define SPDMA_CLK_HW_EN_SHIFT			1
#define AHB_FW_CLK_HW_EN_SHIFT			0	/* always is '1', RO */

/* <CN> 软件时钟门控 */
#define REG_SYS_CLK_SW_EN				(REG_CRM_BASE+0xF904)
#define AHB_CLK_SW_EN_SHIFT				2
#define SPDMA_CLK_SW_EN_SHIFT			1
#define AHB_FW_CLK_SW_EN_SHIFT			0

#define REG_DFT_CFG						(REG_CRM_BASE+0xFC00)
#define APCPU_MBIST_EN_SHIFT			1
#define MBIST_MODE_SHIFT				0

#endif

