/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2022 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
/******************************************************************************
 * Copyright (C) 2022, Montage LZ Technology Co., Ltd.
 *
 * File Name      : mt_crm_lock_reg.h
 * Version        : V0.9
 * Author         : MA-SW
 * Created        : 2022/06/29
 * Description    : MT Symphony6 CRM slock/lock registers.
 * History        :
 * 1.Date         : 2022/06/29
 *   Author       : LZ100218
 *   Modification : Created file
 *
*****************************************************************************/
#ifndef __INC__MT_CRM_LOCK_REG_H__
#define __INC__MT_CRM_LOCK_REG_H__

/* Symphony6 CRM Module SLOCK and LOCK Registers Definition */

#define REG_MAC_SLOCK					(REG_CRM_BASE + 0x70)
#define REG_MAC_LOCK					(REG_CRM_BASE + 0x74)
#define MAC_CLKMODE_LOCK_SHIFT			17
#define MAC_CLKSEL_LOCK_SHIFT			16
#define RMII_CLKEN_LOCK_SHIFT			15
#define MAC_CLKEN_LOCK_SHIFT			14
#define MAC_SRSTN_LOCK_SHIFT			13		/* macahb/macaxi/ephyahb */

#define REG_BUS_SLOCK					(REG_CRM_BASE + 0x8018)
#define REG_BUS_LOCK					(REG_CRM_BASE + 0x801C)
#define AXI_CLKSEL_LOCK_SHIFT			6
#define APB_CLKSEL_LOCK_SHIFT			5
#define AHB_CLKSEL_LOCK_SHIFT			4

#define REG_APCPU_SLOCK					(REG_CRM_BASE + 0x8118)
#define REG_APCPU_LOCK					(REG_CRM_BASE + 0x811C)
#define APCPU_NTRST_LOCK_SHIFT			17
#define APCPU_NPOTRST_LOCK_SHIFT		16
#define APCPU_CSRST_LOCK_SHIFT			15
#define APCPU_AHB_LOCK_SHIFT			14
#define APCPU_APB_LOCK_SHIFT			13
#define MBIST_RSTN_LOCK_SHIFT			12
#define L2RESET_LOCK_SHIFT				11
#define NDBGRESET1_LOCK_SHIFT			10
#define NDBGRESET0_LOCK_SHIFT			9
#define NCORERESET1_LOCK_SHIFT			8
#define NCORERESET0_LOCK_SHIFT			7
#define NCOREPORESET1_LOCK_SHIFT		6
#define NCOREPORESET0_LOCK_SHIFT		5
#define ARMPLL_CFG_LOCK_SHIFT			4
#define APCPU_CLKSEL_LOCK_SHIFT			2
#define APCPU_PCLKEN_LOCK_SHIFT			1
#define APCPU_CLKEN_LOCK_SHIFT			0

#define REG_AVCPU_SLOCK					(REG_CRM_BASE + 0x8218)
#define REG_AVCPU_LOCK					(REG_CRM_BASE + 0x821C)
#define SPDMACORE_SRSTN_LOCK_SHIFT		7
#define SPDMAAHB_SRSTN_LOCK_SHIFT		6
#define SPDMAAXI_SRSTN_LOCK_SHIFT		5
#define AVCPUCORE_SRSTN_LOCK_SHIFT		4
#define AVCPUAHB_SRSTN_LOCK_SHIFT		3
#define AVCPUAXI_SRSTN_LOCK_SHIFT		2
#define AVCPU_CLKSEL_LOCK_SHIFT			1
#define AVCPU_CLKEN_LOCK_SHIFT			0

#define REG_SYS_SLOCK					(REG_CRM_BASE + 0x8318)
#define REG_SYS_LOCK					(REG_CRM_BASE + 0x831C)
#define OMC_PHY_LOCK_SHIFT				30
#define OMC_CORE_LOCK_SHIFT				29
#define OMC_PCLK_LOCK_SHIFT				28
#define OMC_RCLK_LOCK_SHIFT				27
#define SWTMISC_SRST_LOCK_SHIFT			26
#define SWMNTSOSC_SRST_LOCK_SHIFT		25
#define SWMNTXTAL_SRST_LOCK_SHIFT		24
#define SWWDOG1_SRST_LOCK_SHIFT			23
#define SWWDOG0_SRST_LOCK_SHIFT			22
#define SWTIMER3_SRST_LOCK_SHIFT		21
#define SWTIMER2_SRST_LOCK_SHIFT		20
#define SWTIMER1_SRST_LOCK_SHIFT		19
#define SWTIMER0_SRST_LOCK_SHIFT		18
#define DMACORE_SRST_LOCK_SHIFT			17
#define DMAAHB_SRST_LOCK_SHIFT			16
#define DMAAXI_SRST_LOCK_SHIFT			15
#define OIC_OMC_LOCK_SHIFT				14
#define OIC_APB_LOCK_SHIFT				13
#define OIC_AXI_LOCK_SHIFT				12
#define DDR_D3_DUTY_SEL_LOCK_SHIFT		11
#define OMC_CLKSEL_LOCK_SHIFT			10
#define DMA_CLKSEL_LOCK_SHIFT			9
#define SWTWM_CLKEN_LOCK_SHIFT			5
#define DMA_CLKEN_LOCK_SHIFT			4
#define OMC_DFI_CLKEN_LOCK_SHIFT		3
#define OMC_PHY_CLKEN_LOCK_SHIFT		2
#define AXI_REG_CLKEN_LOCK_SHIFT		1
#define OIC_AXI_CLKEN_LOCK_SHIFT		0

#define REG_INTF_RST_SLOCK				(REG_CRM_BASE + 0x9010)
#define REG_INTF_RST_LOCK				(REG_CRM_BASE + 0x9014)
#define SDIO1CORE_SRST_LOCK_SHIFT		30
#define SDIO1AXI_SRST_LOCK_SHIFT		29
#define SDIO1AHB_SRST_LOCK_SHIFT		28
#define SDIO0CORE_SRST_LOCK_SHIFT		27
#define SDIO0AXI_SRST_LOCK_SHIFT		26
#define SDIO0AHB_SRST_LOCK_SHIFT		25
#define PNANDREG_SRST_LOCK_SHIFT		24
#define PNANDCORE_SRST_LOCK_SHIFT		23
#define PNANDAXI_SRST_LOCK_SHIFT		22
#define PNANDAHB_SRST_LOCK_SHIFT		21
#define USB30_PHY_LOCK_SHIFT			18
#define USB30_APB_LOCK_SHIFT			17
#define SPI0REG_SRST_LOCK_SHIFT			16
#define SPI0CORE_SRST_LOCK_SHIFT		15
#define SPI0AHB_SRST_LOCK_SHIFT			14
#define UART1_SRST_LOCK_SHIFT			13
#define UART0_SRST_LOCK_SHIFT			12
#define I2C1_SRST_LOCK_SHIFT			11
#define I2C0_SRST_LOCK_SHIFT			10
#define USB1PHY_SRST_LOCK_SHIFT			9
#define USB1CORE_SRST_LOCK_SHIFT		8
#define USB1AXI_SRST_LOCK_SHIFT			7
#define USB1AHB_SRST_LOCK_SHIFT			6
#define USB0PHY_SRST_LOCK_SHIFT			5
#define USB0CORE_SRST_LOCK_SHIFT		4
#define USB0AXI_SRST_LOCK_SHIFT			3
#define USB0AHB_SRST_LOCK_SHIFT			2
#define SMCPHY_SRST_LOCK_SHIFT			1
#define SMC_SRST_LOCK_SHIFT				0

#define REG_INTF_SLOCK					(REG_CRM_BASE + 0x9018)
#define REG_INTF_LOCK					(REG_CRM_BASE + 0x901C)
#define USB_CLKSEL_LOCK_SHIFT			21
#define UART1PHY_CLKSEL_LOCK_SHIFT		20
#define UART0PHY_CLKSEL_LOCK_SHIFT		19
#define SDIO1_CLKSEL_LOCK_SHIFT			18
#define SDIO0_CLKSEL_LOCK_SHIFT			17
#define PNAND_CLKSEL_LOCK_SHIFT			16		/* pnand_core/pnand_high */

#define SPI0_CLKSEL_LOCK_SHIFT			14		/* spi0_high/spi0_core */
#define SMC_PHY_CLKSEL_LOCK_SHIFT		13
#define SDIO1_CLKEN_LOCK_SHIFT			12
#define SDIO0_CLKEN_LOCK_SHIFT			11
#define PNAND_CLKEN_LOCK_SHIFT			10

#define SPI0_CLKEN_LOCK_SHIFT			8
#define UART1_CLKEN_LOCK_SHIFT			7
#define UART0_CLKEN_LOCK_SHIFT			6
#define I2CDEBUG_CLKEN_LOCK_SHIFT		5
#define I2C1_CLKEN_LOCK_SHIFT			4
#define I2C0_CLKEN_LOCK_SHIFT			3
#define USB1_CLKEN_LOCK_SHIFT			2		/* usb1_phy_utmi/usb1_phy/usb1_lfps/usb1_pclk/usb1_aclk/usb1_app */
#define USB0_CLKEN_LOCK_SHIFT			1		/* usb0_phy_utmi/usb0_phy/usb0_dig */
#define SMC_CLKEN_LOCK_SHIFT			0

#define REG_GRA_SLOCK					(REG_CRM_BASE + 0xA118)
#define REG_GRA_LOCK					(REG_CRM_BASE + 0xA11C)
#define GRACORE_LOCK_SHIFT				4
#define GRAAXI_LOCK_SHIFT				3
#define GRAAHB_LOCK_SHIFT				2
#define GRA_CLKSEL_LOCK_SHIFT			1
#define GRA_CLKEN_LOCK_SHIFT			0

#define REG_JPG_SLOCK					(REG_CRM_BASE + 0xA218)
#define REG_JPG_LOCK					(REG_CRM_BASE + 0xA21C)
#define JPGCORE_LOCK_SHIFT				4
#define JPGAXI_LOCK_SHIFT				3
#define JPGAHB_LOCK_SHIFT				2
#define JPG_CLKSEL_LOCK_SHIFT			1
#define JPG_CLKEN_LOCK_SHIFT			0

#define REG_DISP_SLOCK					(REG_CRM_BASE + 0xA318)
#define REG_DISP_LOCK					(REG_CRM_BASE + 0xA31C)
#define DISP_HDVENC_LOCK_SHIFT			12
#define DISP_SDVENC_LOCK_SHIFT			11
#define DISPVDC_LOCK_SHIFT				10
#define DISPOSDC_LOCK_SHIFT				9
#define DISPDI_LOCK_SHIFT				8
#define DISPCORE_LOCK_SHIFT				7
#define DISPAXI_LOCK_SHIFT				6
#define DISPAHB_LOCK_SHIFT				5
#define DISPVDC_CLKSEL_LOCK_SHIFT		4
#define DISPOSDC_CLKSEL_LOCK_SHIFT		3
#define DISPDI_CLKSEL_LOCK_SHIFT		2
#define DISPCORE_CLKSEL_LOCK_SHIFT		1
#define DISP_CLKEN_LOCK_SHIFT			0

#define REG_VDEC_SLOCK					(REG_CRM_BASE + 0xA418)
#define REG_VDEC_LOCK					(REG_CRM_BASE + 0xA41C)
#define VDECCORE_CORE_LOCK_SHIFT		6
#define VDECCORE_LOCK_SHIFT				4
#define VDECAXI_LOCK_SHIFT				3
#define VDECAHB_LOCK_SHIFT				2
#define VDEC_CLKSEL_LOCK_SHIFT			1
#define VDEC_CLKEN_LOCK_SHIFT			0

#define REG_AOUT_SLOCK					(REG_CRM_BASE + 0xA518)
#define REG_AOUT_LOCK					(REG_CRM_BASE + 0xA51C)
#define AOUT_SRC_LOCK_SHIFT				13
#define AOUT_ADAC_LOCK_SHIFT			12
#define AOUT_MCLK_LOCK_SHIFT			11
#define AOUTCORE_LOCK_SHIFT				10
#define AOUTAXI_LOCK_SHIFT				9
#define AOUTAHB_LOCK_SHIFT				8
#define ADAC_MCLK_CLKSEL_LOCK_SHIFT		7
#define SPDF_CLKSEL_LOCK_SHIFT			6
#define AOUT_CLKSEL_LOCK_SHIFT			5
#define ADAC_DIG_DIV_CLKEN_LOCK_SHIFT	4
#define SPDF_DIG_DIV_CLKEN_LOCK_SHIFT	3
#define ADAC_CLKEN_LOCK_SHIFT			2
#define SPDF_CLKEN_LOCK_SHIFT			1
#define AOUT_CLKEN_LOCK_SHIFT			0

#define REG_VOUT_SLOCK					(REG_CRM_BASE + 0xA618)
#define REG_VOUT_LOCK					(REG_CRM_BASE + 0xA61C)
#define HDMI_CORE_LOCK_SHIFT			22
#define HDMI_APB_LOCK_SHIFT				21
#define HDVENC_HD_LOCK_SHIFT			18
#define HDVENC_AHB_LOCK_SHIFT			17
#define VBI_LOCK_SHIFT					16
#define SDVENC_AHB_LOCK_SHIFT			15
#define SDVENC_CORE_LOCK_SHIFT			14
#define HDMI_AUD_CLKSEL_LOCK_SHIFT		13
#define SDVENC_XTAL_CLKSEL_LOCK_SHIFT	12
#define HDMI_XTAL_CLKSEL_LOCK_SHIFT		11
#define HDMI_PIXNX_CLKSEL_LOCK_SHIFT	10
#define HDMI_TMDS_CLKSEL_LOCK_SHIFT		9
#define HDVENC_CLKSEL_LOCK_SHIFT		5
#define HDMI_CLKEN_LOCK_SHIFT			4
#define HDVENC_CLKEN_LOCK_SHIFT			2
#define VBI_CLKEN_LOCK_SHIFT			1
#define SDVENC_CLKEN_LOCK_SHIFT			0

#define REG_PNG_SLOCK					(REG_CRM_BASE + 0xA718)
#define REG_PNG_LOCK					(REG_CRM_BASE + 0xA71C)
#define PNGCORE_LOCK_SHIFT				4
#define PNGAXI_LOCK_SHIFT				3
#define PNGAHB_LOCK_SHIFT				2
#define PNG_CLKSEL_LOCK_SHIFT			1
#define PNG_CLKEN_LOCK_SHIFT			0

#define REG_DAI_SLOCK					(REG_CRM_BASE + 0xA818)
#define REG_DAI_LOCK					(REG_CRM_BASE + 0xA81C)
#define DAI_CLKSEL_LOCK_SHIFT			8
#define DAIDAC_LOCK_SHIFT				6
#define DAIPDM_LOCK_SHIFT				5
#define DAIRX_LOCK_SHIFT				4
#define DAITX_LOCK_SHIFT				3
#define DAIAXI_LOCK_SHIFT				2
#define DAIAHB_LOCK_SHIFT				1
#define DAI_CLKEN_LOCK_SHIFT			0

#define REG_GPU_SLOCK					(REG_CRM_BASE + 0xA918)
#define REG_GPU_LOCK					(REG_CRM_BASE + 0xA91C)
#define GPU_2PSRAM_LOCK_SHIFT			6
#define GPUMBIST_LOCK_SHIFT				5
#define GPUAXI_LOCK_SHIFT				4
#define GPUCORE_LOCK_SHIFT				3
#define GPUAHB_LOCK_SHIFT				2
#define GPU_CLKSEL_LOCK_SHIFT			1
#define GPU_CLKEN_LOCK_SHIFT			0

#define REG_GMAC_SLOCK					(REG_CRM_BASE + 0xAA18)
#define REG_GMAC_LOCK					(REG_CRM_BASE + 0xAA1C)
#define GMACCRM_LOCK_SHIFT				4
#define GMACAXI_LOCK_SHIFT				3
#define GMACAHB_LOCK_SHIFT				2
#define GMAC_CLKSEL_LOCK_SHIFT			1
#define GMAC_CLKEN_LOCK_SHIFT			0

#define REG_TSI_SLOCK					(REG_CRM_BASE + 0xB018)
#define REG_TSI_LOCK					(REG_CRM_BASE + 0xB01C)
#define TSI_FP_REG_LOCK_SHIFT			28
#define TSI_CI_REG_LOCK_SHIFT			27
#define TSI_TRPP_REG_LOCK_SHIFT			26
#define TSI_SF_REG_LOCK_SHIFT			25
#define TSI_T2MI_LOCK_SHIFT				24
#define AVSYNC_AHB_LOCK_SHIFT			23
#define AVSYNC_PCR_LOCK_SHIFT			22
#define AVSYNC_SYS_LOCK_SHIFT			21
#define SF_AXI_LOCK_SHIFT				20
#define TRPP_AXI_LOCK_SHIFT				19
#define SWTSI_AXI_LOCK_SHIFT			18
#define DEMUX_LOCK_SHIFT				17
#define TSPOOL_LOCK_SHIFT				16
#define SWTSI_LOCK_SHIFT				15
#define TRPP_LOCK_SHIFT					14
#define SF_LOCK_SHIFT					13
#define TS3_LOCK_SHIFT					12
#define TS2_LOCK_SHIFT					11
#define TS1_LOCK_SHIFT					10
#define TS0_LOCK_SHIFT					9
#define TSICORE_LOCK_SHIFT				8
#define TSIAXI_LOCK_SHIFT				7
#define TSIAHB_LOCK_SHIFT				6
#define TS0_CLKSEL_LOCK_SHIFT			5
#define TS1_CLKSEL_LOCK_SHIFT			4
#define TS2_CLKSEL_LOCK_SHIFT			3
#define TS3_CLKSEL_LOCK_SHIFT			2
#define TSI_CLKSEL_LOCK_SHIFT			1
#define TSI_CLKEN_LOCK_SHIFT			0

#define REG_CI_SLOCK					(REG_CRM_BASE + 0xB118)
#define REG_CI_LOCK						(REG_CRM_BASE + 0xB11C)
#define CIAHB_LOCK_SHIFT				3
#define CI_CLKEN_LOCK_SHIFT				0

#define REG_SECURE_SLOCK				(REG_CRM_BASE + 0xC01C)
#define REG_SECURE_LOCK					(REG_CRM_BASE + 0xC018)
#define M2M_CORE1_LOCK_SHIFT			27
#define DS_M2REG_LOCK_SHIFT				26
#define DS_M2CORE_LOCK_SHIFT			25
#define DS_LOCK_SHIFT					24
#define M2M_CIPHER_LOCK_SHIFT			23
#define M2M_AHB_LOCK_SHIFT				22
#define M2M_AXI_LOCK_SHIFT				21
#define M2M_CORE_LOCK_SHIFT				20
#define PKA_IBUS_LOCK_SHIFT				19
#define PKA_CORE_LOCK_SHIFT				18
#define GLITCH_DET_LOCK_SHIFT			17
#define KT_IBUS_LOCK_SHIFT				16
#define KT_CORE_LOCK_SHIFT				15
#define SECHD0_LOCK_SHIFT				14
#define KL_LOCK_SHIFT					13
#define PKA_LOCK_SHIFT					12
#define DS_CLKSEL_LOCK_SHIFT			11
#define M2M_CIPHER_CLKSEL_LOCK_SHIFT	10
#define SECURE_CLKSEL_LOCK_SHIFT		9
#define DS_CLKEN_LOCK_SHIFT				8
#define M2M_CLKEN_LOCK_SHIFT			7
#define PKA_CLKEN_LOCK_SHIFT			6
#define GLITCHDET_CLKEN_LOCK_SHIFT		5
#define KT_CLKEN_LOCK_SHIFT				4
#define SECHD0_CLKEN_LOCK_SHIFT			3
#define KL_CLKEN_LOCK_SHIFT				2
#define KDF_CLKEN_LOCK_SHIFT			1
#define SECMISC_CLKEN_LOCK_SHIFT		0

#define REG_IFCP_SLOCK					(REG_CRM_BASE + 0xC818)
#define REG_IFCP_LOCK					(REG_CRM_BASE + 0xC81C)
#define IFCP_VSCPU_MODE_LOCK_SHIFT		4
#define IFCP_CRYPTO_CLKSEL_LOCK_SHIFT	3
#define IFCP_SYS_CLKSEL_LOCK_SHIFT		2
#define IFCP_KLM_CLKEN_LOCK_SHIFT		1
#define IFCP_CRYPTO_CLKEN_LOCK_SHIFT	0

////TOP
#define REG_TOPCLK_CTRL0_SLOCK			(REG_CRM_BASE + 0xF81C)
#define REG_TOPCLK_CTRL0_LOCK			(REG_CRM_BASE + 0xF820)
#define CTRL0_GROUP7_LOCK_SHIFT			7
#define CTRL0_GROUP6_LOCK_SHIFT			6
#define CTRL0_GROUP5_LOCK_SHIFT			5
#define CTRL0_GROUP4_LOCK_SHIFT			4
#define CTRL0_GROUP3_LOCK_SHIFT			3
#define CTRL0_GROUP2_LOCK_SHIFT			2
#define CTRL0_GROUP1_LOCK_SHIFT			1
#define CTRL0_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL1_SLOCK			(REG_CRM_BASE + 0xF824)
#define REG_TOPCLK_CTRL1_LOCK			(REG_CRM_BASE + 0xF828)
#define CTRL1_GROUP7_LOCK_SHIFT			7
#define CTRL1_GROUP6_LOCK_SHIFT			6
#define CTRL1_GROUP5_LOCK_SHIFT			5
#define CTRL1_GROUP4_LOCK_SHIFT			4
#define CTRL1_GROUP3_LOCK_SHIFT			3
#define CTRL1_GROUP2_LOCK_SHIFT			2
#define CTRL1_GROUP1_LOCK_SHIFT			1
#define CTRL1_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL2_SLOCK			(REG_CRM_BASE + 0xF82C)
#define REG_TOPCLK_CTRL2_LOCK			(REG_CRM_BASE + 0xF830)
#define CTRL2_GROUP7_LOCK_SHIFT			7
#define CTRL2_GROUP6_LOCK_SHIFT			6
#define CTRL2_GROUP5_LOCK_SHIFT			5
#define CTRL2_GROUP4_LOCK_SHIFT			4
#define CTRL2_GROUP3_LOCK_SHIFT			3
#define CTRL2_GROUP2_LOCK_SHIFT			2
#define CTRL2_GROUP1_LOCK_SHIFT			1
#define CTRL2_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL3_SLOCK			(REG_CRM_BASE + 0xF834)
#define REG_TOPCLK_CTRL3_LOCK			(REG_CRM_BASE + 0xF838)
#define CTRL3_GROUP7_LOCK_SHIFT			7
#define CTRL3_GROUP6_LOCK_SHIFT			6
#define CTRL3_GROUP5_LOCK_SHIFT			5
#define CTRL3_GROUP4_LOCK_SHIFT			4
#define CTRL3_GROUP3_LOCK_SHIFT			3
#define CTRL3_GROUP2_LOCK_SHIFT			2
#define CTRL3_GROUP1_LOCK_SHIFT			1
#define CTRL3_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL4_SLOCK			(REG_CRM_BASE + 0xF83C)
#define REG_TOPCLK_CTRL4_LOCK			(REG_CRM_BASE + 0xF840)
#define CTRL4_GROUP7_LOCK_SHIFT			7
#define CTRL4_GROUP6_LOCK_SHIFT			6
#define CTRL4_GROUP5_LOCK_SHIFT			5
#define CTRL4_GROUP4_LOCK_SHIFT			4
#define CTRL4_GROUP3_LOCK_SHIFT			3
#define CTRL4_GROUP2_LOCK_SHIFT			2
#define CTRL4_GROUP1_LOCK_SHIFT			1
#define CTRL4_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL5_SLOCK			(REG_CRM_BASE + 0xF844)
#define REG_TOPCLK_CTRL5_LOCK			(REG_CRM_BASE + 0xF848)
#define CTRL5_GROUP7_LOCK_SHIFT			7
#define CTRL5_GROUP6_LOCK_SHIFT			6
#define CTRL5_GROUP5_LOCK_SHIFT			5
#define CTRL5_GROUP4_LOCK_SHIFT			4
#define CTRL5_GROUP3_LOCK_SHIFT			3
#define CTRL5_GROUP2_LOCK_SHIFT			2
#define CTRL5_GROUP1_LOCK_SHIFT			1
#define CTRL5_GROUP0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL6_SLOCK			(REG_CRM_BASE + 0xF84C)
#define REG_TOPCLK_CTRL6_LOCK			(REG_CRM_BASE + 0xF850)
#define CTRL6_BIT25_LOCK_SHIFT			25
#define CTRL6_BIT24_LOCK_SHIFT			24
#define CTRL6_BIT23_LOCK_SHIFT			23
#define CTRL6_BIT22_LOCK_SHIFT			22
#define CTRL6_BIT21_LOCK_SHIFT			21
#define CTRL6_BIT20_LOCK_SHIFT			20
#define CTRL6_BIT19_LOCK_SHIFT			19
#define CTRL6_BIT18_LOCK_SHIFT			18
#define CTRL6_BIT17_LOCK_SHIFT			17
#define CTRL6_BIT16_LOCK_SHIFT			16
#define CTRL6_BIT15_LOCK_SHIFT			15
#define CTRL6_BIT14_LOCK_SHIFT			14
#define CTRL6_BIT13_LOCK_SHIFT			13
#define CTRL6_BIT12_LOCK_SHIFT			12
#define CTRL6_BIT11_LOCK_SHIFT			11
#define CTRL6_BIT10_LOCK_SHIFT			10
#define CTRL6_BIT9_LOCK_SHIFT			9
#define CTRL6_BIT8_LOCK_SHIFT			8
#define CTRL6_BIT7_LOCK_SHIFT			7
#define CTRL6_BIT6_LOCK_SHIFT			6
#define CTRL6_BIT5_LOCK_SHIFT			5
#define CTRL6_BIT4_LOCK_SHIFT			4
#define CTRL6_BIT3_LOCK_SHIFT			3
#define CTRL6_BIT2_LOCK_SHIFT			2
#define CTRL6_BIT1_LOCK_SHIFT			1
#define CTRL6_BIT0_LOCK_SHIFT			0

#define REG_TOPCLK_CTRL7_SLOCK			(REG_CRM_BASE + 0xF858)
#define REG_TOPCLK_CTRL7_LOCK			(REG_CRM_BASE + 0xF85C)
#define ARMPLL_DELAY_SET_LOCK_SHIFT		0

////WDOGEXP
#define REG_WDOGEXP_SLOCK				(REG_CRM_BASE + 0xFA10)
#define REG_WDOGEXP_LOCK				(REG_CRM_BASE + 0xFA14)
#define WDOGEXP_AXI_MON_LOCK_SHIFT		18
#define WDOGEXP_TSENSOR_LOCK_SHIFT		17
#define WDOGEXP_WD1_LOCK_SHIFT			16
#define WDOGEXP_ARMC1_PC_LOCK_SHIFT		15
#define WDOGEXP_ARMC0_PC_LOCK_SHIFT		14
#define WDOGEXP_AVCPU_PC_LOCK_SHIFT		13
#define WDOGEXP_ARMCPU_LOCK_SHIFT		12
#define WDOGEXP_OTP_BGC_LOCK_SHIFT		11
#define WDOGEXP_IFCP_LOCK_SHIFT			10
#define WDOGEXP_GLITCH_LOCK_SHIFT		9
#define WDOGEXP_CLKMNT_LOCK_SHIFT		8
#define WDOGEXP_RST_LOCK_SHIFT			7
#define WDOGEXP_M2M_LOCK_SHIFT			6
#define WDOGEXP_AOWD_LOCK_SHIFT			5
#define WDOGEXP_OTP_FSM_LOCK_SHIFT		4
#define WDOGEXP_SANDWICH_LOCK_SHIFT		3
#define WDOGEXP_VSCPU_PC_LOCK_SHIFT		2
#define WDOGEXP_WD0_LOCK_SHIFT			1
#define WDOGEXP_RSTTIME_LOCK_SHIFT		0

////AO
#define REG_AOCRM_SLOCK					(REG_AO_CRM_BASE + 0x894)
#define REG_AOCRM_LOCK					(REG_AO_CRM_BASE + 0x898)
#define XTALSEL_LOCK_SHIFT				19
#define WDOG_LOCK_SHIFT					18
#define AOMCU_LOCK_SHIFT				17
#define AGTIMER_LOCK_SHIFT				16
#define AVS_LOCK_SHIFT					15
#define CEC_LOCK_SHIFT					14
#define MAILBOX_LOCK_SHIFT				13
#define MNT_LOCK_SHIFT					12
#define TIMER_LOCK_SHIFT				11
#define PINMUX_LOCK_SHIFT				10
#define RECRAM_LOCK_SHIFT				9
#define FPSPI_LOCK_SHIFT				8
#define FPI2C_LOCK_SHIFT				7
#define ANA_LOCK_SHIFT					6
#define KADC_LOCK_SHIFT					5
#define GPIO_LOCK_SHIFT					4
#define LEDKB_LOCK_SHIFT				3
#define RTC_LOCK_SHIFT					2
#define IRDA_LOCK_SHIFT					1
#define LPM_LOCK_SHIFT					0

////ANA_SW
#define REG_ANA_SW_SLOCK				(REG_ANALOG_SW_BASE + 0xE0)
#define REG_ANA_SW_LOCK					(REG_ANALOG_SW_BASE + 0x10C)
#define TSENSOR_RST_REQ_TH_LOCK_SHIFT	25
#define USB3P0_PLL_REG_LOCK_SHIFT		24
#define USB3P0_SSC_REG2_LOCK_SHIFT		23
#define USB3P0_SSC_REG1_LOCK_SHIFT		22
#define CLKGEN_EPHY_REG_LOCK_SHIFT		21
#define TSENSOR_REG_LOCK_SHIFT			20
#define BIAS_REG_LOCK_SHIFT				19
#define PM_SW_REG_LOCK_SHIFT			18
#define CLKGEN_VSDSSC_REG_LOCK_SHIFT	17
#define CLKGEN_USBACLK_REG_LOCK_SHIFT	16
#define CLKEN_VHDSSC_REG_LOCK_SHIFT		15
#define ANA_TOP_REG3_LOCK_SHIFT			14
#define OTPREG25_REG_LOCK_SHIFT			13
#define ANA_TOP_REG2_LOCK_SHIFT			12
#define INTP_CTRL_REG_LOCK_SHIFT		11	/* INTP_CTRL, VIDEO_SW */
#define CLKGEN_VSDINTP_REG_LOCK_SHIFT	10
#define CLKGEN_CPUPLL_REG_LOCK_SHIFT	9
#define CLKGEN_PDSYS_REG_LOCK_SHIFT		8
#define CLKGEN_USBPLL_REG_LOCK_SHIFT	7
#define CLKGEN_TEST_REG_LOCK_SHIFT		6
#define CLKGEN_ETHINTP_REG_LOCK_SHIFT	5
#define CLKGEN_VSDPLL_REG_LOCK_SHIFT	4
#define CLKGEN_VHDPLL_REG_LOCK_SHIFT	3
#define CLKGEN_VHDINTP_REG_LOCK_SHIFT	2
#define ANA_TOP_REG1_LOCK_SHIFT			1
#define ANA_TOP_REG0_LOCK_SHIFT			0

////ANA_AO
#define REG_ANA_AO_SLOCK				(REG_AO_ANALOG_BASE + 0x08)
#define REG_ANA_AO_LOCK					(REG_AO_ANALOG_BASE + 0x0C)
#define AVS_SYS_REG_LOCK_SHIFT			4
#define AVS_CPU_REG_LOCK_SHIFT			3
#define ANA_AO_REG0_BIT0_BIT24_LOCK_SHIFT	2
#define ANA_AO_REG1_LOCK_SHIFT			1
#define ANA_AO_REG0_LOCK_SHIFT			0

#endif

