include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall all_objs_phony

all:
	$(MAKE) -f lib.mk


all_objs_phony:
	$(MAKE) -f lib.mk all_objs_phony


clean:
	$(MAKE) -f lib.mk clean


install:
	$(MAKE) -f lib.mk install


uninstall:
	$(MAKE) -f lib.mk uninstall

