include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall

all:
	$(MAKE) -f sample_text.mk
	$(MAKE) -f sample_scrolltext.mk
	$(MAKE) -f sample_optlayer.mk
	$(MAKE) -f sample_draw.mk
	$(MAKE) -f sample_decpic.mk
	$(MAKE) -f sample_opacity.mk
	$(MAKE) -f sample_layerperformance.mk
	$(MAKE) -f sample_bit.mk
	$(MAKE) -f sample_rotate_mirror.mk
	$(MAKE) -f sample_loop_pic.mk
	
clean:
	$(MAKE) -f sample_text.mk clean
	$(MAKE) -f sample_scrolltext.mk clean
	$(MAKE) -f sample_optlayer.mk clean
	$(MAKE) -f sample_draw.mk clean
	$(MAKE) -f sample_decpic.mk clean
	$(MAKE) -f sample_opacity.mk clean
	$(MAKE) -f sample_layerperformance.mk clean
	$(MAKE) -f sample_bit.mk clean
	$(MAKE) -f sample_rotate_mirror.mk clean
	$(MAKE) -f sample_loop_pic.mk clean
install:
	$(MAKE) -f sample_text.mk install
	$(MAKE) -f sample_scrolltext.mk install
	$(MAKE) -f sample_optlayer.mk install
	$(MAKE) -f sample_draw.mk install
	$(MAKE) -f sample_decpic.mk install
	$(MAKE) -f sample_opacity.mk install
	$(MAKE) -f sample_layerperformance.mk install
	$(MAKE) -f sample_bit.mk install
	$(MAKE) -f sample_rotate_mirror.mk install
	$(MAKE) -f sample_loop_pic.mk install
uninstall:
	$(MAKE) -f sample_text.mk uninstall
	$(MAKE) -f sample_scrolltext.mk uninstall
	$(MAKE) -f sample_optlayer.mk uninstall
	$(MAKE) -f sample_draw.mk uninstall
	$(MAKE) -f sample_decpic.mk uninstall
	$(MAKE) -f sample_opacity.mk uninstall
	$(MAKE) -f sample_layerperformance.mk uninstall
	$(MAKE) -f sample_bit.mk uninstall
	$(MAKE) -f sample_rotate_mirror.mk uninstall
	$(MAKE) -f sample_loop_pic.mk uninstall