/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2016 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
#ifndef __SD_ENC_ARIA_REG_H__
#define __SD_ENC_ARIA_REG_H__
#include "mt_type.h"

extern ulong p_sdenc_addr;
extern ulong p_vbi_addr;

#define REG_ARIA_SD_ENCODER_BASE_PHY 0xffdd0000

#define REG_ARIA_SD_ENCODER_BASE_VIRT 0xf8dd0000

#define REG_SYMPHONY_SD_ENCODER_BASE 0xbf460000

#define REG_SYMPHONY_VBI_REG_BASE 0xbf450000

#if defined(CONFIG_MT_CHIP_ARIA) || defined(SYMPHONY_LINUX)
#define REG_ARIA_SD_ENCODER_BASE (p_sdenc_addr)
#endif

#ifdef SYMPHONY_LINUX
#define REG_SYMPHONY_VBI_BASE p_vbi_addr
#endif

/*!
  the enum of ARIA_SD_ENC registers
  */
#define  REG_ARIA_SD_ENC_SD_ENC_MODE        (REG_ARIA_SD_ENCODER_BASE + 0x0)
#define  REG_ARIA_SD_ENC_SD_ENC_CURVE       (REG_ARIA_SD_ENCODER_BASE + 0x4)
#define  REG_ARIA_SD_ENC_DELAY             (REG_ARIA_SD_ENCODER_BASE + 0x8)
#define  REG_ARIA_SD_ENC_BLANK_P             (REG_ARIA_SD_ENCODER_BASE + 0xc)
#define  REG_ARIA_SD_ENC_BLANK_N             (REG_ARIA_SD_ENCODER_BASE + 0x10)
#define  REG_ARIA_SD_ENC_CBLANK             (REG_ARIA_SD_ENCODER_BASE + 0x14)
#define  REG_ARIA_SD_ENC_VDAC_PCARRY             (REG_ARIA_SD_ENCODER_BASE + 0x18)
#define  REG_ARIA_SD_ENC_VDAC_NCARRY             (REG_ARIA_SD_ENCODER_BASE + 0x1c)
#define  REG_ARIA_SD_ENC_CFIG1              (REG_ARIA_SD_ENCODER_BASE + 0x20)
#define  REG_ARIA_SD_ENC_CFIG2              (REG_ARIA_SD_ENCODER_BASE + 0x24)
#define  REG_ARIA_SD_ENC_CFIG3              (REG_ARIA_SD_ENCODER_BASE + 0x28)
#define  REG_ARIA_SD_ENC_CFIG4              (REG_ARIA_SD_ENCODER_BASE + 0x2c)
#define  REG_ARIA_SD_ENC_CFIG5              (REG_ARIA_SD_ENCODER_BASE + 0x30)
#define  REG_ARIA_SD_ENC_CFIG6        (REG_ARIA_SD_ENCODER_BASE + 0x34)
#define  REG_ARIA_SD_ENC_CFIG7              (REG_ARIA_SD_ENCODER_BASE + 0x38)
#define  REG_ARIA_SD_ENC_SET                (REG_ARIA_SD_ENCODER_BASE + 0x3c)
#define  REG_ARIA_SD_ENC_DAC0_PARA          (REG_ARIA_SD_ENCODER_BASE + 0x40)
#define  REG_ARIA_SD_ENC_DRCOEF          (REG_ARIA_SD_ENCODER_BASE + 0x44)
#define  REG_ARIA_SD_ENC_DBCOEF          (REG_ARIA_SD_ENCODER_BASE + 0x48)
#define  REG_ARIA_SD_ENC_CAMPCOEF              (REG_ARIA_SD_ENCODER_BASE + 0x4c)
#define  REG_ARIA_SD_ENC_SCARRYDR              (REG_ARIA_SD_ENCODER_BASE + 0x50)
#define  REG_ARIA_SD_ENC_SCARRYDB              (REG_ARIA_SD_ENCODER_BASE + 0x54)
#define  REG_ARIA_SD_ENC_PINCREMENT              (REG_ARIA_SD_ENCODER_BASE + 0x58)
#define  REG_ARIA_SD_ENC_NINCREMENT              (REG_ARIA_SD_ENCODER_BASE + 0x5c)
#define  REG_ARIA_SD_ENC_GCONTROL           (REG_ARIA_SD_ENCODER_BASE + 0x60)
#define  REG_ARIA_SD_ENC_SD_ENC_DACNUM      (REG_ARIA_SD_ENCODER_BASE + 0x64)
#define  REG_ARIA_SD_ENC_INSTM              (REG_ARIA_SD_ENCODER_BASE + 0x68)
#define  REG_ARIA_SD_ENC_COMPRESS           (REG_ARIA_SD_ENCODER_BASE + 0x6c)
#define  REG_ARIA_SD_ENC_SET1               (REG_ARIA_SD_ENCODER_BASE + 0x70)
#define  REG_ARIA_SD_ENC_SET2               (REG_ARIA_SD_ENCODER_BASE + 0x74)
#define  REG_ARIA_SD_ENC_SET3               (REG_ARIA_SD_ENCODER_BASE + 0x78)
#define  REG_ARIA_SD_ENC_LUM_DLY_108M       (REG_ARIA_SD_ENCODER_BASE + 0x7c)
#define  REG_ARIA_SD_ENC_COEF11               (REG_ARIA_SD_ENCODER_BASE + 0x80)
#define  REG_ARIA_SD_ENC_COEF10               (REG_ARIA_SD_ENCODER_BASE + 0x84)
#define  REG_ARIA_SD_ENC_COEF9               (REG_ARIA_SD_ENCODER_BASE + 0x88)
#define  REG_ARIA_SD_ENC_COEF8               (REG_ARIA_SD_ENCODER_BASE + 0x8c)
#define  REG_ARIA_SD_ENC_COEF7               (REG_ARIA_SD_ENCODER_BASE + 0x90)
#define  REG_ARIA_SD_ENC_COEF6               (REG_ARIA_SD_ENCODER_BASE + 0x94)
#define  REG_ARIA_SD_ENC_COEF5               (REG_ARIA_SD_ENCODER_BASE + 0x98)
#define  REG_ARIA_SD_ENC_COEF4               (REG_ARIA_SD_ENCODER_BASE + 0x9c)
#define  REG_ARIA_SD_ENC_COEF3               (REG_ARIA_SD_ENCODER_BASE + 0xa0)
#define  REG_ARIA_SD_ENC_COEF2               (REG_ARIA_SD_ENCODER_BASE + 0xa4)
#define  REG_ARIA_SD_ENC_COEF1               (REG_ARIA_SD_ENCODER_BASE + 0xa8)
#define  REG_ARIA_SD_ENC_COEF0               (REG_ARIA_SD_ENCODER_BASE + 0xac)
#define  REG_ARIA_SD_ENC_COEF_C_LUT3_U               (REG_ARIA_SD_ENCODER_BASE + 0xb0)
#define  REG_ARIA_SD_ENC_COEF_C_LUT2_U                (REG_ARIA_SD_ENCODER_BASE + 0xb4)
#define  REG_ARIA_SD_ENC_COEF_C_LUT1_U                (REG_ARIA_SD_ENCODER_BASE + 0xb8)
#define  REG_ARIA_SD_ENC_COEF_C_LUT0_U                (REG_ARIA_SD_ENCODER_BASE + 0xbc)
#define  REG_ARIA_SD_ENC_COEF_C_LUT3_V      (REG_ARIA_SD_ENCODER_BASE + 0xc0)
#define  REG_ARIA_SD_ENC_COEF_C_LUT2_V      (REG_ARIA_SD_ENCODER_BASE + 0xc4)
#define  REG_ARIA_SD_ENC_COEF_C_LUT1_V      (REG_ARIA_SD_ENCODER_BASE + 0xc8)
#define  REG_ARIA_SD_ENC_COEF_C_LUT0_V      (REG_ARIA_SD_ENCODER_BASE + 0xcc)
#define  REG_ARIA_SD_ENC_COEF_LUT3_Y        (REG_ARIA_SD_ENCODER_BASE + 0xd0)
#define  REG_ARIA_SD_ENC_COEF_LUT2_Y        (REG_ARIA_SD_ENCODER_BASE + 0xd4)
#define  REG_ARIA_SD_ENC_COEF_LUT1_Y        (REG_ARIA_SD_ENCODER_BASE + 0xd8)
#define  REG_ARIA_SD_ENC_COEF_LUT0_Y        (REG_ARIA_SD_ENCODER_BASE + 0xdc)
#define  REG_ARIA_SD_ENC_SIGN_CTL           (REG_ARIA_SD_ENCODER_BASE + 0xe0)
#define  REG_ARIA_SD_ENC_DAC_OFFSET         (REG_ARIA_SD_ENCODER_BASE + 0xe4)
#define  REG_ARIA_SD_ENC_DAC123_PARA        (REG_ARIA_SD_ENCODER_BASE + 0xe8)
#define  REG_ARIA_SD_ENC_DAC0_ANTI_COEF1_0        (REG_ARIA_SD_ENCODER_BASE + 0xf0)
#define  REG_ARIA_SD_ENC_DAC0_ANTI_COEF3_2        (REG_ARIA_SD_ENCODER_BASE + 0xf4)
#define  REG_ARIA_SD_ENC_DAC123_ANTI_COEF1_0        (REG_ARIA_SD_ENCODER_BASE + 0xf8)
#define  REG_ARIA_SD_ENC_DAC123_ANTI_COEF3_2        (REG_ARIA_SD_ENCODER_BASE + 0xfc)

#define REG_SYMPHONY_SD_ENCODER_MODE                 (REG_ARIA_SD_ENCODER_BASE + 0x00)
#define REG_SYMPHONY_SD_ENCODER_CURVE                (REG_ARIA_SD_ENCODER_BASE + 0x04)
#define REG_SYMPHONY_SD_ENCODER_DELAY                (REG_ARIA_SD_ENCODER_BASE + 0x08)
#define REG_SYMPHONY_SD_ENCODER_BLANK_P              (REG_ARIA_SD_ENCODER_BASE + 0x0c)
#define REG_SYMPHONY_SD_ENCODER_BLANK_N              (REG_ARIA_SD_ENCODER_BASE + 0x10)
#define REG_SYMPHONY_SD_ENCODER_CBLANK               (REG_ARIA_SD_ENCODER_BASE + 0x14)
#define REG_SYMPHONY_SD_ENCODER_VDAC_PCARRY          (REG_ARIA_SD_ENCODER_BASE + 0x18)
#define REG_SYMPHONY_SD_ENCODER_VDAC_NCARRY          (REG_ARIA_SD_ENCODER_BASE + 0x1c)
#define REG_SYMPHONY_SD_ENCODER_CFIG1                (REG_ARIA_SD_ENCODER_BASE + 0x20)
#define REG_SYMPHONY_SD_ENCODER_CFIG2                (REG_ARIA_SD_ENCODER_BASE + 0x24)
#define REG_SYMPHONY_SD_ENCODER_CFIG3                (REG_ARIA_SD_ENCODER_BASE + 0x28)
#define REG_SYMPHONY_SD_ENCODER_CFIG4                (REG_ARIA_SD_ENCODER_BASE + 0x2c)
#define REG_SYMPHONY_SD_ENCODER_CFIG5                (REG_ARIA_SD_ENCODER_BASE + 0x30)
#define REG_SYMPHONY_SD_ENCODER_CFIG6                (REG_ARIA_SD_ENCODER_BASE + 0x34)
#define REG_SYMPHONY_SD_ENCODER_CFIG7                (REG_ARIA_SD_ENCODER_BASE + 0x38)
#define REG_SYMPHONY_SD_ENCODER_SET                  (REG_ARIA_SD_ENCODER_BASE + 0x3c)
#define REG_SYMPHONY_SD_ENCODER_DAC0_PARA            (REG_ARIA_SD_ENCODER_BASE + 0x40)
#define REG_SYMPHONY_SD_ENCODER_DRCOEF               (REG_ARIA_SD_ENCODER_BASE + 0x44)
#define REG_SYMPHONY_SD_ENCODER_DBCOEF               (REG_ARIA_SD_ENCODER_BASE + 0x48)
#define REG_SYMPHONY_SD_ENCODER_CFIG8                (REG_ARIA_SD_ENCODER_BASE + 0x4c)
#define REG_SYMPHONY_SD_ENCODER_SCARRYDR             (REG_ARIA_SD_ENCODER_BASE + 0x50)
#define REG_SYMPHONY_SD_ENCODER_SCARRYDB             (REG_ARIA_SD_ENCODER_BASE + 0x54)
#define REG_SYMPHONY_SD_ENCODER_PINCREMENT           (REG_ARIA_SD_ENCODER_BASE + 0x58)
#define REG_SYMPHONY_SD_ENCODER_NINCREMENT           (REG_ARIA_SD_ENCODER_BASE + 0x5c)
#define REG_SYMPHONY_SD_ENCODER_GCONTROL             (REG_ARIA_SD_ENCODER_BASE + 0x60)
#define REG_SYMPHONY_SD_ENCODER_DACNUM               (REG_ARIA_SD_ENCODER_BASE + 0x64)
#define REG_SYMPHONY_SD_ENCODER_INSTM                (REG_ARIA_SD_ENCODER_BASE + 0x68)
#define REG_SYMPHONY_SD_ENCODER_COMPRESS             (REG_ARIA_SD_ENCODER_BASE + 0x6c)
#define REG_SYMPHONY_SD_ENCODER_SET1                 (REG_ARIA_SD_ENCODER_BASE + 0x70)
#define REG_SYMPHONY_SD_ENCODER_SET2                 (REG_ARIA_SD_ENCODER_BASE + 0x74)
#define REG_SYMPHONY_SD_ENCODER_SET3                 (REG_ARIA_SD_ENCODER_BASE + 0x78)
#define REG_SYMPHONY_SD_ENCODER_LUM_DLY_108M         (REG_ARIA_SD_ENCODER_BASE + 0x7c)
#define REG_SYMPHONY_SD_ENCODER_COEF11               (REG_ARIA_SD_ENCODER_BASE + 0x80)
#define REG_SYMPHONY_SD_ENCODER_COEF10               (REG_ARIA_SD_ENCODER_BASE + 0x84)
#define REG_SYMPHONY_SD_ENCODER_COEF9                (REG_ARIA_SD_ENCODER_BASE + 0x88)
#define REG_SYMPHONY_SD_ENCODER_COEF8                (REG_ARIA_SD_ENCODER_BASE + 0x8c)
#define REG_SYMPHONY_SD_ENCODER_COEF7                (REG_ARIA_SD_ENCODER_BASE + 0x90)
#define REG_SYMPHONY_SD_ENCODER_COEF6                (REG_ARIA_SD_ENCODER_BASE + 0x94)
#define REG_SYMPHONY_SD_ENCODER_COEF5                (REG_ARIA_SD_ENCODER_BASE + 0x98)
#define REG_SYMPHONY_SD_ENCODER_COEF4                (REG_ARIA_SD_ENCODER_BASE + 0x9c)
#define REG_SYMPHONY_SD_ENCODER_COEF3                (REG_ARIA_SD_ENCODER_BASE + 0xa0)
#define REG_SYMPHONY_SD_ENCODER_COEF2                (REG_ARIA_SD_ENCODER_BASE + 0xa4)
#define REG_SYMPHONY_SD_ENCODER_COEF1                (REG_ARIA_SD_ENCODER_BASE + 0xa8)
#define REG_SYMPHONY_SD_ENCODER_COEF0                (REG_ARIA_SD_ENCODER_BASE + 0xac)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT3_U        (REG_ARIA_SD_ENCODER_BASE + 0xb0)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT2_U        (REG_ARIA_SD_ENCODER_BASE + 0xb4)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT1_U        (REG_ARIA_SD_ENCODER_BASE + 0xb8)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT0_U        (REG_ARIA_SD_ENCODER_BASE + 0xbc)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT3_V        (REG_ARIA_SD_ENCODER_BASE + 0xc0)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT2_V        (REG_ARIA_SD_ENCODER_BASE + 0xc4)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT1_V        (REG_ARIA_SD_ENCODER_BASE + 0xc8)
#define REG_SYMPHONY_SD_ENCODER_COEF_C_LUT0_V        (REG_ARIA_SD_ENCODER_BASE + 0xcc)
#define REG_SYMPHONY_SD_ENCODER_COEF_LUT3_Y          (REG_ARIA_SD_ENCODER_BASE + 0xd0)
#define REG_SYMPHONY_SD_ENCODER_COEF_LUT2_Y          (REG_ARIA_SD_ENCODER_BASE + 0xd4)
#define REG_SYMPHONY_SD_ENCODER_COEF_LUT1_Y          (REG_ARIA_SD_ENCODER_BASE + 0xd8)
#define REG_SYMPHONY_SD_ENCODER_COEF_LUT0_Y          (REG_ARIA_SD_ENCODER_BASE + 0xdc)
#define REG_SYMPHONY_SD_ENCODER_SIGN_CTL             (REG_ARIA_SD_ENCODER_BASE + 0xe0)
#define REG_SYMPHONY_SD_ENCODER_DAC_OFFSET           (REG_ARIA_SD_ENCODER_BASE + 0xe4)
#define REG_SYMPHONY_SD_ENCODER_DAC123_PARA          (REG_ARIA_SD_ENCODER_BASE + 0xe8)
#define REG_SYMPHONY_SD_ENCODER_SDVENC_SET           (REG_ARIA_SD_ENCODER_BASE + 0xec)
#define REG_SYMPHONY_SD_ENCODER_DAC0_ANTI_COEF1_0    (REG_ARIA_SD_ENCODER_BASE + 0xf0)
#define REG_SYMPHONY_SD_ENCODER_DAC0_ANTI_COEF3_2    (REG_ARIA_SD_ENCODER_BASE + 0xf4)
#define REG_SYMPHONY_SD_ENCODER_DAC123_ANTI_COEF1_0  (REG_ARIA_SD_ENCODER_BASE + 0xf8)
#define REG_SYMPHONY_SD_ENCODER_DAC123_ANTI_COEF3_2  (REG_ARIA_SD_ENCODER_BASE + 0xfc)

#if defined(CONFIG_MT_CHIP_ARIA)
#define  REG_ARIA_SD_ENC_VBI_CTRL    (REG_ARIA_SD_ENCODER_BASE + 0x200)
#define  REG_ARIA_SD_ENC_VBI_SOFT_CTRL    (REG_ARIA_SD_ENCODER_BASE + 0x204)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA1_REG    (REG_ARIA_SD_ENCODER_BASE + 0x20c)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA2_REG    (REG_ARIA_SD_ENCODER_BASE + 0x210)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA3_REG    (REG_ARIA_SD_ENCODER_BASE + 0x214)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA4_REG    (REG_ARIA_SD_ENCODER_BASE + 0x218)
#define  REG_ARIA_SD_ENC_VBI_WSS_DATA_REG   (REG_ARIA_SD_ENCODER_BASE + 0x21c)
#define  REG_ARIA_SD_ENC_VBI_FIFO_CNT    (REG_ARIA_SD_ENCODER_BASE + 0x230)
#define  REG_ARIA_SD_ENC_VBI_INT_MASK_N0    (REG_ARIA_SD_ENCODER_BASE + 0x234)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE_CLR0 (REG_ARIA_SD_ENCODER_BASE + 0x238)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE0     (REG_ARIA_SD_ENCODER_BASE + 0x23c)
#define  REG_ARIA_SD_ENC_VBI_CGMSA_DATA    (REG_ARIA_SD_ENCODER_BASE + 0x244)
#define  REG_ARIA_SD_ENC_VBI_INT_MASK_N1    (REG_ARIA_SD_ENCODER_BASE + 0x248)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE_CLR1 (REG_ARIA_SD_ENCODER_BASE + 0x24c)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE1     (REG_ARIA_SD_ENCODER_BASE + 0x250)
#define  REG_ARIA_SD_ENC_VBI_FIFO_REG     (REG_ARIA_SD_ENCODER_BASE + 0x254)
#elif defined(CONFIG_MT_CHIP_SYMPHONY1) || defined(CONFIG_MT_CHIP_SYMPHONY2) || defined(CONFIG_MT_CHIP_SYMPHONY4) || defined(CONFIG_MT_CHIP_SYMPHONY6)  //sym6 need to add sym6 configure
#define  REG_ARIA_SD_ENC_VBI_CTRL    (REG_SYMPHONY_VBI_BASE + 0x00)
#define  REG_ARIA_SD_ENC_VBI_SOFT_CTRL    (REG_SYMPHONY_VBI_BASE + 0x04)
#define  REG_ARIA_SD_ENC_VBI_CC_DATA_REG    (REG_SYMPHONY_VBI_BASE + 0x08)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA1_REG    (REG_SYMPHONY_VBI_BASE + 0x0c)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA2_REG    (REG_SYMPHONY_VBI_BASE + 0x10)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA3_REG    (REG_SYMPHONY_VBI_BASE + 0x14)
#define  REG_ARIA_SD_ENC_VBI_VPS_DATA4_REG    (REG_SYMPHONY_VBI_BASE + 0x18)
#define  REG_ARIA_SD_ENC_VBI_WSS_DATA_REG   (REG_SYMPHONY_VBI_BASE + 0x1c)
#define  REG_ARIA_SD_ENC_VBI_FIFO_CNT    (REG_SYMPHONY_VBI_BASE + 0x30)
#define  REG_ARIA_SD_ENC_VBI_INT_MASK_N0    (REG_SYMPHONY_VBI_BASE + 0x34)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE_CLR0 (REG_SYMPHONY_VBI_BASE + 0x38)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE0     (REG_SYMPHONY_VBI_BASE + 0x3c)
#define  REG_ARIA_SD_ENC_VBI_CGMSA_DATA    (REG_SYMPHONY_VBI_BASE + 0x44)
#define  REG_ARIA_SD_ENC_VBI_INT_MASK_N1    (REG_SYMPHONY_VBI_BASE + 0x48)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE_CLR1 (REG_SYMPHONY_VBI_BASE + 0x4c)
#define  REG_ARIA_SD_ENC_VBI_INT_STATE1     (REG_SYMPHONY_VBI_BASE + 0x50)
#define  REG_ARIA_SD_ENC_VBI_FIFO_REG     (REG_SYMPHONY_VBI_BASE + 0x54)

#endif

#if defined(CONFIG_MT_CHIP_SYMPHONY2) || defined(CONFIG_MT_CHIP_SYMPHONY4) || defined(CONFIG_MT_CHIP_SYMPHONY6)  //sym6 need to add sym6 configure
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_CFG (REG_SYMPHONY_VBI_BASE + 0xA8)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N1_CS_FST_LIN_TOP (REG_SYMPHONY_VBI_BASE + 0x58)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N2_CS_SPC_1_2_TOP (REG_SYMPHONY_VBI_BASE + 0x5C)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N3_CS_FST_LN_BOT (REG_SYMPHONY_VBI_BASE + 0x60)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N4_CS_SPC_1_2_BOT (REG_SYMPHONY_VBI_BASE + 0x64)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N5_CS_SPC_ELSE (REG_SYMPHONY_VBI_BASE + 0x68)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N6_CS_NUM_IN_FIELD (REG_SYMPHONY_VBI_BASE + 0x6C)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N7_LN_NUM_IN_CS (REG_SYMPHONY_VBI_BASE + 0x70)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N8_PS_DURA (REG_SYMPHONY_VBI_BASE + 0x74)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N9_FST_PS_START (REG_SYMPHONY_VBI_BASE + 0x78)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N10_PS_SPC (REG_SYMPHONY_VBI_BASE + 0x7C)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N11_PS_AGC_LN_CHS (REG_SYMPHONY_VBI_BASE + 0x80)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N12_PS_AGC_FMT_CHS (REG_SYMPHONY_VBI_BASE + 0x84)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N13_PS_AGC_IVK_A (REG_SYMPHONY_VBI_BASE + 0x88)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N14_PS_AGC_IVK_B (REG_SYMPHONY_VBI_BASE + 0x8C)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N15_BP_LN_CHS (REG_SYMPHONY_VBI_BASE + 0x90)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N17_CS_ZONE1 (REG_SYMPHONY_VBI_BASE + 0x94)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N18_CS_ZONE2 (REG_SYMPHONY_VBI_BASE + 0x98)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N19_CS_ZONE3 (REG_SYMPHONY_VBI_BASE + 0x9C)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N20_CS_PHS_MDF (REG_SYMPHONY_VBI_BASE + 0xA0)
#define  REG_SYMPHONY_SD_ENCODER_VBI_MACV_N21_CS_PH_MDF_LN (REG_SYMPHONY_VBI_BASE + 0xA4)
#endif

#if defined(CONFIG_MT_CHIP_SYMPHONY4) || defined(CONFIG_MT_CHIP_SYMPHONY6)  //sym6 need to add sym6 configure
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA0   (REG_ARIA_SD_ENCODER_BASE + 0x400)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA1   (REG_ARIA_SD_ENCODER_BASE + 0x404)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA2   (REG_ARIA_SD_ENCODER_BASE + 0x408)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA3   (REG_ARIA_SD_ENCODER_BASE + 0x40c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA4   (REG_ARIA_SD_ENCODER_BASE + 0x410)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA5   (REG_ARIA_SD_ENCODER_BASE + 0x414)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA6   (REG_ARIA_SD_ENCODER_BASE + 0x418)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA7   (REG_ARIA_SD_ENCODER_BASE + 0x41c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA8   (REG_ARIA_SD_ENCODER_BASE + 0x420)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA9   (REG_ARIA_SD_ENCODER_BASE + 0x424)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA10   (REG_ARIA_SD_ENCODER_BASE + 0x428)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA11   (REG_ARIA_SD_ENCODER_BASE + 0x42c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA12   (REG_ARIA_SD_ENCODER_BASE + 0x430)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA13   (REG_ARIA_SD_ENCODER_BASE + 0x434)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA14   (REG_ARIA_SD_ENCODER_BASE + 0x438)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA15   (REG_ARIA_SD_ENCODER_BASE + 0x43c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA16   (REG_ARIA_SD_ENCODER_BASE + 0x440)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA17   (REG_ARIA_SD_ENCODER_BASE + 0x444)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA18   (REG_ARIA_SD_ENCODER_BASE + 0x448)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA19   (REG_ARIA_SD_ENCODER_BASE + 0x44c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA20   (REG_ARIA_SD_ENCODER_BASE + 0x450)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA21   (REG_ARIA_SD_ENCODER_BASE + 0x454)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA22   (REG_ARIA_SD_ENCODER_BASE + 0x458)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA23   (REG_ARIA_SD_ENCODER_BASE + 0x45c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA24   (REG_ARIA_SD_ENCODER_BASE + 0x460)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA25   (REG_ARIA_SD_ENCODER_BASE + 0x464)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA26   (REG_ARIA_SD_ENCODER_BASE + 0x468)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA27   (REG_ARIA_SD_ENCODER_BASE + 0x46c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA28   (REG_ARIA_SD_ENCODER_BASE + 0x470)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA29   (REG_ARIA_SD_ENCODER_BASE + 0x474)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA30   (REG_ARIA_SD_ENCODER_BASE + 0x478)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA31   (REG_ARIA_SD_ENCODER_BASE + 0x47c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA32   (REG_ARIA_SD_ENCODER_BASE + 0x480)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA33   (REG_ARIA_SD_ENCODER_BASE + 0x484)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA34   (REG_ARIA_SD_ENCODER_BASE + 0x488)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA35   (REG_ARIA_SD_ENCODER_BASE + 0x48c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA36   (REG_ARIA_SD_ENCODER_BASE + 0x490)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA37   (REG_ARIA_SD_ENCODER_BASE + 0x494)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA38   (REG_ARIA_SD_ENCODER_BASE + 0x498)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA39   (REG_ARIA_SD_ENCODER_BASE + 0x49c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA40   (REG_ARIA_SD_ENCODER_BASE + 0x4a0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA41   (REG_ARIA_SD_ENCODER_BASE + 0x4a4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA42   (REG_ARIA_SD_ENCODER_BASE + 0x4a8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA43   (REG_ARIA_SD_ENCODER_BASE + 0x4ac)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA44   (REG_ARIA_SD_ENCODER_BASE + 0x4b0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA45   (REG_ARIA_SD_ENCODER_BASE + 0x4b4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA46   (REG_ARIA_SD_ENCODER_BASE + 0x4b8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA47   (REG_ARIA_SD_ENCODER_BASE + 0x4bc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA48   (REG_ARIA_SD_ENCODER_BASE + 0x4c0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA49   (REG_ARIA_SD_ENCODER_BASE + 0x4c4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA50   (REG_ARIA_SD_ENCODER_BASE + 0x4c8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA51   (REG_ARIA_SD_ENCODER_BASE + 0x4cc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA52   (REG_ARIA_SD_ENCODER_BASE + 0x4d0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA53   (REG_ARIA_SD_ENCODER_BASE + 0x4d4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA54   (REG_ARIA_SD_ENCODER_BASE + 0x4d8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA55   (REG_ARIA_SD_ENCODER_BASE + 0x4dc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA56   (REG_ARIA_SD_ENCODER_BASE + 0x4e0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA57   (REG_ARIA_SD_ENCODER_BASE + 0x4e4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA58   (REG_ARIA_SD_ENCODER_BASE + 0x4e8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA59   (REG_ARIA_SD_ENCODER_BASE + 0x4ec)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA60   (REG_ARIA_SD_ENCODER_BASE + 0x4f0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA61   (REG_ARIA_SD_ENCODER_BASE + 0x4f4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA62   (REG_ARIA_SD_ENCODER_BASE + 0x4f8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA63   (REG_ARIA_SD_ENCODER_BASE + 0x4fc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA64   (REG_ARIA_SD_ENCODER_BASE + 0x500)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA65   (REG_ARIA_SD_ENCODER_BASE + 0x504)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA66   (REG_ARIA_SD_ENCODER_BASE + 0x508)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA67   (REG_ARIA_SD_ENCODER_BASE + 0x50c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA68   (REG_ARIA_SD_ENCODER_BASE + 0x510)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA69   (REG_ARIA_SD_ENCODER_BASE + 0x514)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA70   (REG_ARIA_SD_ENCODER_BASE + 0x518)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA71   (REG_ARIA_SD_ENCODER_BASE + 0x51c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA72   (REG_ARIA_SD_ENCODER_BASE + 0x520)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA73   (REG_ARIA_SD_ENCODER_BASE + 0x524)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA74   (REG_ARIA_SD_ENCODER_BASE + 0x528)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA75   (REG_ARIA_SD_ENCODER_BASE + 0x52c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA76   (REG_ARIA_SD_ENCODER_BASE + 0x530)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA77   (REG_ARIA_SD_ENCODER_BASE + 0x534)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA78   (REG_ARIA_SD_ENCODER_BASE + 0x538)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA79   (REG_ARIA_SD_ENCODER_BASE + 0x53c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA80   (REG_ARIA_SD_ENCODER_BASE + 0x540)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA81   (REG_ARIA_SD_ENCODER_BASE + 0x544)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA82   (REG_ARIA_SD_ENCODER_BASE + 0x548)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA83   (REG_ARIA_SD_ENCODER_BASE + 0x54c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA84   (REG_ARIA_SD_ENCODER_BASE + 0x550)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA85   (REG_ARIA_SD_ENCODER_BASE + 0x554)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA86   (REG_ARIA_SD_ENCODER_BASE + 0x558)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA87   (REG_ARIA_SD_ENCODER_BASE + 0x55c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA88   (REG_ARIA_SD_ENCODER_BASE + 0x560)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA89   (REG_ARIA_SD_ENCODER_BASE + 0x564)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA90   (REG_ARIA_SD_ENCODER_BASE + 0x568)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA91   (REG_ARIA_SD_ENCODER_BASE + 0x56c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA92   (REG_ARIA_SD_ENCODER_BASE + 0x570)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA93   (REG_ARIA_SD_ENCODER_BASE + 0x574)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA94   (REG_ARIA_SD_ENCODER_BASE + 0x578)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA95   (REG_ARIA_SD_ENCODER_BASE + 0x57c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA96   (REG_ARIA_SD_ENCODER_BASE + 0x580)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA97   (REG_ARIA_SD_ENCODER_BASE + 0x584)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA98   (REG_ARIA_SD_ENCODER_BASE + 0x588)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA99   (REG_ARIA_SD_ENCODER_BASE + 0x58c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA100   (REG_ARIA_SD_ENCODER_BASE + 0x590)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA101   (REG_ARIA_SD_ENCODER_BASE + 0x594)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA102   (REG_ARIA_SD_ENCODER_BASE + 0x598)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA103   (REG_ARIA_SD_ENCODER_BASE + 0x59c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA104   (REG_ARIA_SD_ENCODER_BASE + 0x5a0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA105   (REG_ARIA_SD_ENCODER_BASE + 0x5a4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA106   (REG_ARIA_SD_ENCODER_BASE + 0x5a8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA107   (REG_ARIA_SD_ENCODER_BASE + 0x5ac)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA108   (REG_ARIA_SD_ENCODER_BASE + 0x5b0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA109   (REG_ARIA_SD_ENCODER_BASE + 0x5b4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA110   (REG_ARIA_SD_ENCODER_BASE + 0x5b8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA111   (REG_ARIA_SD_ENCODER_BASE + 0x5bc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA112   (REG_ARIA_SD_ENCODER_BASE + 0x5c0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA113   (REG_ARIA_SD_ENCODER_BASE + 0x5c4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA114   (REG_ARIA_SD_ENCODER_BASE + 0x5c8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA115   (REG_ARIA_SD_ENCODER_BASE + 0x5cc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA116   (REG_ARIA_SD_ENCODER_BASE + 0x5d0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA117   (REG_ARIA_SD_ENCODER_BASE + 0x5d4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA118   (REG_ARIA_SD_ENCODER_BASE + 0x5d8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA119   (REG_ARIA_SD_ENCODER_BASE + 0x5dc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA120   (REG_ARIA_SD_ENCODER_BASE + 0x5e0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA121   (REG_ARIA_SD_ENCODER_BASE + 0x5e4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA122   (REG_ARIA_SD_ENCODER_BASE + 0x5e8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA123   (REG_ARIA_SD_ENCODER_BASE + 0x5ec)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA124   (REG_ARIA_SD_ENCODER_BASE + 0x5f0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA125   (REG_ARIA_SD_ENCODER_BASE + 0x5f4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA126   (REG_ARIA_SD_ENCODER_BASE + 0x5f8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA127   (REG_ARIA_SD_ENCODER_BASE + 0x5fc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA128   (REG_ARIA_SD_ENCODER_BASE + 0x600)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA129   (REG_ARIA_SD_ENCODER_BASE + 0x604)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA130   (REG_ARIA_SD_ENCODER_BASE + 0x608)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA131   (REG_ARIA_SD_ENCODER_BASE + 0x60c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA132   (REG_ARIA_SD_ENCODER_BASE + 0x610)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA133   (REG_ARIA_SD_ENCODER_BASE + 0x614)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA134   (REG_ARIA_SD_ENCODER_BASE + 0x618)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA135   (REG_ARIA_SD_ENCODER_BASE + 0x61c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA136   (REG_ARIA_SD_ENCODER_BASE + 0x620)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA137   (REG_ARIA_SD_ENCODER_BASE + 0x624)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA138   (REG_ARIA_SD_ENCODER_BASE + 0x628)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA139   (REG_ARIA_SD_ENCODER_BASE + 0x62c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA140   (REG_ARIA_SD_ENCODER_BASE + 0x630)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA141   (REG_ARIA_SD_ENCODER_BASE + 0x634)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA142   (REG_ARIA_SD_ENCODER_BASE + 0x638)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA143   (REG_ARIA_SD_ENCODER_BASE + 0x63c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA144   (REG_ARIA_SD_ENCODER_BASE + 0x640)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA145   (REG_ARIA_SD_ENCODER_BASE + 0x644)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA146   (REG_ARIA_SD_ENCODER_BASE + 0x648)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA147   (REG_ARIA_SD_ENCODER_BASE + 0x64c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA148   (REG_ARIA_SD_ENCODER_BASE + 0x650)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA149   (REG_ARIA_SD_ENCODER_BASE + 0x654)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA150   (REG_ARIA_SD_ENCODER_BASE + 0x658)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA151   (REG_ARIA_SD_ENCODER_BASE + 0x65c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA152   (REG_ARIA_SD_ENCODER_BASE + 0x660)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA153   (REG_ARIA_SD_ENCODER_BASE + 0x664)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA154   (REG_ARIA_SD_ENCODER_BASE + 0x668)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA155   (REG_ARIA_SD_ENCODER_BASE + 0x66c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA156   (REG_ARIA_SD_ENCODER_BASE + 0x670)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA157   (REG_ARIA_SD_ENCODER_BASE + 0x674)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA158   (REG_ARIA_SD_ENCODER_BASE + 0x678)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA159   (REG_ARIA_SD_ENCODER_BASE + 0x67c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA160   (REG_ARIA_SD_ENCODER_BASE + 0x680)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA161   (REG_ARIA_SD_ENCODER_BASE + 0x684)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA162   (REG_ARIA_SD_ENCODER_BASE + 0x688)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA163   (REG_ARIA_SD_ENCODER_BASE + 0x68c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA164   (REG_ARIA_SD_ENCODER_BASE + 0x690)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA165   (REG_ARIA_SD_ENCODER_BASE + 0x694)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA166   (REG_ARIA_SD_ENCODER_BASE + 0x698)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA167   (REG_ARIA_SD_ENCODER_BASE + 0x69c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA168   (REG_ARIA_SD_ENCODER_BASE + 0x6a0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA169   (REG_ARIA_SD_ENCODER_BASE + 0x6a4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA170   (REG_ARIA_SD_ENCODER_BASE + 0x6a8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA171   (REG_ARIA_SD_ENCODER_BASE + 0x6ac)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA172   (REG_ARIA_SD_ENCODER_BASE + 0x6b0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA173   (REG_ARIA_SD_ENCODER_BASE + 0x6b4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA174   (REG_ARIA_SD_ENCODER_BASE + 0x6b8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA175   (REG_ARIA_SD_ENCODER_BASE + 0x6bc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA176   (REG_ARIA_SD_ENCODER_BASE + 0x6c0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA177   (REG_ARIA_SD_ENCODER_BASE + 0x6c4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA178   (REG_ARIA_SD_ENCODER_BASE + 0x6c8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA179   (REG_ARIA_SD_ENCODER_BASE + 0x6cc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA180   (REG_ARIA_SD_ENCODER_BASE + 0x6d0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA181   (REG_ARIA_SD_ENCODER_BASE + 0x6d4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA182   (REG_ARIA_SD_ENCODER_BASE + 0x6d8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA183   (REG_ARIA_SD_ENCODER_BASE + 0x6dc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA184   (REG_ARIA_SD_ENCODER_BASE + 0x6e0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA185   (REG_ARIA_SD_ENCODER_BASE + 0x6e4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA186   (REG_ARIA_SD_ENCODER_BASE + 0x6e8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA187   (REG_ARIA_SD_ENCODER_BASE + 0x6ec)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA188   (REG_ARIA_SD_ENCODER_BASE + 0x6f0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA189   (REG_ARIA_SD_ENCODER_BASE + 0x6f4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA190   (REG_ARIA_SD_ENCODER_BASE + 0x6f8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA191   (REG_ARIA_SD_ENCODER_BASE + 0x6fc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA192   (REG_ARIA_SD_ENCODER_BASE + 0x700)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA193   (REG_ARIA_SD_ENCODER_BASE + 0x704)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA194   (REG_ARIA_SD_ENCODER_BASE + 0x708)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA195   (REG_ARIA_SD_ENCODER_BASE + 0x70c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA196   (REG_ARIA_SD_ENCODER_BASE + 0x710)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA197   (REG_ARIA_SD_ENCODER_BASE + 0x714)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA198   (REG_ARIA_SD_ENCODER_BASE + 0x718)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA199   (REG_ARIA_SD_ENCODER_BASE + 0x71c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA200   (REG_ARIA_SD_ENCODER_BASE + 0x720)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA201   (REG_ARIA_SD_ENCODER_BASE + 0x724)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA202   (REG_ARIA_SD_ENCODER_BASE + 0x728)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA203   (REG_ARIA_SD_ENCODER_BASE + 0x72c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA204   (REG_ARIA_SD_ENCODER_BASE + 0x730)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA205   (REG_ARIA_SD_ENCODER_BASE + 0x734)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA206   (REG_ARIA_SD_ENCODER_BASE + 0x738)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA207   (REG_ARIA_SD_ENCODER_BASE + 0x73c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA208   (REG_ARIA_SD_ENCODER_BASE + 0x740)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA209   (REG_ARIA_SD_ENCODER_BASE + 0x744)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA210   (REG_ARIA_SD_ENCODER_BASE + 0x748)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA211   (REG_ARIA_SD_ENCODER_BASE + 0x74c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA212   (REG_ARIA_SD_ENCODER_BASE + 0x750)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA213   (REG_ARIA_SD_ENCODER_BASE + 0x754)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA214   (REG_ARIA_SD_ENCODER_BASE + 0x758)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA215   (REG_ARIA_SD_ENCODER_BASE + 0x75c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA216   (REG_ARIA_SD_ENCODER_BASE + 0x760)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA217   (REG_ARIA_SD_ENCODER_BASE + 0x764)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA218   (REG_ARIA_SD_ENCODER_BASE + 0x768)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA219   (REG_ARIA_SD_ENCODER_BASE + 0x76c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA220   (REG_ARIA_SD_ENCODER_BASE + 0x770)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA221   (REG_ARIA_SD_ENCODER_BASE + 0x774)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA222   (REG_ARIA_SD_ENCODER_BASE + 0x778)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA223   (REG_ARIA_SD_ENCODER_BASE + 0x77c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA224   (REG_ARIA_SD_ENCODER_BASE + 0x780)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA225   (REG_ARIA_SD_ENCODER_BASE + 0x784)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA226   (REG_ARIA_SD_ENCODER_BASE + 0x788)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA227   (REG_ARIA_SD_ENCODER_BASE + 0x78c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA228   (REG_ARIA_SD_ENCODER_BASE + 0x790)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA229   (REG_ARIA_SD_ENCODER_BASE + 0x794)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA230   (REG_ARIA_SD_ENCODER_BASE + 0x798)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA231   (REG_ARIA_SD_ENCODER_BASE + 0x79c)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA232   (REG_ARIA_SD_ENCODER_BASE + 0x7a0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA233   (REG_ARIA_SD_ENCODER_BASE + 0x7a4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA234   (REG_ARIA_SD_ENCODER_BASE + 0x7a8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA235   (REG_ARIA_SD_ENCODER_BASE + 0x7ac)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA236   (REG_ARIA_SD_ENCODER_BASE + 0x7b0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA237   (REG_ARIA_SD_ENCODER_BASE + 0x7b4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA238   (REG_ARIA_SD_ENCODER_BASE + 0x7b8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA239   (REG_ARIA_SD_ENCODER_BASE + 0x7bc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA240   (REG_ARIA_SD_ENCODER_BASE + 0x7c0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA241   (REG_ARIA_SD_ENCODER_BASE + 0x7c4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA242   (REG_ARIA_SD_ENCODER_BASE + 0x7c8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA243   (REG_ARIA_SD_ENCODER_BASE + 0x7cc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA244   (REG_ARIA_SD_ENCODER_BASE + 0x7d0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA245   (REG_ARIA_SD_ENCODER_BASE + 0x7d4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA246   (REG_ARIA_SD_ENCODER_BASE + 0x7d8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA247   (REG_ARIA_SD_ENCODER_BASE + 0x7dc)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA248   (REG_ARIA_SD_ENCODER_BASE + 0x7e0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA249   (REG_ARIA_SD_ENCODER_BASE + 0x7e4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA250   (REG_ARIA_SD_ENCODER_BASE + 0x7e8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA251   (REG_ARIA_SD_ENCODER_BASE + 0x7ec)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA252   (REG_ARIA_SD_ENCODER_BASE + 0x7f0)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA253   (REG_ARIA_SD_ENCODER_BASE + 0x7f4)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA254   (REG_ARIA_SD_ENCODER_BASE + 0x7f8)
#define  REG_SYMPHONY_SD_ENCODER_VID_RAM_DATA255   (REG_ARIA_SD_ENCODER_BASE + 0x7fc)

#endif


#define VBI_EN_BIT          (1<<0)
#define CGMSA_EN_BIT        (1<<12)
#define TTTEX_EN_BIT        (1<<16)
#define TTTEX_DEC_EN_BIT    (1<<17)
#define CC_EN_BIT           (3<<20)
#define CC_DEC_EN_BIT       (1<<22)
#define VPS_EN_BIT          (1<<24)
#define WSS_EN_BIT          (1<<28)

/*!
  the union of register reg_aria_sd_enc_sd_enc_mode
  */
typedef union reg_aria_sd_enc_sd_enc_mode
{
    mt_u32 all;
    struct
    {
        mt_u32 vid_mode            : 2;
        mt_u32                             : 2;
        mt_u32 colorbar_sel        : 1;
        mt_u32                             : 3;
        mt_u32 sync_switch        : 2;
        mt_u32                             : 2;
        mt_u32 vid_test_mode    : 2;
        mt_u32                             : 2;
        mt_u32 dac_test_en        : 1;
        mt_u32                             : 3;
        mt_u32 dac0_sync_en     : 1;
        mt_u32                             : 3;
        mt_u32 cable_detect_en : 1;
        mt_u32                             : 3;
        mt_u32 vid_insert_mask_en  : 1;
        mt_u32                             : 3;
    } bitc;
} reg_aria_sd_enc_sd_enc_mode_t;

/*!
  the union of register reg_aria_sd_enc_sd_enc_curve
  */
typedef union reg_aria_sd_enc_sd_enc_curve
{
    mt_u32 all;
    struct
    {
        mt_u32 trap_en                   : 1;
        mt_u32 trap_sel                  : 1;
        mt_u32                                 : 2;
        mt_u32 chrom_filter_sel     : 1;
        mt_u32                                 : 3;
        mt_u32 black_strength_en  : 1;
        mt_u32                                  : 3;
        mt_u32 over_sample_mode : 1;
        mt_u32                                  : 3;
        mt_u32 gamma_amp            : 7;
        mt_u32                                  :1;
        mt_u32 gamma_pole            :1;
        mt_u32 gamma_en               :1;
        mt_u32                                  :6;
    } bitc;
} reg_aria_sd_enc_sd_enc_curve_t;

/*!
  the union of register reg_aria_sd_enc_sd_enc_cfg6
  */
typedef union reg_aria_sd_enc_sd_enc_cfg6
{
    mt_u32 all;
    struct
    {
        mt_u32 video_fmt                   : 3;
        mt_u32                             : 1;
        mt_u32 burst_lmt_en                   : 1;
        mt_u32                             : 3;
        mt_u32 os_bypass                   : 1;
        mt_u32                             : 7;
        mt_u32 dac_chan_sel                   : 8;
        mt_u32                             : 8;
    } bitc;
} reg_aria_sd_enc_sd_enc_cfg6_t;

/*!
  the union of register reg_aria_sd_enc_sd_enc_dacnum
  */
typedef union reg_aria_sd_enc_sd_enc_dacnum
{
    mt_u32 all;
    struct
    {
        mt_u32 soft_set               : 1;
        mt_u32                             : 7;
        mt_u32 dac_switch_en    : 1;
        mt_u32                             : 7;
        mt_u32 ypbpr_same_st   : 2;
        mt_u32                             : 14;
    } bitc;
} reg_aria_sd_enc_sd_enc_dacnum_t;


typedef struct
{
    volatile reg_aria_sd_enc_sd_enc_mode_t      sd_enc_mode    ; /* 0x0 */
    volatile reg_aria_sd_enc_sd_enc_curve_t       sd_enc_curve    ; /* 0x4 */
    volatile mt_u32               sd_enc_delay    ; /* 0x8 */
    volatile mt_u32               sd_enc_blank[3]    ; /* 0xc-0x14 */
    volatile mt_u32               sd_enc_dac_array[2]    ; /* 0x18-0x1c */
    volatile mt_u32               sd_enc_cfg[5]    ; /* 0x20-0x30 */
    volatile reg_aria_sd_enc_sd_enc_cfg6_t  sd_enc_cfg6    ; /* 0x34 */
    volatile mt_u32               sd_enc_cfg7    ; /* 0x38 */
    volatile mt_u32               sd_enc_set    ; /* 0x3c */
    volatile mt_u32               sd_enc_dac0_para    ; /* 0x40 */
    volatile mt_u32               sd_enc_secam[5]    ; /* 0x44-0x54 */
    volatile mt_u32               sd_enc_pal_increment    ; /* 0x58 */
    volatile mt_u32               sd_enc_ntsc_increment    ; /* 0x5c */
    volatile mt_u32               sd_enc_gctrl   ; /* 0x60 */
    volatile reg_aria_sd_enc_sd_enc_dacnum_t  sd_enc_dacnum   ; /* 0x64 */
    volatile mt_u32               sd_enc_insert_time   ; /* 0x68 */
    volatile mt_u32               sd_enc_compress   ; /* 0x6c */
    volatile mt_u32               sd_enc_set_ypbpr[4]   ; /* 0x70-0x7c */
    volatile mt_u32               sd_enc_coef_filt[12] ; /* 0x80-0xac */
    volatile mt_u32               sd_enc_coef_lut[12]   ; /* 0xb0-0xdc */
    volatile mt_u32               sd_enc_sign_ctrl   ; /* 0xe0*/
    volatile mt_u32               sd_enc_dac_offset   ; /* 0xe4*/
    volatile mt_u32               sd_enc_dac_para   ; /* 0xe8 */
    volatile mt_u32               sd_enc_reserv1   ; /* 0xec*/
    volatile mt_u32               sd_enc_dac_antisinc_coef[4]   ; /* 0xf0-0xfc */
}aria_regs_sdenc_t;



/*!
  the union of register reg_symphony_sd_encoder_mode
  */
typedef union reg_symphony_sd_encoder_mode
{
    mt_u32 all;
    struct
    {
        mt_u32 vid_mode                    : 2;
        mt_u32                             : 2;
        mt_u32 colorbar_sel                : 1;
        mt_u32                             : 3;
        mt_u32 sync_switch                 : 2;
        mt_u32                             : 2;
        mt_u32 vid_test_mode               : 2;
        mt_u32                             : 2;
        mt_u32 dac_test_en                 : 1;
        mt_u32                             : 3;
        mt_u32 dac0_sync_en                : 1;
        mt_u32                             : 3;
        mt_u32 cable_detect_en             : 1;
        mt_u32                             : 3;
        mt_u32 vid_insert_mask_en          : 1;
        mt_u32                             : 3;
    } bitc;
} reg_symphony_sd_encoder_mode_t;

/*!
  the union of register reg_symphony_sd_encoder_curve
  */
typedef union reg_symphony_sd_encoder_curve
{
    mt_u32 all;
    struct
    {
        mt_u32 trap_en                     : 1;
        mt_u32 trap_sel                    : 1;
        mt_u32                             : 2;
        mt_u32 chrom_filter_sel            : 1;
        mt_u32                             : 7;
        mt_u32 over_sample_mode            : 1;
        mt_u32                             : 3;
        mt_u32 gamma_amp                   : 7;
        mt_u32                             : 1;
        mt_u32 gamma_pole                  : 1;
        mt_u32 gamma_en                    : 1;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_curve_t;

/*!
  the union of register reg_symphony_sd_encoder_delay
  */
typedef union reg_symphony_sd_encoder_delay
{
    mt_u32 all;
    struct
    {
        mt_u32 y_sync                      : 8;
        mt_u32 cvbs_delay_n                : 8;
        mt_u32 cvbs_delay_p                : 8;
        mt_u32 cvbs_lum_delay              : 5;
        mt_u32                             : 3;
    } bitc;
} reg_symphony_sd_encoder_delay_t;

/*!
  the union of register reg_symphony_sd_encoder_blank_p
  */
typedef union reg_symphony_sd_encoder_blank_p
{
    mt_u32 all;
    struct
    {
        mt_u32 y_blank_p                   : 10;
        mt_u32                             : 6;
        mt_u32 y_black_p                   : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_blank_p_t;

/*!
  the union of register reg_symphony_sd_encoder_blank_n
  */
typedef union reg_symphony_sd_encoder_blank_n
{
    mt_u32 all;
    struct
    {
        mt_u32 y_blank_n                   : 10;
        mt_u32                             : 6;
        mt_u32 y_black_n                   : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_blank_n_t;

/*!
  the union of register reg_symphony_sd_encoder_cblank
  */
typedef union reg_symphony_sd_encoder_cblank
{
    mt_u32 all;
    struct
    {
        mt_u32 c_sync                      : 10;
        mt_u32                             : 6;
        mt_u32 c_blank                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_cblank_t;

/*!
  the union of register reg_symphony_sd_encoder_vdac_pcarry
  */
typedef union reg_symphony_sd_encoder_vdac_pcarry
{
    mt_u32 all;
    struct
    {
        mt_u32 subcarrier_p                : 32;
    } bitc;
} reg_symphony_sd_encoder_vdac_pcarry_t;

/*!
  the union of register reg_symphony_sd_encoder_vdac_ncarry
  */
typedef union reg_symphony_sd_encoder_vdac_ncarry
{
    mt_u32 all;
    struct
    {
        mt_u32 subcarrier_n                : 32;
    } bitc;
} reg_symphony_sd_encoder_vdac_ncarry_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig1
  */
typedef union reg_symphony_sd_encoder_cfig1
{
    mt_u32 all;
    struct
    {
        mt_u32 bluecoef_p                  : 9;
        mt_u32                             : 7;
        mt_u32 redcoef_p                   : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_cfig1_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig2
  */
typedef union reg_symphony_sd_encoder_cfig2
{
    mt_u32 all;
    struct
    {
        mt_u32 lumcoef_p                   : 9;
        mt_u32                             : 7;
        mt_u32 burstcoef_p                 : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_cfig2_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig3
  */
typedef union reg_symphony_sd_encoder_cfig3
{
    mt_u32 all;
    struct
    {
        mt_u32 bluecoef_n                  : 9;
        mt_u32                             : 7;
        mt_u32 redcoef_n                   : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_cfig3_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig4
  */
typedef union reg_symphony_sd_encoder_cfig4
{
    mt_u32 all;
    struct
    {
        mt_u32 lumcoef_n                   : 9;
        mt_u32                             : 7;
        mt_u32 burstcoef_n                 : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_cfig4_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig5
  */
typedef union reg_symphony_sd_encoder_cfig5
{
    mt_u32 all;
    struct
    {
        mt_u32 white_black_cfg             : 2;
        mt_u32                             : 14;
        mt_u32 burst_rst_phase             : 11;
        mt_u32                             : 5;
    } bitc;
} reg_symphony_sd_encoder_cfig5_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig6
  */
typedef union reg_symphony_sd_encoder_cfig6
{
    mt_u32 all;
    struct
    {
        mt_u32 video_format                : 3;
        mt_u32                             : 1;
        mt_u32 burst_lmt_en                : 1;
        mt_u32                             : 3;
        mt_u32 os_bypass                   : 1;
        mt_u32                             : 7;
        mt_u32 dac_chal_sel                : 8;
        mt_u32                             : 8;
    } bitc;
} reg_symphony_sd_encoder_cfig6_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig7
  */
typedef union reg_symphony_sd_encoder_cfig7
{
    mt_u32 all;
    struct
    {
        mt_u32 bypass_filter               : 4;
        mt_u32 field_line                  : 10;
        mt_u32                             : 2;
        mt_u32 field_cnt                   : 6;
        mt_u32                             : 10;
    } bitc;
} reg_symphony_sd_encoder_cfig7_t;

/*!
  the union of register reg_symphony_sd_encoder_set
  */
typedef union reg_symphony_sd_encoder_set
{
    mt_u32 all;
    struct
    {
        mt_u32 burst_rstmode               : 2;
        mt_u32                             : 2;
        mt_u32 burst_phase_change          : 1;
        mt_u32                             : 11;
        mt_u32 ire_7p5_en                  : 1;
        mt_u32                             : 3;
        mt_u32 pal_seq_mode                : 1;
        mt_u32                             : 7;
        mt_u32 dac_test_mode               : 1;
        mt_u32                             : 3;
    } bitc;
} reg_symphony_sd_encoder_set_t;

/*!
  the union of register reg_symphony_sd_encoder_dac0_para
  */
typedef union reg_symphony_sd_encoder_dac0_para
{
    mt_u32 all;
    struct
    {
        mt_u32 df_coef_b                   : 11;
        mt_u32                             : 1;
        mt_u32 df_coef_a                   : 12;
        mt_u32 df_sign_b                   : 1;
        mt_u32                             : 3;
        mt_u32 df_en                       : 1;
        mt_u32                             : 3;
    } bitc;
} reg_symphony_sd_encoder_dac0_para_t;

/*!
  the union of register reg_symphony_sd_encoder_drcoef
  */
typedef union reg_symphony_sd_encoder_drcoef
{
    mt_u32 all;
    struct
    {
        mt_u32 df_coef                     : 18;
        mt_u32                             : 14;
    } bitc;
} reg_symphony_sd_encoder_drcoef_t;

/*!
  the union of register reg_symphony_sd_encoder_dbcoef
  */
typedef union reg_symphony_sd_encoder_dbcoef
{
    mt_u32 all;
    struct
    {
        mt_u32 db_coef                     : 18;
        mt_u32                             : 14;
    } bitc;
} reg_symphony_sd_encoder_dbcoef_t;

/*!
  the union of register reg_symphony_sd_encoder_cfig8
  */
typedef union reg_symphony_sd_encoder_cfig8
{
    mt_u32 all;
    struct
    {
        mt_u32 scm_camp_coef               : 9;
        mt_u32                             : 23;
    } bitc;
} reg_symphony_sd_encoder_cfig8_t;

/*!
  the union of register reg_symphony_sd_encoder_scarrydr
  */
typedef union reg_symphony_sd_encoder_scarrydr
{
    mt_u32 all;
    struct
    {
        mt_u32 mid_freqwdr                 : 32;
    } bitc;
} reg_symphony_sd_encoder_scarrydr_t;

/*!
  the union of register reg_symphony_sd_encoder_scarrydb
  */
typedef union reg_symphony_sd_encoder_scarrydb
{
    mt_u32 all;
    struct
    {
        mt_u32 mid_freqwdb                 : 32;
    } bitc;
} reg_symphony_sd_encoder_scarrydb_t;

/*!
  the union of register reg_symphony_sd_encoder_pincrement
  */
typedef union reg_symphony_sd_encoder_pincrement
{
    mt_u32 all;
    struct
    {
        mt_u32 phase_line_increment_p      : 32;
    } bitc;
} reg_symphony_sd_encoder_pincrement_t;

/*!
  the union of register reg_symphony_sd_encoder_nincrement
  */
typedef union reg_symphony_sd_encoder_nincrement
{
    mt_u32 all;
    struct
    {
        mt_u32 phase_line_increment_n      : 32;
    } bitc;
} reg_symphony_sd_encoder_nincrement_t;

/*!
  the union of register reg_symphony_sd_encoder_gcontrol
  */
typedef union reg_symphony_sd_encoder_gcontrol
{
    mt_u32 all;
    struct
    {
        mt_u32 gain_control_0              : 11;
        mt_u32                             : 5;
        mt_u32 gain_control_123            : 11;
        mt_u32                             : 1;
        mt_u32 gain_control_0_en           : 1;
        mt_u32 gain_control_1_en           : 1;
        mt_u32 gain_control_2_en           : 1;
        mt_u32 gain_control_3_en           : 1;
    } bitc;
} reg_symphony_sd_encoder_gcontrol_t;

/*!
  the union of register reg_symphony_sd_encoder_dacnum
  */
typedef union reg_symphony_sd_encoder_dacnum
{
    mt_u32 all;
    struct
    {
        mt_u32 soft_set                    : 1;
        mt_u32                             : 7;
        mt_u32 dac_switch_en               : 1;
        mt_u32                             : 7;
        mt_u32 ypbpr_same_set              : 2;
        mt_u32                             : 14;
    } bitc;
} reg_symphony_sd_encoder_dacnum_t;

/*!
  the union of register reg_symphony_sd_encoder_instm
  */
typedef union reg_symphony_sd_encoder_instm
{
    mt_u32 all;
    struct
    {
        mt_u32 video_instm_p               : 10;
        mt_u32                             : 6;
        mt_u32 video_instm_n               : 10;
        mt_u32                             : 2;
        mt_u32 digital_time_en             : 1;
        mt_u32                             : 3;
    } bitc;
} reg_symphony_sd_encoder_instm_t;

/*!
  the union of register reg_symphony_sd_encoder_compress
  */
typedef union reg_symphony_sd_encoder_compress
{
    mt_u32 all;
    struct
    {
        mt_u32 cr_compress                 : 8;
        mt_u32 cb_compress                 : 8;
        mt_u32 y_compress                  : 8;
        mt_u32                             : 8;
    } bitc;
} reg_symphony_sd_encoder_compress_t;

/*!
  the union of register reg_symphony_sd_encoder_set1
  */
typedef union reg_symphony_sd_encoder_set1
{
    mt_u32 all;
    struct
    {
        mt_u32 cvbs_chrom_delay            : 4;
        mt_u32 ypp_chrom_delay             : 4;
        mt_u32                             : 24;
    } bitc;
} reg_symphony_sd_encoder_set1_t;

/*!
  the union of register reg_symphony_sd_encoder_set2
  */
typedef union reg_symphony_sd_encoder_set2
{
    mt_u32 all;
    struct
    {
        mt_u32 ypp_lum_delay               : 4;
        mt_u32                             : 4;
        mt_u32 y_sync_n                    : 8;
        mt_u32                             : 16;
    } bitc;
} reg_symphony_sd_encoder_set2_t;

/*!
  the union of register reg_symphony_sd_encoder_set3
  */
typedef union reg_symphony_sd_encoder_set3
{
    mt_u32 all;
    struct
    {
        mt_u32 video_end_num_p             : 11;
        mt_u32                             : 5;
        mt_u32 video_end_num_n             : 11;
        mt_u32                             : 5;
    } bitc;
} reg_symphony_sd_encoder_set3_t;

/*!
  the union of register reg_symphony_sd_encoder_lum_dly_108m
  */
typedef union reg_symphony_sd_encoder_lum_dly_108m
{
    mt_u32 all;
    struct
    {
        mt_u32 cvbs_lum_delay_108m         : 2;
        mt_u32                             : 2;
        mt_u32 ypp_lum_delay_108m          : 2;
        mt_u32                             : 2;
        mt_u32 vid_mask_begin_cnt          : 7;
        mt_u32                             : 1;
        mt_u32 vid_mask_end_cnt            : 7;
        mt_u32                             : 1;
        mt_u32 vid_mask_en                 : 1;
        mt_u32                             : 3;
        mt_u32 first_line_later            : 4;
    } bitc;
} reg_symphony_sd_encoder_lum_dly_108m_t;

/*!
  the union of register reg_symphony_sd_encoder_coef11
  */
typedef union reg_symphony_sd_encoder_coef11
{
    mt_u32 all;
    struct
    {
        mt_u32 coef11                      : 10;
        mt_u32                             : 6;
        mt_u32 coef11_y                    : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef11_t;

/*!
  the union of register reg_symphony_sd_encoder_coef10
  */
typedef union reg_symphony_sd_encoder_coef10
{
    mt_u32 all;
    struct
    {
        mt_u32 coef10                      : 10;
        mt_u32                             : 6;
        mt_u32 coef10_y                    : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef10_t;

/*!
  the union of register reg_symphony_sd_encoder_coef9
  */
typedef union reg_symphony_sd_encoder_coef9
{
    mt_u32 all;
    struct
    {
        mt_u32 coef9                       : 10;
        mt_u32                             : 6;
        mt_u32 coef9_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef9_t;

/*!
  the union of register reg_symphony_sd_encoder_coef8
  */
typedef union reg_symphony_sd_encoder_coef8
{
    mt_u32 all;
    struct
    {
        mt_u32 coef8                       : 10;
        mt_u32                             : 6;
        mt_u32 coef8_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef8_t;

/*!
  the union of register reg_symphony_sd_encoder_coef7
  */
typedef union reg_symphony_sd_encoder_coef7
{
    mt_u32 all;
    struct
    {
        mt_u32 coef7                       : 10;
        mt_u32                             : 6;
        mt_u32 coef7_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef7_t;

/*!
  the union of register reg_symphony_sd_encoder_coef6
  */
typedef union reg_symphony_sd_encoder_coef6
{
    mt_u32 all;
    struct
    {
        mt_u32 coef6                       : 10;
        mt_u32                             : 6;
        mt_u32 coef6_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef6_t;

/*!
  the union of register reg_symphony_sd_encoder_coef5
  */
typedef union reg_symphony_sd_encoder_coef5
{
    mt_u32 all;
    struct
    {
        mt_u32 coef5                       : 10;
        mt_u32                             : 6;
        mt_u32 coef5_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef5_t;

/*!
  the union of register reg_symphony_sd_encoder_coef4
  */
typedef union reg_symphony_sd_encoder_coef4
{
    mt_u32 all;
    struct
    {
        mt_u32 coef4                       : 10;
        mt_u32                             : 6;
        mt_u32 coef4_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef4_t;

/*!
  the union of register reg_symphony_sd_encoder_coef3
  */
typedef union reg_symphony_sd_encoder_coef3
{
    mt_u32 all;
    struct
    {
        mt_u32 coef3                       : 10;
        mt_u32                             : 6;
        mt_u32 coef3_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef3_t;

/*!
  the union of register reg_symphony_sd_encoder_coef2
  */
typedef union reg_symphony_sd_encoder_coef2
{
    mt_u32 all;
    struct
    {
        mt_u32 coef2                       : 10;
        mt_u32                             : 6;
        mt_u32 coef2_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef2_t;

/*!
  the union of register reg_symphony_sd_encoder_coef1
  */
typedef union reg_symphony_sd_encoder_coef1
{
    mt_u32 all;
    struct
    {
        mt_u32 coef1                       : 10;
        mt_u32                             : 6;
        mt_u32 coef1_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef1_t;

/*!
  the union of register reg_symphony_sd_encoder_coef0
  */
typedef union reg_symphony_sd_encoder_coef0
{
    mt_u32 all;
    struct
    {
        mt_u32 coef0                       : 10;
        mt_u32                             : 6;
        mt_u32 coef0_y                     : 10;
        mt_u32                             : 6;
    } bitc;
} reg_symphony_sd_encoder_coef0_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut3_u
  */
typedef union reg_symphony_sd_encoder_coef_c_lut3_u
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut3_u               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut3_u_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut2_u
  */
typedef union reg_symphony_sd_encoder_coef_c_lut2_u
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut2_u               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut2_u_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut1_u
  */
typedef union reg_symphony_sd_encoder_coef_c_lut1_u
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut1_u               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut1_u_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut0_u
  */
typedef union reg_symphony_sd_encoder_coef_c_lut0_u
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut0_u               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut0_u_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut3_v
  */
typedef union reg_symphony_sd_encoder_coef_c_lut3_v
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut3_v               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut3_v_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut2_v
  */
typedef union reg_symphony_sd_encoder_coef_c_lut2_v
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut2_v               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut2_v_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut1_v
  */
typedef union reg_symphony_sd_encoder_coef_c_lut1_v
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut1_v               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut1_v_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_c_lut0_v
  */
typedef union reg_symphony_sd_encoder_coef_c_lut0_v
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_c_lut0_v               : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_c_lut0_v_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_lut3_y
  */
typedef union reg_symphony_sd_encoder_coef_lut3_y
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_lut3_y                 : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_lut3_y_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_lut2_y
  */
typedef union reg_symphony_sd_encoder_coef_lut2_y
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_lut2_y                 : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_lut2_y_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_lut1_y
  */
typedef union reg_symphony_sd_encoder_coef_lut1_y
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_lut1_y                 : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_lut1_y_t;

/*!
  the union of register reg_symphony_sd_encoder_coef_lut0_y
  */
typedef union reg_symphony_sd_encoder_coef_lut0_y
{
    mt_u32 all;
    struct
    {
        mt_u32 coef_lut0_y                 : 32;
    } bitc;
} reg_symphony_sd_encoder_coef_lut0_y_t;

/*!
  the union of register reg_symphony_sd_encoder_sign_ctl
  */
typedef union reg_symphony_sd_encoder_sign_ctl
{
    mt_u32 all;
    struct
    {
        mt_u32 sign_ctl                    : 13;
        mt_u32                             : 19;
    } bitc;
} reg_symphony_sd_encoder_sign_ctl_t;

/*!
  the union of register reg_symphony_sd_encoder_dac_offset
  */
typedef union reg_symphony_sd_encoder_dac_offset
{
    mt_u32 all;
    struct
    {
        mt_u32 dac0_offset                 : 8;
        mt_u32 field1_other_vbi_first      : 4;
        mt_u32 field2_other_vbi_first      : 4;
        mt_u32                             : 3;
        mt_u32 vbi_priority_mode           : 1;
        mt_u32                             : 12;
    } bitc;
} reg_symphony_sd_encoder_dac_offset_t;

/*!
  the union of register reg_symphony_sd_encoder_dac123_para
  */
typedef union reg_symphony_sd_encoder_dac123_para
{
    mt_u32 all;
    struct
    {
        mt_u32 df_coef_b                   : 11;
        mt_u32                             : 1;
        mt_u32 df_coef_a                   : 12;
        mt_u32 df_sign_b                   : 1;
        mt_u32                             : 3;
        mt_u32 df_en_1                     : 1;
        mt_u32 df_en_2                     : 1;
        mt_u32 df_en_3                     : 1;
        mt_u32                             : 1;
    } bitc;
} reg_symphony_sd_encoder_dac123_para_t;

/*!
  the union of register reg_symphony_sd_encoder_dac0_anti_coef1_0
  */
typedef union reg_symphony_sd_encoder_dac0_anti_coef1_0
{
    mt_u32 all;
    struct
    {
        mt_u32 dac0_anti_coef0             : 9;
        mt_u32                             : 7;
        mt_u32 dac0_anti_coef1             : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_dac0_anti_coef1_0_t;

/*!
  the union of register reg_symphony_sd_encoder_dac0_anti_coef3_2
  */
typedef union reg_symphony_sd_encoder_dac0_anti_coef3_2
{
    mt_u32 all;
    struct
    {
        mt_u32 dac0_anti_coef2             : 9;
        mt_u32                             : 7;
        mt_u32 dac0_anti_coef3             : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_dac0_anti_coef3_2_t;

/*!
  the union of register reg_symphony_sd_encoder_dac123_anti_coef1_0
  */
typedef union reg_symphony_sd_encoder_dac123_anti_coef1_0
{
    mt_u32 all;
    struct
    {
        mt_u32 dac123_anti_coef0           : 9;
        mt_u32                             : 7;
        mt_u32 dac123_anti_coef1           : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_dac123_anti_coef1_0_t;

/*!
  the union of register reg_symphony_sd_encoder_dac123_anti_coef3_2
  */
typedef union reg_symphony_sd_encoder_dac123_anti_coef3_2
{
    mt_u32 all;
    struct
    {
        mt_u32 dac123_anti_coef2           : 9;
        mt_u32                             : 7;
        mt_u32 dac123_anti_coef3           : 9;
        mt_u32                             : 7;
    } bitc;
} reg_symphony_sd_encoder_dac123_anti_coef3_2_t;

#ifdef __cplusplus
extern "C" {
#endif

/*!
  register REGARIA_SD_ENC_SD_ENC_MODE (read/write)
  */
void reg_aria_sd_enc_set_sd_enc_mode(mt_u32 data);
/*!
  comments
  */
mt_u32  reg_aria_sd_enc_get_sd_enc_mode(void);
/*!
  comments
  */
void reg_aria_sd_enc_set_sd_enc_mode_vid_mode(mt_u8 data);
/*!
  comments
  */
mt_u8   reg_aria_sd_enc_get_sd_enc_mode_vid_mode(void);

/*!
  register REGARIA_SD_ENC_SD_ENC_CFG6 (read/write)
  */
void reg_aria_sd_enc_set_cfg6(mt_u32 data);
/*!
  comments
  */
mt_u32  reg_aria_sd_enc_get_cfg6(void);
/*!
  comments
  */
void reg_aria_sd_enc_set_cfg6_video_fmt(mt_u8 data);
/*!
  comments
  */
mt_u8   reg_aria_sd_enc_get_cfg6_video_fmt(void);

/*!
  register REGARIA_SD_ENC_SD_ENC_DACNUM (read/write)
  */
void reg_aria_sd_enc_set_sd_enc_dacnum(mt_u32 data);
/*!
  comments
  */
mt_u32  reg_aria_sd_enc_get_sd_enc_dacnum(void);
/*!
  comments
  */
void reg_aria_sd_enc_set_sd_enc_dacnum_dac_switch(mt_u8 data);
/*!
  comments
  */
mt_u8   reg_aria_sd_enc_get_sd_enc_dacnum_dac_switch(void);

/*!
  ARIA_SD_ENC reg init function
  */
void reg_aria_sd_enc_init(void);

/*!
 comments
  */
void reg_aria_sd_encoder_set_gama_correction_gama_coef(mt_u8 data);
/*!
 comments
  */
void reg_aria_sd_encoder_set_gama_correction_gama_pole(mt_u8 data);
/*!
 comments
  */
void reg_aria_sd_encoder_set_gama_correction_gama_enable(mt_u8 data);

/*********************************************************************/
/*!
  register REGSYMPHONY_SD_ENCODER_MODE (read/write)
  */
void reg_symphony_sd_encoder_set_mode(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_mode(void);
void reg_symphony_sd_encoder_set_mode_vid_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_vid_mode(void);
void reg_symphony_sd_encoder_set_mode_colorbar_sel(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_colorbar_sel(void);
void reg_symphony_sd_encoder_set_mode_sync_switch(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_sync_switch(void);
void reg_symphony_sd_encoder_set_mode_vid_test_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_vid_test_mode(void);
void reg_symphony_sd_encoder_set_mode_dac_test_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_dac_test_en(void);
void reg_symphony_sd_encoder_set_mode_dac0_sync_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_dac0_sync_en(void);
void reg_symphony_sd_encoder_set_mode_cable_detect_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_cable_detect_en(void);
void reg_symphony_sd_encoder_set_mode_vid_insert_mask_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_mode_vid_insert_mask_en(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CURVE (read/write)
  */
void reg_symphony_sd_encoder_set_curve(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_curve(void);
void reg_symphony_sd_encoder_set_curve_trap_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_trap_en(void);
void reg_symphony_sd_encoder_set_curve_trap_sel(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_trap_sel(void);
void reg_symphony_sd_encoder_set_curve_chrom_filter_sel(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_chrom_filter_sel(void);
void reg_symphony_sd_encoder_set_curve_over_sample_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_over_sample_mode(void);
void reg_symphony_sd_encoder_set_curve_gamma_amp(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_gamma_amp(void);
void reg_symphony_sd_encoder_set_curve_gamma_pole(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_gamma_pole(void);
void reg_symphony_sd_encoder_set_curve_gamma_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_curve_gamma_en(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DELAY (read/write)
  */
void reg_symphony_sd_encoder_set_delay(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_delay(void);
void reg_symphony_sd_encoder_set_delay_y_sync(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_delay_y_sync(void);
void reg_symphony_sd_encoder_set_delay_cvbs_delay_n(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_delay_cvbs_delay_n(void);
void reg_symphony_sd_encoder_set_delay_cvbs_delay_p(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_delay_cvbs_delay_p(void);
void reg_symphony_sd_encoder_set_delay_cvbs_lum_delay(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_delay_cvbs_lum_delay(void);

/*!
  register REGSYMPHONY_SD_ENCODER_BLANK_P (read/write)
  */
void reg_symphony_sd_encoder_set_blank_p(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_blank_p(void);
void reg_symphony_sd_encoder_set_blank_p_y_blank_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_blank_p_y_blank_p(void);
void reg_symphony_sd_encoder_set_blank_p_y_black_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_blank_p_y_black_p(void);

/*!
  register REGSYMPHONY_SD_ENCODER_BLANK_N (read/write)
  */
void reg_symphony_sd_encoder_set_blank_n(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_blank_n(void);
void reg_symphony_sd_encoder_set_blank_n_y_blank_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_blank_n_y_blank_n(void);
void reg_symphony_sd_encoder_set_blank_n_y_black_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_blank_n_y_black_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CBLANK (read/write)
  */
void reg_symphony_sd_encoder_set_cblank(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cblank(void);
void reg_symphony_sd_encoder_set_cblank_c_sync(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cblank_c_sync(void);
void reg_symphony_sd_encoder_set_cblank_c_blank(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cblank_c_blank(void);

/*!
  register REGSYMPHONY_SD_ENCODER_VDAC_PCARRY (read/write)
  */
void reg_symphony_sd_encoder_set_vdac_pcarry(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_vdac_pcarry(void);
void reg_symphony_sd_encoder_set_vdac_pcarry_subcarrier_p(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_vdac_pcarry_subcarrier_p(void);

/*!
  register REGSYMPHONY_SD_ENCODER_VDAC_NCARRY (read/write)
  */
void reg_symphony_sd_encoder_set_vdac_ncarry(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_vdac_ncarry(void);
void reg_symphony_sd_encoder_set_vdac_ncarry_subcarrier_n(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_vdac_ncarry_subcarrier_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG1 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig1(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig1(void);
void reg_symphony_sd_encoder_set_cfig1_bluecoef_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig1_bluecoef_p(void);
void reg_symphony_sd_encoder_set_cfig1_redcoef_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig1_redcoef_p(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG2 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig2(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig2(void);
void reg_symphony_sd_encoder_set_cfig2_lumcoef_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig2_lumcoef_p(void);
void reg_symphony_sd_encoder_set_cfig2_burstcoef_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig2_burstcoef_p(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG3 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig3(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig3(void);
void reg_symphony_sd_encoder_set_cfig3_bluecoef_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig3_bluecoef_n(void);
void reg_symphony_sd_encoder_set_cfig3_redcoef_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig3_redcoef_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG4 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig4(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig4(void);
void reg_symphony_sd_encoder_set_cfig4_lumcoef_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig4_lumcoef_n(void);
void reg_symphony_sd_encoder_set_cfig4_burstcoef_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig4_burstcoef_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG5 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig5(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig5(void);
void reg_symphony_sd_encoder_set_cfig5_white_black_cfg(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig5_white_black_cfg(void);
void reg_symphony_sd_encoder_set_cfig5_burst_rst_phase(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig5_burst_rst_phase(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG6 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig6(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig6(void);
void reg_symphony_sd_encoder_set_cfig6_video_format(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig6_video_format(void);
void reg_symphony_sd_encoder_set_cfig6_burst_lmt_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig6_burst_lmt_en(void);
void reg_symphony_sd_encoder_set_cfig6_os_bypass(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig6_os_bypass(void);
void reg_symphony_sd_encoder_set_cfig6_dac_chal_sel(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig6_dac_chal_sel(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG7 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig7(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig7(void);
void reg_symphony_sd_encoder_set_cfig7_bypass_filter(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig7_bypass_filter(void);
void reg_symphony_sd_encoder_set_cfig7_field_line(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig7_field_line(void);
void reg_symphony_sd_encoder_set_cfig7_field_cnt(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_cfig7_field_cnt(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SET (read/write)
  */
void reg_symphony_sd_encoder_set_set(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_set(void);
void reg_symphony_sd_encoder_set_set_burst_rstmode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set_burst_rstmode(void);
void reg_symphony_sd_encoder_set_set_burst_phase_change(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set_burst_phase_change(void);
void reg_symphony_sd_encoder_set_set_ire_7p5_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set_ire_7p5_en(void);
void reg_symphony_sd_encoder_set_set_pal_seq_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set_pal_seq_mode(void);
void reg_symphony_sd_encoder_set_set_dac_test_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set_dac_test_mode(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC0_PARA (read/write)
  */
void reg_symphony_sd_encoder_set_dac0_para(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac0_para(void);
void reg_symphony_sd_encoder_set_dac0_para_df_coef_b(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_para_df_coef_b(void);
void reg_symphony_sd_encoder_set_dac0_para_df_coef_a(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_para_df_coef_a(void);
void reg_symphony_sd_encoder_set_dac0_para_df_sign_b(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac0_para_df_sign_b(void);
void reg_symphony_sd_encoder_set_dac0_para_df_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac0_para_df_en(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DRCOEF (read/write)
  */
void reg_symphony_sd_encoder_set_drcoef(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_drcoef(void);
void reg_symphony_sd_encoder_set_drcoef_df_coef(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_drcoef_df_coef(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DBCOEF (read/write)
  */
void reg_symphony_sd_encoder_set_dbcoef(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dbcoef(void);
void reg_symphony_sd_encoder_set_dbcoef_db_coef(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dbcoef_db_coef(void);

/*!
  register REGSYMPHONY_SD_ENCODER_CFIG8 (read/write)
  */
void reg_symphony_sd_encoder_set_cfig8(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_cfig8(void);
void reg_symphony_sd_encoder_set_cfig8_scm_camp_coef(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_cfig8_scm_camp_coef(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SCARRYDR (read/write)
  */
void reg_symphony_sd_encoder_set_scarrydr(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_scarrydr(void);
void reg_symphony_sd_encoder_set_scarrydr_mid_freqwdr(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_scarrydr_mid_freqwdr(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SCARRYDB (read/write)
  */
void reg_symphony_sd_encoder_set_scarrydb(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_scarrydb(void);
void reg_symphony_sd_encoder_set_scarrydb_mid_freqwdb(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_scarrydb_mid_freqwdb(void);

/*!
  register REGSYMPHONY_SD_ENCODER_PINCREMENT (read/write)
  */
void reg_symphony_sd_encoder_set_pincrement(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_pincrement(void);
void reg_symphony_sd_encoder_set_pincrement_phase_line_increment_p(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_pincrement_phase_line_increment_p(void);

/*!
  register REGSYMPHONY_SD_ENCODER_NINCREMENT (read/write)
  */
void reg_symphony_sd_encoder_set_nincrement(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_nincrement(void);
void reg_symphony_sd_encoder_set_nincrement_phase_line_increment_n(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_nincrement_phase_line_increment_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_GCONTROL (read/write)
  */
void reg_symphony_sd_encoder_set_gcontrol(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_gcontrol(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_0(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_gcontrol_gain_control_0(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_123(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_gcontrol_gain_control_123(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_0_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_gcontrol_gain_control_0_en(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_1_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_gcontrol_gain_control_1_en(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_2_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_gcontrol_gain_control_2_en(void);
void reg_symphony_sd_encoder_set_gcontrol_gain_control_3_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_gcontrol_gain_control_3_en(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DACNUM (read/write)
  */
void reg_symphony_sd_encoder_set_dacnum(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dacnum(void);
void reg_symphony_sd_encoder_set_dacnum_soft_set(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dacnum_soft_set(void);
void reg_symphony_sd_encoder_set_dacnum_dac_switch_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dacnum_dac_switch_en(void);
void reg_symphony_sd_encoder_set_dacnum_ypbpr_same_set(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dacnum_ypbpr_same_set(void);

/*!
  register REGSYMPHONY_SD_ENCODER_INSTM (read/write)
  */
void reg_symphony_sd_encoder_set_instm(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_instm(void);
void reg_symphony_sd_encoder_set_instm_video_instm_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_instm_video_instm_p(void);
void reg_symphony_sd_encoder_set_instm_video_instm_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_instm_video_instm_n(void);
void reg_symphony_sd_encoder_set_instm_digital_time_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_instm_digital_time_en(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COMPRESS (read/write)
  */
void reg_symphony_sd_encoder_set_compress(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_compress(void);
void reg_symphony_sd_encoder_set_compress_cr_compress(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_compress_cr_compress(void);
void reg_symphony_sd_encoder_set_compress_cb_compress(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_compress_cb_compress(void);
void reg_symphony_sd_encoder_set_compress_y_compress(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_compress_y_compress(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SET1 (read/write)
  */
void reg_symphony_sd_encoder_set_set1(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_set1(void);
void reg_symphony_sd_encoder_set_set1_cvbs_chrom_delay(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set1_cvbs_chrom_delay(void);
void reg_symphony_sd_encoder_set_set1_ypp_chrom_delay(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set1_ypp_chrom_delay(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SET2 (read/write)
  */
void reg_symphony_sd_encoder_set_set2(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_set2(void);
void reg_symphony_sd_encoder_set_set2_ypp_lum_delay(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set2_ypp_lum_delay(void);
void reg_symphony_sd_encoder_set_set2_y_sync_n(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_set2_y_sync_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SET3 (read/write)
  */
void reg_symphony_sd_encoder_set_set3(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_set3(void);
void reg_symphony_sd_encoder_set_set3_video_end_num_p(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_set3_video_end_num_p(void);
void reg_symphony_sd_encoder_set_set3_video_end_num_n(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_set3_video_end_num_n(void);

/*!
  register REGSYMPHONY_SD_ENCODER_LUM_DLY_108M (read/write)
  */
void reg_symphony_sd_encoder_set_lum_dly_108m(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_lum_dly_108m(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_cvbs_lum_delay_108m(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_cvbs_lum_delay_108m(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_ypp_lum_delay_108m(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_ypp_lum_delay_108m(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_vid_mask_begin_cnt(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_vid_mask_begin_cnt(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_vid_mask_end_cnt(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_vid_mask_end_cnt(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_vid_mask_en(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_vid_mask_en(void);
void reg_symphony_sd_encoder_set_lum_dly_108m_first_line_later(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_lum_dly_108m_first_line_later(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF11 (read/write)
  */
void reg_symphony_sd_encoder_set_coef11(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef11(void);
void reg_symphony_sd_encoder_set_coef11_coef11(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef11_coef11(void);
void reg_symphony_sd_encoder_set_coef11_coef11_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef11_coef11_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF10 (read/write)
  */
void reg_symphony_sd_encoder_set_coef10(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef10(void);
void reg_symphony_sd_encoder_set_coef10_coef10(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef10_coef10(void);
void reg_symphony_sd_encoder_set_coef10_coef10_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef10_coef10_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF9 (read/write)
  */
void reg_symphony_sd_encoder_set_coef9(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef9(void);
void reg_symphony_sd_encoder_set_coef9_coef9(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef9_coef9(void);
void reg_symphony_sd_encoder_set_coef9_coef9_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef9_coef9_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF8 (read/write)
  */
void reg_symphony_sd_encoder_set_coef8(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef8(void);
void reg_symphony_sd_encoder_set_coef8_coef8(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef8_coef8(void);
void reg_symphony_sd_encoder_set_coef8_coef8_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef8_coef8_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF7 (read/write)
  */
void reg_symphony_sd_encoder_set_coef7(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef7(void);
void reg_symphony_sd_encoder_set_coef7_coef7(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef7_coef7(void);
void reg_symphony_sd_encoder_set_coef7_coef7_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef7_coef7_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF6 (read/write)
  */
void reg_symphony_sd_encoder_set_coef6(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef6(void);
void reg_symphony_sd_encoder_set_coef6_coef6(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef6_coef6(void);
void reg_symphony_sd_encoder_set_coef6_coef6_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef6_coef6_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF5 (read/write)
  */
void reg_symphony_sd_encoder_set_coef5(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef5(void);
void reg_symphony_sd_encoder_set_coef5_coef5(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef5_coef5(void);
void reg_symphony_sd_encoder_set_coef5_coef5_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef5_coef5_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF4 (read/write)
  */
void reg_symphony_sd_encoder_set_coef4(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef4(void);
void reg_symphony_sd_encoder_set_coef4_coef4(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef4_coef4(void);
void reg_symphony_sd_encoder_set_coef4_coef4_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef4_coef4_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF3 (read/write)
  */
void reg_symphony_sd_encoder_set_coef3(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef3(void);
void reg_symphony_sd_encoder_set_coef3_coef3(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef3_coef3(void);
void reg_symphony_sd_encoder_set_coef3_coef3_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef3_coef3_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF2 (read/write)
  */
void reg_symphony_sd_encoder_set_coef2(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef2(void);
void reg_symphony_sd_encoder_set_coef2_coef2(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef2_coef2(void);
void reg_symphony_sd_encoder_set_coef2_coef2_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef2_coef2_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF1 (read/write)
  */
void reg_symphony_sd_encoder_set_coef1(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef1(void);
void reg_symphony_sd_encoder_set_coef1_coef1(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef1_coef1(void);
void reg_symphony_sd_encoder_set_coef1_coef1_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef1_coef1_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF0 (read/write)
  */
void reg_symphony_sd_encoder_set_coef0(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef0(void);
void reg_symphony_sd_encoder_set_coef0_coef0(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef0_coef0(void);
void reg_symphony_sd_encoder_set_coef0_coef0_y(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_coef0_coef0_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT3_U (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut3_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut3_u(void);
void reg_symphony_sd_encoder_set_coef_c_lut3_u_coef_c_lut3_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut3_u_coef_c_lut3_u(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT2_U (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut2_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut2_u(void);
void reg_symphony_sd_encoder_set_coef_c_lut2_u_coef_c_lut2_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut2_u_coef_c_lut2_u(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT1_U (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut1_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut1_u(void);
void reg_symphony_sd_encoder_set_coef_c_lut1_u_coef_c_lut1_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut1_u_coef_c_lut1_u(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT0_U (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut0_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut0_u(void);
void reg_symphony_sd_encoder_set_coef_c_lut0_u_coef_c_lut0_u(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut0_u_coef_c_lut0_u(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT3_V (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut3_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut3_v(void);
void reg_symphony_sd_encoder_set_coef_c_lut3_v_coef_c_lut3_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut3_v_coef_c_lut3_v(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT2_V (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut2_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut2_v(void);
void reg_symphony_sd_encoder_set_coef_c_lut2_v_coef_c_lut2_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut2_v_coef_c_lut2_v(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT1_V (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut1_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut1_v(void);
void reg_symphony_sd_encoder_set_coef_c_lut1_v_coef_c_lut1_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut1_v_coef_c_lut1_v(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_C_LUT0_V (read/write)
  */
void reg_symphony_sd_encoder_set_coef_c_lut0_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut0_v(void);
void reg_symphony_sd_encoder_set_coef_c_lut0_v_coef_c_lut0_v(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_c_lut0_v_coef_c_lut0_v(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_LUT3_Y (read/write)
  */
void reg_symphony_sd_encoder_set_coef_lut3_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut3_y(void);
void reg_symphony_sd_encoder_set_coef_lut3_y_coef_lut3_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut3_y_coef_lut3_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_LUT2_Y (read/write)
  */
void reg_symphony_sd_encoder_set_coef_lut2_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut2_y(void);
void reg_symphony_sd_encoder_set_coef_lut2_y_coef_lut2_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut2_y_coef_lut2_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_LUT1_Y (read/write)
  */
void reg_symphony_sd_encoder_set_coef_lut1_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut1_y(void);
void reg_symphony_sd_encoder_set_coef_lut1_y_coef_lut1_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut1_y_coef_lut1_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_COEF_LUT0_Y (read/write)
  */
void reg_symphony_sd_encoder_set_coef_lut0_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut0_y(void);
void reg_symphony_sd_encoder_set_coef_lut0_y_coef_lut0_y(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_coef_lut0_y_coef_lut0_y(void);

/*!
  register REGSYMPHONY_SD_ENCODER_SIGN_CTL (read/write)
  */
void reg_symphony_sd_encoder_set_sign_ctl(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_sign_ctl(void);
void reg_symphony_sd_encoder_set_sign_ctl_sign_ctl(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_sign_ctl_sign_ctl(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC_OFFSET (read/write)
  */
void reg_symphony_sd_encoder_set_dac_offset(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac_offset(void);
void reg_symphony_sd_encoder_set_dac_offset_dac0_offset(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac_offset_dac0_offset(void);
void reg_symphony_sd_encoder_set_dac_offset_field1_other_vbi_first(mt_u8 data);
void reg_symphony_sd_encoder_set_dac_offset_field2_other_vbi_first(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac_offset_field2_other_vbi_first(void);
void reg_symphony_sd_encoder_set_dac_offset_vbi_priority_mode(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac_offset_vbi_priority_mode(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC123_PARA (read/write)
  */
void reg_symphony_sd_encoder_set_dac123_para(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac123_para(void);
void reg_symphony_sd_encoder_set_dac123_para_df_coef_b(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_para_df_coef_b(void);
void reg_symphony_sd_encoder_set_dac123_para_df_coef_a(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_para_df_coef_a(void);
void reg_symphony_sd_encoder_set_dac123_para_df_sign_b(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac123_para_df_sign_b(void);
void reg_symphony_sd_encoder_set_dac123_para_df_en_1(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac123_para_df_en_1(void);
void reg_symphony_sd_encoder_set_dac123_para_df_en_2(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac123_para_df_en_2(void);
void reg_symphony_sd_encoder_set_dac123_para_df_en_3(mt_u8 data);
mt_u8   reg_symphony_sd_encoder_get_dac123_para_df_en_3(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC0_ANTI_COEF1_0 (read/write)
  */
void reg_symphony_sd_encoder_set_dac0_anti_coef1_0(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac0_anti_coef1_0(void);
void reg_symphony_sd_encoder_set_dac0_anti_coef1_0_dac0_anti_coef0(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_anti_coef1_0_dac0_anti_coef0(void);
void reg_symphony_sd_encoder_set_dac0_anti_coef1_0_dac0_anti_coef1(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_anti_coef1_0_dac0_anti_coef1(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC0_ANTI_COEF3_2 (read/write)
  */
void reg_symphony_sd_encoder_set_dac0_anti_coef3_2(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac0_anti_coef3_2(void);
void reg_symphony_sd_encoder_set_dac0_anti_coef3_2_dac0_anti_coef2(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_anti_coef3_2_dac0_anti_coef2(void);
void reg_symphony_sd_encoder_set_dac0_anti_coef3_2_dac0_anti_coef3(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac0_anti_coef3_2_dac0_anti_coef3(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC123_ANTI_COEF1_0 (read/write)
  */
void reg_symphony_sd_encoder_set_dac123_anti_coef1_0(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac123_anti_coef1_0(void);
void reg_symphony_sd_encoder_set_dac123_anti_coef1_0_dac123_anti_coef0(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_anti_coef1_0_dac123_anti_coef0(void);
void reg_symphony_sd_encoder_set_dac123_anti_coef1_0_dac123_anti_coef1(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_anti_coef1_0_dac123_anti_coef1(void);

/*!
  register REGSYMPHONY_SD_ENCODER_DAC123_ANTI_COEF3_2 (read/write)
  */
void reg_symphony_sd_encoder_set_dac123_anti_coef3_2(mt_u32 data);
mt_u32  reg_symphony_sd_encoder_get_dac123_anti_coef3_2(void);
void reg_symphony_sd_encoder_set_dac123_anti_coef3_2_dac123_anti_coef2(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_anti_coef3_2_dac123_anti_coef2(void);
void reg_symphony_sd_encoder_set_dac123_anti_coef3_2_dac123_anti_coef3(mt_u16 data);
mt_u16  reg_symphony_sd_encoder_get_dac123_anti_coef3_2_dac123_anti_coef3(void);

/*!
  SYMPHONY_SD_Encoder reg init function
  */
void reg_symphony_sd_encoder_init(void);

#ifdef __cplusplus
}
#endif

#endif

