///////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
//  This file is marked as "read only".
//
///////////////////////////////////////////////////////////////////////////////

#pragma once

#include "CDiags.h"
#include "CHalDecoder.h"
#include "CReceiverCommon.h"
#include "StringUtils.h"
#include "Trace.h"
#include "IXDrm.h"
#include <string>

// ===============================================================================================================
// Base diagnostics event used for receiver side events
// ===============================================================================================================

class CDiagsReceiverEvent : public IDiagsEvent
{
public:
    CDiagsReceiverEvent()
        : IDiagsEvent()
        , PipeIdN(kDiagsPipeIdN_FullScreen)
        , MediaTransportId(0)
        , UniqueId(0)
        , ContentId(GUID_NULL)
        , Channel(INVALID_UINT32)
    {
    }
    virtual ~CDiagsReceiverEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        //Pipe id currently assigned to the playback receiver
        DiagsLogPipeId(L"PipeId", PipeIdN);
        //Unique ids associated with this tune
        DiagsLogValue(L"MTId", MediaTransportId);
        DiagsLogValue(L"UId", UniqueId);
        DiagsLogGuid(L"ServiceId", ContentId);
        //Channel number this receiver is on currently
        DiagsLogValue(L"Channel", Channel);
    }
    __override const WCHAR* DiagsGetEventMessage(void) = 0;
    __override kDiagsEvent DiagsGetEventType(void) = 0;
    __override bool DiagsIsError(void) = 0;

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return IDiagsEvent::DiagsSerializeEventDataLength(version) + 4*4+16;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        IDiagsEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, PipeIdN);
        DiagsPackUint32(data, MediaTransportId);
        DiagsPackUint32(data, UniqueId);
        DiagsPackGuid(data, ContentId);
        DiagsPackUint32(data, Channel);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        IDiagsEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, PipeIdN);
        DiagsUnpackUint32(data, MediaTransportId);
        DiagsUnpackUint32(data, UniqueId);
        DiagsUnpackGuid(data, ContentId);
        DiagsUnpackUint32(data, Channel);
        return true;
    }

public:
    //Pipe id currently assigned to the playback receiver
    uint32 PipeIdN;
    //Unique ids associated with this tune
    uint32 MediaTransportId;
    uint32 UniqueId;
    GUID   ContentId;
    //Channel number this receiver is on currently
    uint32 Channel;
};

// ===============================================================================================================
// Periodic diagnostics event generated by each receiver currently active in the system
// ===============================================================================================================

class CDiagsReceiverUpdateEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverUpdateEvent()
        : CDiagsReceiverEvent()
        , TuneTime(0)
        , BitRate(0)
        , TimeToTuneTotal(0)
        , TimeToTuneApp(0)
        , TimeToTuneAV(0)
        , IsIFrameOnlyMode(false)
        , EncodecPictureWidth(0)
        , EncodecPictureHeight(0)
        , AspectX(0)
        , AspectY(0)
        , IsStreaming(false)
        , BytesReceived(0)
        , ProgramId(INVALID_UINT32)
        , NumRebuffering(0)
        , Discontinuities(0)
        , DiscontinuitiesPackets(0)
        , RtpPayloadError(0)
        , DroppedPacketsUntilRap(0)
        , EcmParseErrors(0)
        , EcmLookupError(0)
        , Drift(0)
        , AVSync(0)
        , CpuTotalUsed(0)
        , CpuLast(0)
        , CpuAverage(0)
        , CpuMaximum(0)
        , VideoStreamType(0)
        , VideoPtsDelta(0)
        , VideoPtsDeltaMin(0)
        , VideoPtsDeltaMax(0)
        , VideoPtsDeltaHal(0)
        , VideoDataDropped(0)
        , VideoDataThroughput(0)
        , VideoAccessControlBlockedCounter(0)
        , VideoAccessControlUnblockedCounter(0)
        , VideoFramesDecoded(0)
        , VideoFramesDropped(0)
        , VideoDecoderErrors(0)
        , VideoBufferUnderruns(0)
        , VideoBufferOverflows(0)
        , VideoFifoSize(0)
        , VideoFifoRd(0)
        , VideoFifoWr(0)
        , VideoDrmErrors(0)
        , VideoCryptoError(0)
        , AudioStreamType(0)
        , AudioPtsDelta(0)
        , AudioPtsDeltaMin(0)
        , AudioPtsDeltaMax(0)
        , AudioPtsDeltaHal(0)
        , AudioDataDropped(0)
        , AudioDataThroughput(0)
        , AudioAccessControlBlockedCounter(0)
        , AudioAccessControlUnblockedCounter(0)
        , AudioSamplesDecoded(0)
        , AudioSamplesDropped(0)
        , AudioDecoderErrors(0)
        , AudioBufferUnderruns(0)
        , AudioBufferOverflows(0)
        , AudioFifoSize(0)
        , AudioFifoRd(0)
        , AudioFifoWr(0)
        , AudioDrmErrors(0)
        , AudioCryptoError(0)
        , AudioDescriptionStreamType(0)
        , AudioDescriptionPtsDelta(0)
        , AudioDescriptionPtsDeltaMin(0)
        , AudioDescriptionPtsDeltaMax(0)
        , AudioDescriptionPtsDeltaHal(0)
        , AudioDescriptionDataDropped(0)
        , AudioDescriptionDataThroughput(0)
        , AudioDescriptionAccessControlBlockedCounter(0)
        , AudioDescriptionAccessControlUnblockedCounter(0)
        , AudioDescriptionSamplesDecoded(0)
        , AudioDescriptionSamplesDropped(0)
        , AudioDescriptionDecoderErrors(0)
        , AudioDescriptionBufferUnderruns(0)
        , AudioDescriptionBufferOverflows(0)
        , AudioDescriptionFifoSize(0)
        , AudioDescriptionFifoRd(0)
        , AudioDescriptionFifoWr(0)
        , AudioDescriptionDrmErrors(0)
        , AudioDescriptionCryptoError(0)
        , BytesCCReceived(0)
        , SubtitlesCharsRendered(0)
        , TotalNumUnderrun(0)
        , TotalDiscontinuitiesPackets(0)
    {
        VideoDSPCrashes[0] = 0;
        AudioDSPCrashes[0] = 0;
        AudioDescriptionDSPCrashes[0] = 0;
    }
    virtual ~CDiagsReceiverUpdateEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        //Time it is tuned to so far
        DiagsLogValue(L"TunedFor", TuneTime);

        //Time it is tuned to so far
        DiagsLogValue(L"BitRate", BitRate);

        //Whether it is in IFrame only mode
        DiagsLogWString(L"IFrameOnlyMode", IsIFrameOnlyMode ? L"true" : L"false");

        //Encoded picture size
        std::string encodedPictureSize = toString(EncodecPictureWidth) + "x" + toString(EncodecPictureHeight);
        DiagsLogString(L"EncodedPictureSize", encodedPictureSize.c_str());
        //Aspect ratio
        std::string aspectRatio = toString(AspectX) + "x" + toString(AspectY);
        DiagsLogString(L"PixelAspectRatio", aspectRatio.c_str());

        //Is it currently streaming?
        DiagsLogWString(L"Streaming", IsStreaming ? L"true" : L"false");
        //Number of bytes received
        DiagsLogString(L"BytesReceived", toString64(BytesReceived, false).c_str());

        //Current program id being processed
        DiagsLogValue(L"ProgramId", ProgramId);

        //Number of times we did rebuffering for various reasons
        DiagsLogValue(L"TimelineDiscontinuity", RebufferTimes[kSyncReason_TimelineDiscontinuity]);
        DiagsLogValue(L"VideoUnderrun", RebufferTimes[kSyncReason_VideoBufferUnderrun]);
        DiagsLogValue(L"AudioUnderrun", RebufferTimes[kSyncReason_AudioBufferUnderrun]);
        DiagsLogValue(L"BufferOverrun", RebufferTimes[kSyncReason_BufferOverrun]);
        DiagsLogValue(L"DecoderStall", RebufferTimes[kSyncReason_DecoderStall]);
        DiagsLogValue(L"PmtChanged", RebufferTimes[kSyncReason_PmtChanged]);
        DiagsLogValue(L"SelectComponentVideo", RebufferTimes[kSyncReason_SelectComponentVideo]);
        DiagsLogValue(L"SelectComponentAudio", RebufferTimes[kSyncReason_SelectComponentAudio]);
        //Number of times we did rebuffering
        DiagsLogValue(L"Rebuffer", NumRebuffering);
        //Number of sequence number discontinuites
        DiagsLogValue(L"Discontinuities", Discontinuities);
        DiagsLogValue(L"DiscontinuitiesPackets", DiscontinuitiesPackets);
        DiagsLogValue(L"RtpPayloadError", RtpPayloadError);
        DiagsLogValue(L"DroppedPacketsUntilRap", DroppedPacketsUntilRap);
        DiagsLogValue(L"EcmParseErrors", EcmParseErrors);
        DiagsLogValue(L"EcmLookupError", EcmLookupError);

        //Clock drift
        DiagsLogValue(L"Drift", Drift);

        //Video Diagnostics
        //
        DiagsLogString(L"VideoCodec", CHalDecoder::StreamName(VideoStreamType));
        DiagsLogValue(L"VideoPtsDelta", VideoPtsDelta);
        DiagsLogValue(L"VideoPtsDeltaHal", VideoPtsDeltaHal);
        DiagsLogString(L"VideoDataDropped", toString64(VideoDataDropped, false).c_str());
        DiagsLogValue(L"VideoDataThroughput", (int)((VideoDataThroughput * 1000) / (TuneTime ? TuneTime : 1)));
        //AccessControl diags
        DiagsLogValue(L"VideoAccessControlBlockedCounter", VideoAccessControlBlockedCounter);
        DiagsLogValue(L"VideoAccessControlUnblockedCounter", VideoAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsLogValue(L"VideoFramesDecoded", VideoFramesDecoded);
        DiagsLogValue(L"VideoFramesDropped", VideoFramesDropped);
        DiagsLogValue(L"VideoDecoderErrors", VideoDecoderErrors);
        DiagsLogValue(L"VideoBufferUnderruns", VideoBufferUnderruns);
        DiagsLogValue(L"VideoBufferOverflows", VideoBufferOverflows);
        DiagsLogValue(L"VideoFifoSize", VideoFifoSize);
        DiagsLogValue(L"VideoFifoRd", VideoFifoRd);
        DiagsLogValue(L"VideoFifoWr", VideoFifoWr);
        DiagsLogString(L"VideoDSPCrashes", VideoDSPCrashes);
        DiagsLogValue(L"VideoDrmErrors", VideoDrmErrors);
        DiagsLogValue(L"VideoCryptoError", VideoCryptoError);

        //Audio Diagnostics
        //
        DiagsLogString(L"AudioCodec", CHalDecoder::StreamName(AudioStreamType));
        DiagsLogValue(L"AudioPtsDelta", AudioPtsDelta);
        DiagsLogValue(L"AudioPtsDeltaHal", AudioPtsDeltaHal);
        DiagsLogString(L"AudioDataDropped", toString64(AudioDataDropped, false).c_str());
        DiagsLogValue(L"AudioDataThroughput", (int)((AudioDataThroughput * 1000) / (TuneTime ? TuneTime : 1)));
        //AccessControl diags
        DiagsLogValue(L"AudioAccessControlBlockedCounter", AudioAccessControlBlockedCounter);
        DiagsLogValue(L"AudioAccessControlUnblockedCounter", AudioAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsLogValue(L"AudioSamplesDecoded", AudioSamplesDecoded);
        DiagsLogValue(L"AudioSamplesDropped", AudioSamplesDropped);
        DiagsLogValue(L"AudioDecoderErrors", AudioDecoderErrors);
        DiagsLogValue(L"AudioBufferUnderruns", AudioBufferUnderruns);
        DiagsLogValue(L"AudioBufferOverflows", AudioBufferOverflows);
        DiagsLogValue(L"AudioFifoSize", AudioFifoSize);
        DiagsLogValue(L"AudioFifoRd", AudioFifoRd);
        DiagsLogValue(L"AudioFifoWr", AudioFifoWr);
        DiagsLogString(L"AudioDSPCrashes", AudioDSPCrashes);
        DiagsLogValue(L"AudioDrmErrors", AudioDrmErrors);
        DiagsLogValue(L"AudioCryptoError", AudioCryptoError);

        //Audio Description Diagnostics
        //
        DiagsLogString(L"AudioDescCodec", CHalDecoder::StreamName(AudioDescriptionStreamType));
        DiagsLogValue(L"AudioDescPtsDelta", AudioDescriptionPtsDelta);
        DiagsLogValue(L"AudioDescPtsDeltaHal", AudioDescriptionPtsDeltaHal);
        DiagsLogString(L"AudioDescDataDropped", toString64(AudioDescriptionDataDropped, false).c_str());
        DiagsLogValue(L"AudioDescDataThroughput", (int)((AudioDescriptionDataThroughput * 1000) / (TuneTime ? TuneTime : 1)));
        //AccessControl diags
        DiagsLogValue(L"AudioDescAccessControlBlockedCounter", AudioDescriptionAccessControlBlockedCounter);
        DiagsLogValue(L"AudioDescAccessControlUnblockedCounter", AudioDescriptionAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsLogValue(L"AudioDescSamplesDecoded", AudioDescriptionSamplesDecoded);
        DiagsLogValue(L"AudioDescSamplesDropped", AudioDescriptionSamplesDropped);
        DiagsLogValue(L"AudioDescDecoderErrors", AudioDescriptionDecoderErrors);
        DiagsLogValue(L"AudioDescBufferUnderruns", AudioDescriptionBufferUnderruns);
        DiagsLogValue(L"AudioDescBufferOverflows", AudioDescriptionBufferOverflows);
        DiagsLogValue(L"AudioDescFifoSize", AudioDescriptionFifoSize);
        DiagsLogValue(L"AudioDescFifoRd", AudioDescriptionFifoRd);
        DiagsLogValue(L"AudioDescFifoWr", AudioDescriptionFifoWr);
        DiagsLogString(L"AudioDescDSPCrashes", AudioDescriptionDSPCrashes);
        DiagsLogValue(L"AudioDescDrmErrors", AudioDescriptionDrmErrors);
        DiagsLogValue(L"AudioDescCryptoError", AudioDescriptionCryptoError);

        //Number of bytes received for 608/708 CC services
        DiagsLogValue(L"BytesCCReceived", BytesCCReceived);

        //Subtitling diagnostics info
        DiagsLogValue(L"SubtitlesCharsRendered", SubtitlesCharsRendered);

        //Global counters
        //
        //Total number of times the decoder has underrun/rebuffered, since box reboot
        DiagsLogValue(L"TotalAVUnderruns", TotalNumUnderrun);
        //Total number of packets missing in all discontinuities so far, since box reboot
        DiagsLogValue(L"TotalDiscontinuitiesPackets ", TotalDiscontinuitiesPackets);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.Update.Renderer"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Update; }
    __override bool DiagsIsError(void) { return false; }

    __override LogStorageMode DiagsLogStorageMode(void)
    {
        return kLogStorageMode_Persist;
    }
    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 550 + kSyncReason_Max * 4 + 4 + 2*4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        //Time is is tuned to so far
        DiagsPackUint32(data, TuneTime);

        //Bitrate as specified
        DiagsPackUint32(data, BitRate);

        //Time taken for last tune
        DiagsPackUint32(data, TimeToTuneTotal);
        DiagsPackUint32(data, TimeToTuneApp);
        DiagsPackUint32(data, TimeToTuneAV);

        //Whether it is in IFrame only mode
        DiagsPackBool(data, IsIFrameOnlyMode);

        //Encoded picture size
        DiagsPackInt32(data, EncodecPictureWidth);
        DiagsPackInt32(data, EncodecPictureHeight);
        //Aspect ratio
        DiagsPackInt32(data, AspectX);
        DiagsPackInt32(data, AspectY);

        //Is it currently streaming?
        DiagsPackBool(data, IsStreaming);
        //Number of bytes received
        DiagsPackUint64(data, BytesReceived);

        //Current program id being processed
        DiagsPackUint32(data, ProgramId);

        //Number of times it rebuffered for various reasons
        for (int i=0; i<kSyncReason_Max; i++) DiagsPackUint32(data, RebufferTimes[i]);
        //Number of times the decoder has stalled
        DiagsPackUint32(data, NumRebuffering);
        //Number of sequence number discontinuites
        DiagsPackUint32(data, Discontinuities);
        //Total number of packets missing in all discontinuities so far
        DiagsPackUint32(data, DiscontinuitiesPackets);
        //Missing RTP payload
        DiagsPackUint32(data, RtpPayloadError);
        //Dropped RTP packets until a rap was found
        DiagsPackUint32(data, DroppedPacketsUntilRap);
        //Numer of times we failed to parse ECM packets
        DiagsPackUint32(data, EcmParseErrors);
        //Number of frames we failed to do a ECM lookup
        DiagsPackUint32(data, EcmLookupError);

        //Clock drift
        DiagsPackInt32(data, Drift);
        //Current AV Sync
        DiagsPackInt32(data, AVSync);

        //CPU usage
        DiagsPackUint32(data, CpuTotalUsed);
        DiagsPackUint32(data, CpuLast);
        DiagsPackUint32(data, CpuAverage);
        DiagsPackUint32(data, CpuMaximum);

        //Video Diagnostics
        //
        DiagsPackInt32(data, VideoStreamType);
        DiagsPackInt32(data, VideoPtsDelta);
        DiagsPackInt32(data, VideoPtsDeltaMin);
        DiagsPackInt32(data, VideoPtsDeltaMax);
        DiagsPackInt32(data, VideoPtsDeltaHal);
        DiagsPackUint64(data, VideoDataDropped);
        DiagsPackUint64(data, VideoDataThroughput);
        //AccessControl diags
        DiagsPackUint32(data, VideoAccessControlBlockedCounter);
        DiagsPackUint32(data, VideoAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsPackUint32(data, VideoFramesDecoded);
        DiagsPackUint32(data, VideoFramesDropped);
        DiagsPackUint32(data, VideoDecoderErrors);
        DiagsPackUint32(data, VideoBufferUnderruns);
        DiagsPackUint32(data, VideoBufferOverflows);
        DiagsPackUint32(data, VideoFifoSize);
        DiagsPackUint32(data, VideoFifoRd);
        DiagsPackUint32(data, VideoFifoWr);
        DiagsPackChars(data, VideoDSPCrashes, 64);
        DiagsPackUint32(data, VideoDrmErrors);
        DiagsPackUint32(data, VideoCryptoError);

        //Audio Diagnostics
        //
        DiagsPackInt32(data, AudioStreamType);
        DiagsPackInt32(data, AudioPtsDelta);
        DiagsPackInt32(data, AudioPtsDeltaMin);
        DiagsPackInt32(data, AudioPtsDeltaMax);
        DiagsPackInt32(data, AudioPtsDeltaHal);
        DiagsPackUint64(data, AudioDataDropped);
        DiagsPackUint64(data, AudioDataThroughput);
        //AccessControl diags
        DiagsPackUint32(data, AudioAccessControlBlockedCounter);
        DiagsPackUint32(data, AudioAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsPackUint32(data, AudioSamplesDecoded);
        DiagsPackUint32(data, AudioSamplesDropped);
        DiagsPackUint32(data, AudioDecoderErrors);
        DiagsPackUint32(data, AudioBufferUnderruns);
        DiagsPackUint32(data, AudioBufferOverflows);
        DiagsPackUint32(data, AudioFifoSize);
        DiagsPackUint32(data, AudioFifoRd);
        DiagsPackUint32(data, AudioFifoWr);
        DiagsPackChars(data, AudioDSPCrashes, 64);
        DiagsPackUint32(data, AudioDrmErrors);
        DiagsPackUint32(data, AudioCryptoError);

        //Audio Description Diagnostics
        //
        DiagsPackInt32(data, AudioDescriptionStreamType);
        DiagsPackInt32(data, AudioDescriptionPtsDelta);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaMin);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaMax);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaHal);
        DiagsPackUint64(data, AudioDescriptionDataDropped);
        DiagsPackUint64(data, AudioDescriptionDataThroughput);
        //AccessControl diags
        DiagsPackUint32(data, AudioDescriptionAccessControlBlockedCounter);
        DiagsPackUint32(data, AudioDescriptionAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsPackUint32(data, AudioDescriptionSamplesDecoded);
        DiagsPackUint32(data, AudioDescriptionSamplesDropped);
        DiagsPackUint32(data, AudioDescriptionDecoderErrors);
        DiagsPackUint32(data, AudioDescriptionBufferUnderruns);
        DiagsPackUint32(data, AudioDescriptionBufferOverflows);
        DiagsPackUint32(data, AudioDescriptionFifoSize);
        DiagsPackUint32(data, AudioDescriptionFifoRd);
        DiagsPackUint32(data, AudioDescriptionFifoWr);
        DiagsPackChars(data, AudioDescriptionDSPCrashes, 64);
        DiagsPackUint32(data, AudioDescriptionDrmErrors);
        DiagsPackUint32(data, AudioDescriptionCryptoError);

        //Number of bytes received for each of 608/708 CC services
        DiagsPackUint32(data, BytesCCReceived);

        //Subtitling diagnostics info
        DiagsPackUint32(data, SubtitlesCharsRendered);

        //Global counters
        //
        //Total number of times the decoder has underrun/rebuffered, since box reboot
        DiagsPackUint32(data, TotalNumUnderrun);
        //Total number of packets missing in all discontinuities so far, since box reboot
        DiagsPackUint32(data, TotalDiscontinuitiesPackets);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        //Time is is tuned to so far
        DiagsUnpackUint32(data, TuneTime);

        //Bitrate as specified
        DiagsUnpackUint32(data, BitRate);

        //Time taken for last tune
        DiagsUnpackUint32(data, TimeToTuneTotal);
        DiagsUnpackUint32(data, TimeToTuneApp);
        DiagsUnpackUint32(data, TimeToTuneAV);

        //Whether it is in IFrame only mode
        DiagsUnpackBool(data, IsIFrameOnlyMode);

        //Encoded picture size
        DiagsUnpackInt32(data, EncodecPictureWidth);
        DiagsUnpackInt32(data, EncodecPictureHeight);
        //Aspect ratio
        DiagsUnpackInt32(data, AspectX);
        DiagsUnpackInt32(data, AspectY);

        //Is it currently streaming?
        DiagsUnpackBool(data, IsStreaming);
        //Number of bytes received
        DiagsUnpackUint64(data, BytesReceived);

        //Current program id being processed
        DiagsUnpackUint32(data, ProgramId);

        //Number of times it rebuffered for various reasons
        for(int i=0; i<kSyncReason_Max; i++) DiagsUnpackUint32(data, RebufferTimes[i]);
        //Number of times the decoeder has stalled
        DiagsUnpackUint32(data, NumRebuffering);
        //Number of sequence number discontinuites
        DiagsUnpackUint32(data, Discontinuities);
        //Total number of packets missing in all discontinuities so far
        DiagsUnpackUint32(data, DiscontinuitiesPackets);
        //Missing RTP payload
        DiagsUnpackUint32(data, RtpPayloadError);
        //Dropped RTP packets until a rap was found
        DiagsUnpackUint32(data, DroppedPacketsUntilRap);
        //Numer of times we failed to parse ECM packets
        DiagsUnpackUint32(data, EcmParseErrors);
        //Number of frames we failed to do a ECM lookup
        DiagsUnpackUint32(data, EcmLookupError);

        //Clock drift
        DiagsUnpackInt32(data, Drift);
        //Current AV Sync
        DiagsUnpackInt32(data, AVSync);

        //CPU usage
        DiagsUnpackUint32(data, CpuTotalUsed);
        DiagsUnpackUint32(data, CpuLast);
        DiagsUnpackUint32(data, CpuAverage);
        DiagsUnpackUint32(data, CpuMaximum);

        //Video Diagnostics
        //
        DiagsUnpackInt32(data, VideoStreamType);
        DiagsUnpackInt32(data, VideoPtsDelta);
        DiagsUnpackInt32(data, VideoPtsDeltaMin);
        DiagsUnpackInt32(data, VideoPtsDeltaMax);
        DiagsUnpackInt32(data, VideoPtsDeltaHal);
        DiagsUnpackUint64(data, VideoDataDropped);
        DiagsUnpackUint64(data, VideoDataThroughput);
        //AccessControl diags
        DiagsUnpackUint32(data, VideoAccessControlBlockedCounter);
        DiagsUnpackUint32(data, VideoAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsUnpackUint32(data, VideoFramesDecoded);
        DiagsUnpackUint32(data, VideoFramesDropped);
        DiagsUnpackUint32(data, VideoDecoderErrors);
        DiagsUnpackUint32(data, VideoBufferUnderruns);
        DiagsUnpackUint32(data, VideoBufferOverflows);
        DiagsUnpackUint32(data, VideoFifoSize);
        DiagsUnpackUint32(data, VideoFifoRd);
        DiagsUnpackUint32(data, VideoFifoWr);
        DiagsUnpackChars(data, VideoDSPCrashes, 64);
        DiagsUnpackUint32(data, VideoDrmErrors);
        DiagsUnpackUint32(data, VideoCryptoError);

        //Audio Diagnostics
        //
        DiagsUnpackInt32(data, AudioStreamType);
        DiagsUnpackInt32(data, AudioPtsDelta);
        DiagsUnpackInt32(data, AudioPtsDeltaMin);
        DiagsUnpackInt32(data, AudioPtsDeltaMax);
        DiagsUnpackInt32(data, AudioPtsDeltaHal);
        DiagsUnpackUint64(data, AudioDataDropped);
        DiagsUnpackUint64(data, AudioDataThroughput);
        //AccessControl diags
        DiagsUnpackUint32(data, AudioAccessControlBlockedCounter);
        DiagsUnpackUint32(data, AudioAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsUnpackUint32(data, AudioSamplesDecoded);
        DiagsUnpackUint32(data, AudioSamplesDropped);
        DiagsUnpackUint32(data, AudioDecoderErrors);
        DiagsUnpackUint32(data, AudioBufferUnderruns);
        DiagsUnpackUint32(data, AudioBufferOverflows);
        DiagsUnpackUint32(data, AudioFifoSize);
        DiagsUnpackUint32(data, AudioFifoRd);
        DiagsUnpackUint32(data, AudioFifoWr);
        DiagsUnpackChars(data, AudioDSPCrashes,64);
        DiagsUnpackUint32(data, AudioDrmErrors);
        DiagsUnpackUint32(data, AudioCryptoError);

        //Audio Description Diagnostics
        //
        DiagsUnpackInt32(data, AudioDescriptionStreamType);
        DiagsUnpackInt32(data, AudioDescriptionPtsDelta);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaMin);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaMax);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaHal);
        DiagsUnpackUint64(data, AudioDescriptionDataDropped);
        DiagsUnpackUint64(data, AudioDescriptionDataThroughput);
        //AccessControl diags
        DiagsUnpackUint32(data, AudioDescriptionAccessControlBlockedCounter);
        DiagsUnpackUint32(data, AudioDescriptionAccessControlUnblockedCounter);
        //Decoder HAL diagnostics
        DiagsUnpackUint32(data, AudioDescriptionSamplesDecoded);
        DiagsUnpackUint32(data, AudioDescriptionSamplesDropped);
        DiagsUnpackUint32(data, AudioDescriptionDecoderErrors);
        DiagsUnpackUint32(data, AudioDescriptionBufferUnderruns);
        DiagsUnpackUint32(data, AudioDescriptionBufferOverflows);
        DiagsUnpackUint32(data, AudioDescriptionFifoSize);
        DiagsUnpackUint32(data, AudioDescriptionFifoRd);
        DiagsUnpackUint32(data, AudioDescriptionFifoWr);
        DiagsUnpackChars(data, AudioDescriptionDSPCrashes,64);
        DiagsUnpackUint32(data, AudioDescriptionDrmErrors);
        DiagsUnpackUint32(data, AudioDescriptionCryptoError);

        //Number of bytes received for each of 608/708 CC services
        DiagsUnpackUint32(data, BytesCCReceived);

        //Subtitling diagnostics info
        DiagsUnpackUint32(data, SubtitlesCharsRendered);

        //Global counters
        //
        //Total number of times the decoder has underrun/rebuffered, since box reboot
        DiagsUnpackUint32(data, TotalNumUnderrun);
        //Total number of packets missing in all discontinuities so far, since box reboot
        DiagsUnpackUint32(data, TotalDiscontinuitiesPackets);

        return true;
    }

public:
    //Time is is tuned to so far
    uint32           TuneTime;

    //Bitrate as specified
    uint32           BitRate;

    //Time taken for last tune
    uint32           TimeToTuneTotal;
    uint32           TimeToTuneApp;
    uint32           TimeToTuneAV;

    //Whether it is in IFrame only mode
    bool             IsIFrameOnlyMode;

    //Encoded picture size
    int              EncodecPictureWidth;
    int              EncodecPictureHeight;
    //Aspect ratio
    int              AspectX;
    int              AspectY;

    //Is it currently streaming?
    bool             IsStreaming;
    //Number of bytes received
    uint64           BytesReceived;

    //Current program id being processed
    uint32           ProgramId;

    //Number of times it rebuffered for various reasons
    uint32           RebufferTimes[kSyncReason_Max];
    //Number of times the decoeder has stalled
    uint32           NumRebuffering;
    //Number of sequence number discontinuites
    uint32           Discontinuities;
    //Total number of packets missing in all discontinuities so far
    uint32           DiscontinuitiesPackets;
    //Missing RTP payload
    uint32           RtpPayloadError;
    //Dropped RTP packets until a rap was found
    uint32           DroppedPacketsUntilRap;
    //Numer of times we failed to parse ECM packets
    uint32           EcmParseErrors;
    //Number of frames we failed to do a ECM lookup
    uint32           EcmLookupError;

    //Clock drift
    int              Drift;
    //Current AV Sync
    int              AVSync;

    //CPU usage
    uint32           CpuTotalUsed;
    uint32           CpuLast;
    uint32           CpuAverage;
    uint32           CpuMaximum;

    //Video Diagnostics
    //
    int              VideoStreamType;
    int              VideoPtsDelta;
    int              VideoPtsDeltaMin;
    int              VideoPtsDeltaMax;
    int              VideoPtsDeltaHal;
    uint64           VideoDataDropped;
    uint64           VideoDataThroughput;
    //AccessControl diags
    uint32           VideoAccessControlBlockedCounter;
    uint32           VideoAccessControlUnblockedCounter;
    //Decoder HAL diagnostics
    uint32           VideoFramesDecoded;
    uint32           VideoFramesDropped;
    uint32           VideoDecoderErrors;
    uint32           VideoBufferUnderruns;
    uint32           VideoBufferOverflows;
    uint32           VideoFifoSize;
    uint32           VideoFifoRd;
    uint32           VideoFifoWr;
    char             VideoDSPCrashes[64];
    uint32           VideoDrmErrors;
    uint32           VideoCryptoError;

    //Audio Diagnostics
    //
    int              AudioStreamType;
    int              AudioPtsDelta;
    int              AudioPtsDeltaMin;
    int              AudioPtsDeltaMax;
    int              AudioPtsDeltaHal;
    uint64           AudioDataDropped;
    uint64           AudioDataThroughput;
    //AccessControl diags
    uint32           AudioAccessControlBlockedCounter;
    uint32           AudioAccessControlUnblockedCounter;
    //Decoder HAL diagnostics
    uint32           AudioSamplesDecoded;
    uint32           AudioSamplesDropped;
    uint32           AudioDecoderErrors;
    uint32           AudioBufferUnderruns;
    uint32           AudioBufferOverflows;
    uint32           AudioFifoSize;
    uint32           AudioFifoRd;
    uint32           AudioFifoWr;
    char             AudioDSPCrashes[64];
    uint32           AudioDrmErrors;
    uint32           AudioCryptoError;

    //Audio Description Diagnostics
    //
    int              AudioDescriptionStreamType;
    int              AudioDescriptionPtsDelta;
    int              AudioDescriptionPtsDeltaMin;
    int              AudioDescriptionPtsDeltaMax;
    int              AudioDescriptionPtsDeltaHal;
    uint64           AudioDescriptionDataDropped;
    uint64           AudioDescriptionDataThroughput;
    //AccessControl diags
    uint32           AudioDescriptionAccessControlBlockedCounter;
    uint32           AudioDescriptionAccessControlUnblockedCounter;
    //Decoder HAL diagnostics
    uint32           AudioDescriptionSamplesDecoded;
    uint32           AudioDescriptionSamplesDropped;
    uint32           AudioDescriptionDecoderErrors;
    uint32           AudioDescriptionBufferUnderruns;
    uint32           AudioDescriptionBufferOverflows;
    uint32           AudioDescriptionFifoSize;
    uint32           AudioDescriptionFifoRd;
    uint32           AudioDescriptionFifoWr;
    char             AudioDescriptionDSPCrashes[64];
    uint32           AudioDescriptionDrmErrors;
    uint32           AudioDescriptionCryptoError;

    //Number of bytes received for each of 608/708 CC services
    uint32           BytesCCReceived;

    //Subtitling diagnostics info
    uint32           SubtitlesCharsRendered;

    //Global counters
    //
    //Total number of times the decoder has underrun/rebuffered, since box reboot
    uint32           TotalNumUnderrun;
    //Total number of packets missing in all discontinuities so far, since box reboot
    uint32           TotalDiscontinuitiesPackets;
};

// ===============================================================================================================
// Global receiver counters
// ===============================================================================================================

class CReceiverGlobalDiags : public IDiagsEvent
{
public:
    CReceiverGlobalDiags()
        : IDiagsEvent()
        , TotalNumUnderrun(0)
        , TotalDiscontinuitiesPackets(0)
    {}
    virtual ~CReceiverGlobalDiags() {}

public:
    __override void DiagsGetEventData(void)
    {
        DiagsLogValue(L"TotalAVUnderruns", TotalNumUnderrun);
        DiagsLogValue(L"TotalDiscontinuitiesPackets ", TotalDiscontinuitiesPackets);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.Update.Renderer.StaticDiags"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_StaticDiags; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return IDiagsEvent::DiagsSerializeEventDataLength(version) + 4+4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        IDiagsEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, TotalNumUnderrun);
        DiagsPackUint32(data, TotalDiscontinuitiesPackets);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        IDiagsEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, TotalNumUnderrun);
        DiagsUnpackUint32(data, TotalDiscontinuitiesPackets);
        return true;
    }

public:
    //Total number of times the decoder has underrun/rebuffered, since box reboot
    uint32       TotalNumUnderrun;
    //Total number of packets missing in all discontinuities so far, since box reboot
    uint32       TotalDiscontinuitiesPackets;
};

// ===============================================================================================================
// On Tuner Error event
// ===============================================================================================================

class CDiagsReceiverTunerErrorEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverTunerErrorEvent()
        : CDiagsReceiverEvent()
    {}
    CDiagsReceiverTunerErrorEvent(int tunerError, int socketError, pkRESULT pkResult, int httpResponse)
        : CDiagsReceiverEvent()
        , TunerError(tunerError)
        , SocketError(socketError)
        , PKResult(pkResult)
        , HttpResponse(httpResponse)
    {}
    virtual ~CDiagsReceiverTunerErrorEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"TunerError", TunerError);
        DiagsLogValue(L"SocketError", SocketError);
        DiagsLogValue(L"PKResult", PKResult);
        DiagsLogValue(L"HttpResponse", HttpResponse);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.TunerError"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_TunerError; }
    __override bool DiagsIsError(void) { return true; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 12;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackInt32(data, TunerError);
        DiagsPackInt32(data, SocketError);
        DiagsPackInt32(data, PKResult);
        DiagsPackInt32(data, HttpResponse);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackInt32(data, TunerError);
        DiagsUnpackInt32(data, SocketError);
        DiagsUnpackInt32(data, PKResult);
        DiagsUnpackInt32(data, HttpResponse);
        return true;
    }

public:
    int TunerError;
    int SocketError;
    int PKResult;
    int HttpResponse;
};

// ===============================================================================================================
// Rebuffering event
// ===============================================================================================================

class CDiagsReceiverBufferingEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverBufferingEvent()
        : CDiagsReceiverEvent()
        , Reason(kSyncReason_None)
    {}
    CDiagsReceiverBufferingEvent(SyncReason reason, bool sync, bool cleanStall)
        : CDiagsReceiverEvent()
        , Reason(reason)
        , Flushed(sync)
        , CleanStall(cleanStall)
    {}
    virtual ~CDiagsReceiverBufferingEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        //Whether data was flushed
        DiagsLogString(L"Flushed", Flushed ? "true" : "false");
        //Whether we cleaned the possible HAL decoder stall
        DiagsLogString(L"CleanStall", CleanStall ? "true" : "false");
    }
    __override const WCHAR* DiagsGetEventMessage(void)
    {
        static const WCHAR* SyncReasonStrings[] =
        {
            L"AV.Buffering.None",
            L"AV.Buffering.TimelineDiscontinuity",
            L"AV.Buffering.VideoUnderrun",
            L"AV.Buffering.AudioUnderrun",
            L"AV.Buffering.Overrun",
            L"AV.Buffering.DecoderStall",
            L"AV.Buffering.Pmt",
            L"AV.Buffering.SelectComponentVideo",
            L"AV.Buffering.SelectComponentAudio",
        };
        ASSERT(Reason < kSyncReason_Max);
        return SyncReasonStrings[Reason];
    }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Buffering; }
    __override bool DiagsIsError(void) { return Reason != kSyncReason_PmtChanged; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4+1+1;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, Reason);
        DiagsPackBool(data, Flushed);
        DiagsPackBool(data, CleanStall);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, Reason);
        DiagsUnpackBool(data, Flushed);
        DiagsUnpackBool(data, CleanStall);
        return true;
    }

public:
    //Reason
    SyncReason Reason;
    //Whether we flushed the data
    bool       Flushed;
    //Whether we cleaned the possible HAL decoder stall
    bool       CleanStall;
};

// ===============================================================================================================
// Acquiring HAL Decoder
// ===============================================================================================================

class CDiagsReceiverDecoderEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverDecoderEvent()
        : CDiagsReceiverEvent()
        , Status(kDecoderStatus_Idle)
    {}
    CDiagsReceiverDecoderEvent(bool isVideo, bool isAudioDescription, DecoderStatus status, int streamType, int pid, uint64 pts, int errorCode = 0)
        : CDiagsReceiverEvent()
        , IsVideo(isVideo)
        , IsAudioDescription(isAudioDescription)
        , Status(status)
        , StreamType(streamType)
        , Pid(pid)
        , Pts(pts)
        , ErrorCode(errorCode)
    {}
    virtual ~CDiagsReceiverDecoderEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogString(L"Codec", CHalDecoder::StreamName(StreamType));
        DiagsLogValue(L"StreamType", StreamType);
        DiagsLogValue(L"Pid", Pid);
        if (IS_VALID_TIME(Pts))
        {
            DiagsLogString(L"Pts", toString64(Pts, false).c_str());
        }
        DiagsLogValue(L"ErrorCode", ErrorCode);
    }
    __override const WCHAR* DiagsGetEventMessage(void)
    {
        static const WCHAR* VideoDecoderMessage[] =
        {
            L"AV.Decoder.Video.Idle",
            L"AV.Decoder.Video.Unsupported",
            L"AV.Decoder.Video.DecoderError",
            L"AV.Decoder.Video.DrmError",
            L"AV.Decoder.Video.Failed",
            L"AV.Decoder.Video.Acquired",
            L"AV.Decoder.Video.Released",
            L"AV.Decoder.Video.Processing",
            L"AV.Decoder.Video.Dropping",
            L"AV.Decoder.Video.Flushed",
            L"AV.Decoder.Video.Discontinuity",
            L"AV.Decoder.Video.UnBlocked",
            L"AV.Decoder.Video.Blocked",
        };
        static const WCHAR* AudioDecoderMessage[] =
        {
            L"AV.Decoder.Audio.Idle",
            L"AV.Decoder.Audio.Unsupported",
            L"AV.Decoder.Audio.DecoderError",
            L"AV.Decoder.Audio.DrmError",
            L"AV.Decoder.Audio.Failed",
            L"AV.Decoder.Audio.Acquired",
            L"AV.Decoder.Audio.Released",
            L"AV.Decoder.Audio.Processing",
            L"AV.Decoder.Audio.Dropping",
            L"AV.Decoder.Audio.Flushed",
            L"AV.Decoder.Audio.Discontinuity",
            L"AV.Decoder.Audio.UnBlocked",
            L"AV.Decoder.Audio.Blocked",
        };
        static const WCHAR* AudioDescriptionDecoderMessage[] =
        {
            L"AV.Decoder.AudioDesc.Idle",
            L"AV.Decoder.AudioDesc.Unsupported",
            L"AV.Decoder.AudioDesc.DecoderError",
            L"AV.Decoder.AudioDesc.DrmError",
            L"AV.Decoder.AudioDesc.Failed",
            L"AV.Decoder.AudioDesc.Acquired",
            L"AV.Decoder.AudioDesc.Released",
            L"AV.Decoder.AudioDesc.Processing",
            L"AV.Decoder.AudioDesc.Dropping",
            L"AV.Decoder.AudioDesc.Flushed",
            L"AV.Decoder.AudioDesc.Discontinuity",
            L"AV.Decoder.AudioDesc.UnBlocked",
            L"AV.Decoder.AudioDesc.Blocked",
        };
        ASSERT(Status < kDecoderStatus_Max);
        return IsVideo
                ? VideoDecoderMessage[Status]
                : IsAudioDescription
                    ? AudioDescriptionDecoderMessage[Status]
                    : AudioDecoderMessage[Status];
    }
    __override kDiagsEvent DiagsGetEventType(void)
    {
        return IsVideo
                ? kDiagsEvent_Receiver_VideoDecoder
                : IsAudioDescription
                    ? kDiagsEvent_Receiver_AudioDescriptionDecoder
                    : kDiagsEvent_Receiver_AudioDecoder;
    }
    __override bool DiagsIsError(void) { return Status <= kDecoderStatus_Failed; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 2+12+8+4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, IsVideo);
        DiagsPackBool(data, IsAudioDescription);
        DiagsPackUint32(data, (uint32)Status);
        DiagsPackInt32(data, StreamType);
        DiagsPackInt32(data, Pid);
        DiagsPackUint64(data, Pts);
        DiagsPackInt32(data, ErrorCode);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, IsVideo);
        DiagsUnpackBool(data, IsAudioDescription);
        DiagsUnpackUint32(data, Status);
        DiagsUnpackInt32(data, StreamType);
        DiagsUnpackInt32(data, Pid);
        DiagsUnpackUint64(data, Pts);
        DiagsUnpackInt32(data, ErrorCode);
        return true;
    }

public:
    bool          IsVideo;
    bool          IsAudioDescription;
    DecoderStatus Status;
    int           StreamType;
    int           Pid;
    uint64        Pts;
    int           ErrorCode;
};

// ===============================================================================================================
// Whether we are currently Streaming
// ===============================================================================================================

class CDiagsReceiverStreamingEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverStreamingEvent()
        : CDiagsReceiverEvent()
    {}
    CDiagsReceiverStreamingEvent(bool isStreaming)
        : CDiagsReceiverEvent()
        , IsStreaming(isStreaming)
    {}
    virtual ~CDiagsReceiverStreamingEvent() {}

public:
    __override const WCHAR* DiagsGetEventMessage(void) { return IsStreaming ? L"AV.Streaming" : L"AV.Released"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Streaming; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 1;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, IsStreaming);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, IsStreaming);
        return true;
    }

public:
    bool IsStreaming;
};

// ===============================================================================================================
// ===============================================================================================================

class CDiagsSetStreamBufferDelay : public CDiagsReceiverEvent
{
public:
    CDiagsSetStreamBufferDelay()
        : CDiagsReceiverEvent()
        , Delay(0)
    {}
    CDiagsSetStreamBufferDelay(uint32 delay)
        : CDiagsReceiverEvent()
        , Delay(delay)
    {}
    virtual ~CDiagsSetStreamBufferDelay() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"Delay", Delay);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.SetStreamBufferDelay"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_SetStreamBufferDelay; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, Delay);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, Delay);
        return true;
    }

public:
    uint32 Delay; //in ms
};

// ===============================================================================================================
// PTS Delta Event
// ===============================================================================================================

class CDiagsReceiverPtsDelta : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverPtsDelta()
        : CDiagsReceiverEvent()
    {}
    CDiagsReceiverPtsDelta(int videoPtsDelta, int videoPtsDeltaMin, int videoPtsDeltaMax, int videoPtsDeltaHal,
                           int audioPtsDelta, int audioPtsDeltaMin, int audioPtsDeltaMax, int audioPtsDeltaHal,
                           int audioDescPtsDelta, int audioDescPtsDeltaMin, int audioDescPtsDeltaMax, int audioDescPtsDeltaHal,
                           uint64 currentTime, uint64 stc)
        : CDiagsReceiverEvent()
        , VideoPtsDelta(videoPtsDelta)
        , VideoPtsDeltaMin(videoPtsDeltaMin)
        , VideoPtsDeltaMax(videoPtsDeltaMax)
        , VideoPtsDeltaHal(videoPtsDeltaHal)
        , AudioPtsDelta(audioPtsDelta)
        , AudioPtsDeltaMin(audioPtsDeltaMin)
        , AudioPtsDeltaMax(audioPtsDeltaMax)
        , AudioPtsDeltaHal(audioPtsDeltaHal)
        , AudioDescriptionPtsDelta(audioDescPtsDelta)
        , AudioDescriptionPtsDeltaMin(audioDescPtsDeltaMin)
        , AudioDescriptionPtsDeltaMax(audioDescPtsDeltaMax)
        , AudioDescriptionPtsDeltaHal(audioDescPtsDeltaHal)
        , CurrentTime(currentTime)
        , STC(stc)
    {}
    virtual ~CDiagsReceiverPtsDelta() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"Video", VideoPtsDelta);
        DiagsLogValue(L"VideoMin", VideoPtsDeltaMin);
        DiagsLogValue(L"VideoMax", VideoPtsDeltaMax);
        DiagsLogValue(L"VideoHal", VideoPtsDeltaHal);
        DiagsLogValue(L"Audio", AudioPtsDelta);
        DiagsLogValue(L"AudioMin", AudioPtsDeltaMin);
        DiagsLogValue(L"AudioMax", AudioPtsDeltaMax);
        DiagsLogValue(L"AudioHal", AudioPtsDeltaHal);
        DiagsLogValue(L"AudioDesc", AudioDescriptionPtsDelta);
        DiagsLogValue(L"AudioDescMin", AudioDescriptionPtsDeltaMin);
        DiagsLogValue(L"AudioDescMax", AudioDescriptionPtsDeltaMax);
        DiagsLogValue(L"AudioDescHal", AudioDescriptionPtsDeltaHal);
        DiagsLogString(L"Time", toString64(CurrentTime, true).c_str());
        DiagsLogString(L"STC", toString64(STC, true).c_str());
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.Decoder.PtsDelta"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_PtsDelta; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4*12 + 8*2;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackInt32(data, VideoPtsDelta);
        DiagsPackInt32(data, VideoPtsDeltaMin);
        DiagsPackInt32(data, VideoPtsDeltaMax);
        DiagsPackInt32(data, VideoPtsDeltaHal);
        DiagsPackInt32(data, AudioPtsDelta);
        DiagsPackInt32(data, AudioPtsDeltaMin);
        DiagsPackInt32(data, AudioPtsDeltaMax);
        DiagsPackInt32(data, AudioPtsDeltaHal);
        DiagsPackInt32(data, AudioDescriptionPtsDelta);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaMin);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaMax);
        DiagsPackInt32(data, AudioDescriptionPtsDeltaHal);
        DiagsPackUint64(data, CurrentTime);
        DiagsPackUint64(data, STC);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackInt32(data, VideoPtsDelta);
        DiagsUnpackInt32(data, VideoPtsDeltaMin);
        DiagsUnpackInt32(data, VideoPtsDeltaMax);
        DiagsUnpackInt32(data, VideoPtsDeltaHal);
        DiagsUnpackInt32(data, AudioPtsDelta);
        DiagsUnpackInt32(data, AudioPtsDeltaMin);
        DiagsUnpackInt32(data, AudioPtsDeltaMax);
        DiagsUnpackInt32(data, AudioPtsDeltaHal);
        DiagsUnpackInt32(data, AudioDescriptionPtsDelta);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaMin);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaMax);
        DiagsUnpackInt32(data, AudioDescriptionPtsDeltaHal);
        DiagsUnpackUint64(data, CurrentTime);
        DiagsUnpackUint64(data, STC);
        return true;
    }

public:
    int VideoPtsDelta;
    int VideoPtsDeltaMin;
    int VideoPtsDeltaMax;
    int VideoPtsDeltaHal;
    int AudioPtsDelta;
    int AudioPtsDeltaMin;
    int AudioPtsDeltaMax;
    int AudioPtsDeltaHal;
    int AudioDescriptionPtsDelta;
    int AudioDescriptionPtsDeltaMin;
    int AudioDescriptionPtsDeltaMax;
    int AudioDescriptionPtsDeltaHal;
    uint64 CurrentTime;
    uint64 STC;
};

// ===============================================================================================================
// Tune timing event
// ===============================================================================================================

class CDiagsReceiverTuneTimingEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverTuneTimingEvent()
        : CDiagsReceiverEvent()
        , Action(TimingAction_Unknown)
    {}
    CDiagsReceiverTuneTimingEvent(int action, const int* timings)
        : CDiagsReceiverEvent()
        , Action(action)
    {
        ASSERT(Action >= TimingAction_Unknown && Action < TimingAction_Max);
        if (Action < TimingAction_Unknown || Action >= TimingAction_Max)
        {
            Action = TimingAction_Unknown;
        }
        memcpy_s(Timings, sizeof(Timings), timings, sizeof(Timings));
    }
    virtual ~CDiagsReceiverTuneTimingEvent() {}

public:
    __override void DiagsGetEventData(void);
    __override const WCHAR* DiagsGetEventMessage(void);
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_TuneTiming; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4 + TimingSnapshotAt_Max * 4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackInt32(data, Action);
        for(int i=0;i<TimingSnapshotAt_Max;i++) DiagsPackInt32(data, Timings[i]);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackInt32(data, Action);
        for(int i=0;i<TimingSnapshotAt_Max;i++) DiagsUnpackInt32(data, (int&)Timings[i]);
        return true;
    }

public:
    int Action;
    int Timings[TimingSnapshotAt_Max];

private:
    static const WCHAR* ActionStrings[];
};

// ===============================================================================================================
// Type of tune action being taken
// ===============================================================================================================

class CDiagsReceiverTuneEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverTuneEvent()
        : CDiagsReceiverEvent()
        , Action(TimingAction_Unknown)
        , Speed(1)
        , Rap(0)
    {}
    CDiagsReceiverTuneEvent(int action, int speed, uint64 rap)
        : CDiagsReceiverEvent()
        , Action(action)
        , Speed(speed)
        , Rap(rap)
    {
        ASSERT(Action >= TimingAction_Unknown && Action < TimingAction_Max);
        if (Action < TimingAction_Unknown || Action >= TimingAction_Max)
        {
            Action = TimingAction_Unknown;
        }
    }
    virtual ~CDiagsReceiverTuneEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"Speed", Speed);
        if (Rap != 0)
        {
            DiagsLogValue64(L"Rap", Rap);
        }
    }
    __override const WCHAR* DiagsGetEventMessage(void)
    {
        static const WCHAR* ActionStrings[] =
        {
            L"AV.Unknown",
            L"AV.Pause",
            L"AV.Play",
            L"AV.Step",
            L"AV.FastForward",
            L"AV.Rewind",
            L"AV.SkipForward",
            L"AV.SkipBackward",
            L"AV.Scan",
            L"AV.SkipPlaylistItem",
            L"AV.PlayFromBeginning",
            L"AV.PlayLive",
            L"AV.PlayAt",
            L"AV.Stop",
            L"AV.FrontTruncation",
            L"AV.TuneToLive",
            L"AV.TuneToDvb",
            L"AV.TuneToDvr",
            L"AV.TuneToVod",
            L"AV.TuneToWMS",
            L"AV.TuneToMP3",
            L"AV.TuneToMP4",
            L"AV.TuneToTimeShiftLive",
            L"AV.TuneToTimeShiftRange",
            L"AV.TuneToMpegTS",
            L"AV.TuneToTS",
            L"AV.TuneToSmoothStreaming",
        };
        ASSERT(Action >= TimingAction_Unknown && Action < TimingAction_Max);
        return ActionStrings[Action >= TimingAction_Unknown && Action < TimingAction_Max ? Action : 0];
    }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Tune; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 16;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackInt32(data, Action);
        DiagsPackInt32(data, Speed);
        DiagsPackUint64(data, Rap);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackInt32(data, Action);
        DiagsUnpackInt32(data, Speed);
        DiagsUnpackUint64(data, Rap);
        return true;
    }

public:
    int Action;
    int Speed;
    uint64 Rap;
};

// ===============================================================================================================
// Pause Event
// ===============================================================================================================

class CDiagsReceiverPauseEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverPauseEvent()
        : CDiagsReceiverEvent()
        , Rap(0)
    {}
    CDiagsReceiverPauseEvent(uint64 rap)
        : CDiagsReceiverEvent()
        , Rap(rap)
    {}
    virtual ~CDiagsReceiverPauseEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        if (Rap != 0)
        {
            DiagsLogValue64(L"Rap", Rap);
        }
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.Pause"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Pause; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 8;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint64(data, Rap);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint64(data, Rap);
        return true;
    }

public:
    uint64 Rap;
};

// ===============================================================================================================
// Play Event
// ===============================================================================================================

class CDiagsReceiverPlayEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverPlayEvent()
        : CDiagsReceiverEvent()
    {}
    virtual ~CDiagsReceiverPlayEvent() {}

public:
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.Play"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_Play; }
    __override bool DiagsIsError(void) { return false; }
};

// ===============================================================================================================
// Sendt when streaming for socket has completed and we start to wait for rendering to complete
// ===============================================================================================================

class CDiagsNearEndEvent : public CDiagsReceiverEvent
{
public:
    CDiagsNearEndEvent()
        : CDiagsReceiverEvent()
    {}
    virtual ~CDiagsNearEndEvent() {}

public:
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.NearEnd"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_NearEnd; }
    __override bool DiagsIsError(void) { return false; }
};

// ===============================================================================================================
// Clsoed caption diagnostics
// ===============================================================================================================

class CDtvCCDiags : public CDiagsReceiverEvent
{
public:
    CDtvCCDiags()
        : CDiagsReceiverEvent()
    {}
    CDtvCCDiags(bool state, bool isCC708, byte service)
        : CDiagsReceiverEvent()
        , State(state)
        , IsCC708(isCC708)
        , Service(service)
    {}
    virtual ~CDtvCCDiags() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        if (State)
        {
            DiagsLogValue(L"Type", IsCC708 ? 708 : 608);
            DiagsLogValue(L"Service", Service);
        }
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return State ? L"AV.Decoder.CC.On" : L"AV.Decoder.CC.Off"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_CC; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 3;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, State);
        DiagsPackBool(data, IsCC708);
        DiagsPackByte(data, Service);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, State);
        DiagsUnpackBool(data, IsCC708);
        DiagsUnpackByte(data, Service);
        return true;
    }

public:
    bool State;
    bool IsCC708;
    byte Service;
};

// ===============================================================================================================
// OTT stream bitrate event
// ===============================================================================================================

class CDiagsReceiverOTTBitRateEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverOTTBitRateEvent()
        : CDiagsReceiverEvent()
        , BitRate(0)
    {}
    CDiagsReceiverOTTBitRateEvent(uint32 bitRate)
        : CDiagsReceiverEvent()
        , BitRate(bitRate)
    {}
    virtual ~CDiagsReceiverOTTBitRateEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        //Base class stuff so far
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"BitRate", BitRate);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.OTT.BitRate"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_BitRate; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, BitRate);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, BitRate);
        return true;
    }

public:
    uint32 BitRate;
};

// ===============================================================================================================
// OTT stream video parameter event
// ===============================================================================================================

class CDiagsVideoDecoderParametersEvent : public CDiagsReceiverEvent
{
public:
    CDiagsVideoDecoderParametersEvent()
        : CDiagsReceiverEvent()
        , IsWmv3(false)
        , FourCC(0)
    {}
    CDiagsVideoDecoderParametersEvent(uint32 fourCC)
        : CDiagsReceiverEvent()
        , IsWmv3(false)
        , FourCC(fourCC)
    {}
    CDiagsVideoDecoderParametersEvent(uint32 fourCC, uint32 width, uint32 height, uint32 pixelAspectX, uint32 pixelAspectY)
        : CDiagsReceiverEvent()
        , IsWmv3(true)
        , FourCC(fourCC)
        , Width(width)
        , Height(height)
        , PixelAspectX(pixelAspectX)
        , PixelAspectY(pixelAspectY)
    {}
    virtual ~CDiagsVideoDecoderParametersEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogString(L"FourCC", toString(FourCC, true).c_str());
        if (IsWmv3)
        {
            DiagsLogValue(L"Width", Width);
            DiagsLogValue(L"Height", Height);
            DiagsLogValue(L"PixelAspectX", PixelAspectX);
            DiagsLogValue(L"PixelAspectY", PixelAspectY);
        }
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.OTT.VideoParams"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Decoder_VideoParameters; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 1 + 4*5;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, IsWmv3);
        DiagsPackUint32(data, FourCC);
        DiagsPackUint32(data, Width);
        DiagsPackUint32(data, Height);
        DiagsPackUint32(data, PixelAspectX);
        DiagsPackUint32(data, PixelAspectY);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, IsWmv3);
        DiagsUnpackUint32(data, FourCC);
        DiagsUnpackUint32(data, Width);
        DiagsUnpackUint32(data, Height);
        DiagsUnpackUint32(data, PixelAspectX);
        DiagsUnpackUint32(data, PixelAspectY);
        return true;
    }

public:
    //Whether it is WMV3 or WMVA/WVC1 stream
    bool   IsWmv3;
    //FourCC code and other video parameters
    uint32 FourCC;
    uint32 Width;
    uint32 Height;
    uint32 PixelAspectX;
    uint32 PixelAspectY;
};

// ===============================================================================================================
// OTT stream audio parameter event
// ===============================================================================================================

class CDiagsAudioDecoderParametersEvent : public CDiagsReceiverEvent
{
public:
    CDiagsAudioDecoderParametersEvent()
        : CDiagsReceiverEvent()
        , IsWma(false)
        , FourCC(0)
    {}
    CDiagsAudioDecoderParametersEvent(uint32 fourCC)
        : CDiagsReceiverEvent()
        , IsWma(false)
        , FourCC(fourCC)
    {}
    CDiagsAudioDecoderParametersEvent(uint32 fourCC,
                            uint32 versionNumber,
                            uint32 subband,
                            uint32 samplingRate,
                            uint16 channel,
                            uint32 bytePerSec,
                            uint32 blockSize,
                            uint16 encodeOption,
                            uint16 playerOption)
        : CDiagsReceiverEvent()
        , IsWma(true)
        , FourCC(fourCC)
        , VersionNumber(versionNumber)
        , Subband(subband)
        , SamplingRate(samplingRate)
        , AudioChannel(channel)
        , BytePerSec(bytePerSec)
        , BlockSize(blockSize)
        , EncodeOption(encodeOption)
        , PlayerOption(playerOption)
    {}
    virtual ~CDiagsAudioDecoderParametersEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogString(L"FourCC", toString(FourCC, true).c_str());
        if (IsWma)
        {
            DiagsLogValue(L"VersionNumber", VersionNumber);
            DiagsLogValue(L"Subband", Subband);
            DiagsLogValue(L"SamplingRate", SamplingRate);
            DiagsLogValue(L"AudioChannel", AudioChannel);
            DiagsLogValue(L"BytePerSec", BytePerSec);
            DiagsLogValue(L"BlockSize", BlockSize);
            DiagsLogValue(L"EncodeOption", EncodeOption);
            DiagsLogValue(L"PlayerOption", PlayerOption);
        }
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.OTT.AudioParams"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Decoder_AudioParameters; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 1+4*6+2*3;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, IsWma);
        DiagsPackUint32(data, FourCC);
        DiagsPackUint32(data, VersionNumber);
        DiagsPackUint32(data, Subband);
        DiagsPackUint32(data, SamplingRate);
        DiagsPackUint16(data, AudioChannel);
        DiagsPackUint32(data, BytePerSec);
        DiagsPackUint32(data, BlockSize);
        DiagsPackUint16(data, EncodeOption);
        DiagsPackUint16(data, PlayerOption);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, IsWma);
        DiagsUnpackUint32(data, FourCC);
        DiagsUnpackUint32(data, VersionNumber);
        DiagsUnpackUint32(data, Subband);
        DiagsUnpackUint32(data, SamplingRate);
        DiagsUnpackUint16(data, AudioChannel);
        DiagsUnpackUint32(data, BytePerSec);
        DiagsUnpackUint32(data, BlockSize);
        DiagsUnpackUint16(data, EncodeOption);
        DiagsUnpackUint16(data, PlayerOption);
        return true;
    }

public:
    //Whether it is WMA or MP3 stream
    bool   IsWma;
    //FourCC code and other audio parameters
    uint32 FourCC;
    uint32 VersionNumber;
    uint32 Subband;
    uint32 SamplingRate;
    uint16 AudioChannel;
    uint32 BytePerSec;
    uint32 BlockSize;
    uint16 EncodeOption;
    uint16 PlayerOption;
};

// ===============================================================================================================
// OTT stream discontinuity event
// ===============================================================================================================

class CDiagsReceiverOTTDiscontinuityEvent : public CDiagsReceiverEvent
{
public:
    CDiagsReceiverOTTDiscontinuityEvent()
        : CDiagsReceiverEvent()
    {}
    CDiagsReceiverOTTDiscontinuityEvent(uint32 audioDiscontinuityCount, uint32 videoDiscontinuityCount, uint32 ticks)
        : CDiagsReceiverEvent()
        , AudioDiscontinuityCount(audioDiscontinuityCount)
        , VideoDiscontinuityCount(videoDiscontinuityCount)
        , Ticks(ticks)
    {}
    virtual ~CDiagsReceiverOTTDiscontinuityEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"AudioDiscontinuityCount", AudioDiscontinuityCount);
        DiagsLogValue(L"VideoDiscontinuityCount", VideoDiscontinuityCount);
        DiagsLogValue(L"Ticks since last report", Ticks);
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.OTT.DiscontinuityStats"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_OTT_Discontinuity; }
    __override bool DiagsIsError(void) { return true; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 12;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, AudioDiscontinuityCount);
        DiagsPackUint32(data, VideoDiscontinuityCount);
        DiagsPackUint32(data, Ticks);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, AudioDiscontinuityCount);
        DiagsUnpackUint32(data, VideoDiscontinuityCount);
        DiagsUnpackUint32(data, Ticks);
        return true;
    }

public:
    uint32 AudioDiscontinuityCount;
    uint32 VideoDiscontinuityCount;
    uint32 Ticks; // the a/v discontinuity count are collected within the last 'Ticks' ms
};

// ===============================================================================================================
// When signal is lost and reqcauired by the receiver
// ===============================================================================================================

class CDiagsSignalLostEvent : public CDiagsReceiverEvent
{
public:
    CDiagsSignalLostEvent()
        : CDiagsReceiverEvent()
    {}
    CDiagsSignalLostEvent(bool isSignalLost)
        : CDiagsReceiverEvent()
        , IsSignalLost(isSignalLost)
    {}
    virtual ~CDiagsSignalLostEvent() {}

public:
    __override const WCHAR* DiagsGetEventMessage(void) { return IsSignalLost ? L"AV.SignalLost" : L"AV.SignalAcquired"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_Receiver_SignalLost; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 1;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackBool(data, IsSignalLost);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackBool(data, IsSignalLost);
        return true;
    }

public:
    bool IsSignalLost;
};

// ===============================================================================================================
// Play Ready Output Protection Level event
// ===============================================================================================================

class CDiagsPlayReadyOPLEvent : public CDiagsReceiverEvent
{
public:
    CDiagsPlayReadyOPLEvent()
        : CDiagsReceiverEvent()
    {}
    CDiagsPlayReadyOPLEvent(uint32 cgmsaLevel, uint32 macrovisionLevel, XDRM_OPL_ACTION hdcpAction, bool disableComponentVideo)
        : CDiagsReceiverEvent()
        , CGMSALevel(cgmsaLevel)
        , MacrovisionLevel(macrovisionLevel)
        , HDCPAction(hdcpAction)
        , DisableComponentVideo(disableComponentVideo)
    {}
    virtual ~CDiagsPlayReadyOPLEvent() {}

public:
    __override void DiagsGetEventData(void)
    {
        CDiagsReceiverEvent::DiagsGetEventData();

        DiagsLogValue(L"CGMS-A", CGMSALevel);
        DiagsLogValue(L"Macrovision", MacrovisionLevel);
        DiagsLogString(L"HDCP", HDCPAction != XDRM_OPL_DISABLE ? "Enabled" : "Disabled");
        DiagsLogString(L"ComponentVideo", DisableComponentVideo ? "Disabled" : "Enabled");
    }
    __override const WCHAR* DiagsGetEventMessage(void) { return L"AV.OPL"; }
    __override kDiagsEvent DiagsGetEventType(void) { return kDiagsEvent_PlayReady_OPL; }
    __override bool DiagsIsError(void) { return false; }

    __override uint16 DiagsSerializeEventDataLength(byte version)
    {
        return CDiagsReceiverEvent::DiagsSerializeEventDataLength(version) + 4*2 + 1*2;
    }
    __override void DiagsSerializeEventData(byte*& data)
    {
        CDiagsReceiverEvent::DiagsSerializeEventData(data);

        DiagsPackUint32(data, CGMSALevel);
        DiagsPackUint32(data, MacrovisionLevel);
        DiagsPackUint32(data, (uint32)HDCPAction);
        DiagsPackBool(data, DisableComponentVideo);
    }
    __override bool DiagsDeSerializeEventData(byte version, byte*& data)
    {
        CDiagsReceiverEvent::DiagsDeSerializeEventData(version, data);

        DiagsUnpackUint32(data, CGMSALevel);
        DiagsUnpackUint32(data, MacrovisionLevel);
        DiagsUnpackUint32(data, HDCPAction);
        DiagsUnpackBool(data, DisableComponentVideo);
        return true;
    }

public:
    uint32  CGMSALevel;
    uint32  MacrovisionLevel;
    XDRM_OPL_ACTION HDCPAction;
    bool    DisableComponentVideo;
};

// ===============================================================================================================
// ===============================================================================================================
