/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
#ifndef TA_MSS_TEST_H
#define TA_MSS_TEST_H

#define TA_MSS_TEST_UUID \
	{ 0x15a31c2f, 0xf8a4, 0x481f, \
		{ 0x8c, 0xe0, 0x98, 0x22, 0x18, 0x9f, 0xfa, 0xaa} }

/* The function IDs implemented in this TA */
typedef enum {
	TA_MSS_TEST_INIT			    = 0,

	TA_MSS_KT_REQUEST		= 1,
	TA_MSS_KT_RELEASE,
	TA_MSS_KT_SET,
	TA_MSS_KT_SET_IV,
	TA_MSS_KT_SET_EXT,

	TA_MSS_CRYPTO_CREATE	= 10,
	TA_MSS_CRYPTO_CONFIG,
	TA_MSS_CRYPTO_PROCESS,
	TA_MSS_CRYPTO_DESTROY,
	TA_MSS_CRYPTO_TS_CREATE,
	TA_MSS_CRYPTO_TS_CONFIG,
	TA_MSS_CRYPTO_TS_PROCESS,
	TA_MSS_CRYPTO_TS_DESTROY,

	TA_MSS_HASH_CREATE	= 20,
	TA_MSS_HASH_UPDATE,
	TA_MSS_HASH_FINAL,

	TA_MSS_MAC_CREATE,
	TA_MSS_MAC_UPDATE,
	TA_MSS_MAC_FINAL,

	TA_MSS_KL_CREATE	= 30,
	TA_MSS_KL_DESTROY,
	TA_MSS_KL_SET_SIGNATURE,
	TA_MSS_KL_START,
	TA_MSS_KL_LINK,
	TA_MSS_KL_END,

	TA_MSS_RSA_PUBLIC_ENCRYPT	= 40,
	TA_MSS_RSA_PRIVATE_DECRYPT,
	TA_MSS_RSA_PUBLIC_DECRYPT,
	TA_MSS_RSA_PRIVATE_ENCRYPT,
	TA_MSS_RSA_SIGN,
	TA_MSS_RSA_VERIFY,
	TA_MSS_MOD_CREATE,
	TA_MSS_MOD_DESTROY,
	TA_MSS_MOD_MOD,
	TA_MSS_MOD_MUL,
	TA_MSS_MOD_ADD,
	TA_MSS_MOD_SUB,
	TA_MSS_MOD_INV,
	TA_MSS_MOD_EXP,
	TA_MSS_ECP_CREATE,
	TA_MSS_ECP_DESTROY,
	TA_MSS_ECP_MUL,
	TA_MSS_ECP_ADD,

	TA_MSS_ECC_POINT_CHECK = 60,
	TA_MSS_ECDH_GEN_KEYPAIR,
	TA_MSS_ECDH_GEN_PUBKEY,
	TA_MSS_ECDH_GEN_SHAREKEY,

	TA_MSS_ECDSA_SIGN,
	TA_MSS_ECDSA_VERIFY,

	TA_MSS_SM2_SIGN,
	TA_MSS_SM2_VERIFY,
	TA_MSS_SM2_ENCRYPT,
	TA_MSS_SM2_DECRYPT,

	TA_MSS_CERT_LOCK	= 80,
	TA_MSS_CERT_UNLOCK,
	TA_MSS_CERT_EXCHANGE,
	TA_MSS_CERT_RESET,
	TA_MSS_CERT_EXPORT,
	TA_MSS_CERT_ACK,

	TA_MSS_TEST = 100,
} TA_MSS_TEST_CMD_TYPE;

#define PARAM_MSS_KT_REQUEST  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KT_RELEASE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KT_SET  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT)
#define PARAM_MSS_KT_SET_IV  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)


#define PARAM_MSS_CRYPTO_CREATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_VALUE_OUTPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CRYPTO_CONFIG  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CRYPTO_PROCESS  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_CRYPTO_DESTROY  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CRYPTO_TS_CREATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_VALUE_OUTPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CRYPTO_TS_CONFIG  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_CRYPTO_TS_PROCESS  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_CRYPTO_TS_DESTROY  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)


#define PARAM_MSS_HASH_CREATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_VALUE_OUTPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_HASH_UPDATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_HASH_FINAL  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE, TEEC_NONE)


#define PARAM_MSS_MAC_CREATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_VALUE_OUTPUT)
#define PARAM_MSS_MAC_UPDATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_MAC_FINAL  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE, TEEC_NONE)


#define PARAM_MSS_KL_CREATE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_VALUE_OUTPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KL_DESTROY  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KL_SET_SIGNATURE  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KL_START  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_KL_LINK  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE)
#define PARAM_MSS_KL_END  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)

#define PARAM_MSS_RSA_PUBLIC_ENCRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_RSA_PRIVATE_DECRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_RSA_PUBLIC_DECRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_RSA_PRIVATE_ENCRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_RSA_SIGN  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)
#define PARAM_MSS_RSA_VERIFY  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT)

#define PARAM_MSS_MOD_MOD  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_MOD_MUL  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)
#define PARAM_MSS_MOD_ADD  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)
#define PARAM_MSS_MOD_SUB  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)
#define PARAM_MSS_MOD_INV  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_MOD_EXP  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)

#define PARAM_MSS_ECC_POINT_CHECK  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_ECDH_GEN_KEYPAIR  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_ECDH_GEN_PUBKEY  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_ECDH_GEN_SHAREKEY  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)

#define PARAM_MSS_ECDSA_SIGN  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)
#define PARAM_MSS_ECDSA_VERIFY  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT)

#define PARAM_MSS_SM2_SIGN  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT)
#define PARAM_MSS_SM2_VERIFY  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT)
#define PARAM_MSS_SM2_ENCRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)
#define PARAM_MSS_SM2_DECRYPT  \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE)


#define PARAM_MSS_CERT_LOCK \
	TEEC_PARAM_TYPES(TEEC_NONE, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CERT_UNLOCK \
	TEEC_PARAM_TYPES(TEEC_NONE, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CERT_EXCHANGE \
	TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, TEEC_VALUE_OUTPUT, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CERT_RESET  \
	TEEC_PARAM_TYPES(TEEC_NONE, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CERT_EXPORT  \
	TEEC_PARAM_TYPES(TEEC_VALUE_INPUT, TEEC_NONE, TEEC_NONE, TEEC_NONE)
#define PARAM_MSS_CERT_ACK \
	TEEC_PARAM_TYPES(TEEC_NONE, TEEC_NONE, TEEC_NONE, TEEC_NONE)

#endif /*TA_MSS_TEST_H*/
