/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/

#ifndef __SYMPHONY4_RESET_H_
/*!
  to avoid to include repeatedly
  */
#define __SYMPHONY4_RESET_H_

#if defined(CONFIG_MT_CHIP_SYMPHONY4)

//#define SYMPHONY_CRM_REG_BASE SYMPHONY_IO_VA(0xBF500000)

#define SYMPHONY_CRM_REG_BASE 	mt_get_crm_base()

#else
#error "Only Symphony4 chip has CRM Registers!"
#endif

#define SYMPHONY_AO_REG_BASE SYMPHONY_IO_VA(0xBF150000)

typedef enum{
    CLKEN_OFF = 0,
    CLKEN_ON = 1,
}crm_clken_status_e;


#define BIT_MAC_AHB_RST (0x8)
#define BIT_MAC_AXI_RST (0x4)
#define BIT_EPHY_AHB_RST (0x2)
#define BIT_MAC_RST_MASK (BIT_MAC_AHB_RST | BIT_MAC_AXI_RST | BIT_EPHY_AHB_RST)
#define MAC_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x0018)

#define BIT_RMII_CLKEN (0x20)
#define BIT_MAC_CLKEN (0x10)
#define BIT_MAC_CLKEN_MASK (BIT_RMII_CLKEN | BIT_MAC_CLKEN)
#define MAC_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0x001C)



#define VAL_MAC_CLK_MODE_MII (0x0)
#define VAL_MAC_CLK_MODE_RMII (0x1)
#define POS_MAC_CLK_MODE (0x8)

#define BIT_MAC_CLK_SEL_RET (0x0)
#define BIT_MAC_CLK_SEL_REVERT_RET (0x1)
#define BIT_MAC_CLK_SEL_ORIG (0x2)
#define BIT_MAC_CLK_SEL_REVERT_ORIG (0x3)
#define MAC_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0x0050)

#define BIT_MAC_CLK_MODE_LOCK (0x1 << 17)
#define BIT_MAC_CLK_SEL_LOCK (0x1 << 16)
#define BIT_RMII_CLK_EN_LOCK (0x1 << 15)
#define BIT_MAC_CLK_EN_LOCK (0x1 << 14)
#define BIT_MAC_RST_LOCK (0x1 << 13)
#define MAC_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x0070)
#define MAC_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x0074)

#define BIT_BUS_AXI_REG_CLK_EN (0x4)
#define BIT_BUS_AXI_DEBUG_CLK_EN (0x2)
#define BIT_BUS_AXI_CLK_EN (0x1)
#define BUS_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0x8000)

#define POS_AXI_CLK_SRC_SEL 14
#define BIT_AXI_CLK_SEL (0x1 << POS_AXI_CLK_SRC_SEL)

#define BIT_AXI_CLK_SEL_MASK (0x7f)
#define POS_AXI_CLK_SEL (8)

#define BIT_APB_CLK_SEL_MASK (0xc0)
#define POS_APB_CLK_SEL (6)

#define BIT_AHB_CLK_SEL_MASK (0x38)
#define POS_AHB_CLK_SEL (3)
#define BUS_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0x8004)

#define BIT_BUS_AXICLK_SEL_LOCK (0x1 << 6)
#define BIT_BUS_APBCLK_SEL_LOCK (0x1 << 5)
#define BIT_BUS_AHBCLK_SEL_LOCK (0x1 << 4)
#define BIT_BUS_AXIREG_CLKEN_LOCK (0x1 << 2)
#define BIT_BUS_AXIDBG_CLKEN_LOCK (0x1 << 1)
#define BIT_BUS_AXI_CLKEN_LOCK (0x1 << 0)
#define BUS_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x8018)
#define BUS_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x801C)

#define APCPU_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0x8100)
#define APCPU_CLKSEL0_REG (SYMPHONY_CRM_REG_BASE + 0x8104)
#define APCPU_CLKSEL1_REG (SYMPHONY_CRM_REG_BASE + 0x8108)

#ifndef APCPU_SRSTN_REG
#define APCPU_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x810C)
#endif

#define APCPU_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x8118)
#define APCPU_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x811C)
#define BIT_APCPU_PCLKEN (0x2)
#define BIT_APCPU_CLKEN (0x1)
#define BIT_APCPU_ATCLK_CFG_FREQ_UPDATE (0x40)
#define BIT_APCPU_CLK_SWITCHMASK (0x1000)
#define BIT_BACKUP_ARMPLL_CLKSEL_MASK (0x80)
#define BIT_ATCLK_CFG_DIV_SEL_MASK (0x30)
#define BIT_APBACKUP_CLKSEL_MASK (0xF)
#define POS_APCPU_CLK_SWITCHMASK (12)
#define POS_APCPU_BACKUP_ARMPLL_CLKSEL (7)
#define POS_APCPU_ATCLK_CFG_DIV (4)
#define POS_APCPU_APBACKUP_CLK (0)

#define BIT_APCPU_NTRST_LOCK (0x1 << 17)
#define BIT_APCPU_NPOTRST_LOCK (0x1 <<16)
#define BIT_APCPU_CSRST_LOCK (0x1 <<15)
#define BIT_APCPU_AHB_LOCK (0x1 <<14)
#define BIT_APCPU_APB_LOCK (0x1 <<13)
#define BIT_MBISTRESET_LOCK (0x1 <<12)
#define BIT_I2CRESET_LOCK (0x1 <<11)
#define BIT_NDBGRESET1_LOCK (0x1 <<10)
#define BIT_NDBGRESET0_LOCK (0x1 <<9)
#define BIT_NCORERESET1_LOCK (0x1 <<8)
#define BIT_NCORERESET0_LOCK (0x1 <<7)
#define BIT_NCOREPORESET1_LOCK (0x1 <<6)
#define BIT_NCOREPORESET0_LOCK (0x1 <<5)
#define BIT_ARMPLL_CFG_LOCK (0x1 <<4)
#define BIT_ATCLK_CFG_LOCK (0x1 <<3)
#define BIT_APBACKUP_CLKSEL_LOCK (0x1 <<2)
#define BIT_APCPU_PCLKEN_LOCK (0x1 <<1)
#define BIT_APCPU_CLKEN_LOCK (0x1 <<0)
#define BIT_APCPU_CLKSEL1_1BIT_MASK (0x1)
#define BIT_APCPU_CLKSEL1_2BIT_MASK (0x3)
#define BIT_APCPU_CLKSEL1_4BIT_MASK (0xF)
#define BIT_APCPU_CLKSEL1_CTR_I_MASK (0x7)
#define BIT_APCPU_CLKSEL1_DIV_FB_MASK (0xFF)
#define BIT_APCPU_CLKSEL1_VCO_EXT (0x1)
#define BIT_APCPU_CLKSEL1_DC_TEST_EN (0x1)
#define POS_APCPU_CLKSEL1_VCO_SEL (30)
#define POS_APCPU_CLKSEL1_VCO_EXT (28)
#define POS_APCPU_CLKSEL1_DC_TEST_SEL (26)
#define POS_APCPU_CLKSEL1_CPVR_SEL (24)
#define POS_APCPU_CLKSEL1_DIV_FB (16)
#define POS_APCPU_CLKSEL1_CTR_DLY (15)
#define POS_APCPU_CLKSEL1_RST_SOFT (14)
#define POS_APCPU_CLKSEL1_DC_TEST_EN (13)
#define POS_APCPU_CLKSEL1_DC_TEST_EN1 (12)
#define POS_APCPU_CLKSEL1_DIV_FRONT (8)
#define POS_APCPU_CLKSEL1_CLK_CPU_SEL (4)
#define POS_APCPU_CLKSEL1_CAL_EN (3)
#define POS_APCPU_CLKSEL1_CTR_I (0)
#define BIT_APCPU_RESET_MASK (0x1)
#define BIT_APCPU_REST_ADD_LOCK (5)



#define AVCPU_CLKEN_REG  (SYMPHONY_CRM_REG_BASE + 0x8200)
#define AVCPU_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0x8204)
#define AVCPU_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x820C)
#define AVCPU_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x8218)
#define AVCPU_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x821C)
#define BIT_AVCPU_CLKEN (0x1)
#define BIT_AVCPU_CLKEN_LOCK (0x1 <<0)
#define BIT_AVCPU_CLKSEL_EN_LOCK (0x1 <<0)
#define BIT_AVCPU_CLKSEL_LOCK (0x1 <<1)
#define POS_AVCPU_CLK_SWITCH_MASK (3)
#define BIT_AVCPU_CLK_SWITCH_MASK_EN (0x8)
#define BIT_AVCPU_CLKSEL_EN (0x8)
#define BIT_AVCPU_LOCK_DEC_RSTN (2)
#define BIT_AVCPU_RSTN_EN (0x1)

typedef enum{
 AVCPU_AXI_SRSTN=0,
 AVCPUAHB_SRTSTN,
 AVCPUCORE_SRSTN,
 SPDMAAXI_SRSTN,
 SPDMAAHB_SRSTN,
 SPDMACORE_SRSTN
}avcpu_reset_e;

#define SYS_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0x8300)
#define SYS_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0x8304)
#define SYS_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x830C)
#define SYS_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x8318)
#define SYS_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x831C)
#define BIT_SYS_CLKEN_EN (0x1)
#define BIT_SYS_DDR_D3_DUTY_SEL_LOCK (0x1 <<11)
#define BIT_SYS_DDRPLL_PNCLK_CLKSEL_LOCK (0x1 <<10)
#define BIT_SYS_DMA_CLKSEL_LOCK (0x1 <<9)
#define POS_SYS_DDR_D3_DUTY_SEL (3)
#define POS_SYS_DDRPLL_PNCLK_CLKSEL (2)
#define BIT_SYS_DDR_D3_DUTY_SEL_MASK (0x7)
#define BIT_SYS_DDRPLL_PNCLK_CLKSEL_MASK (0xB)
#define BIT_SYS_DMA_CLKSEL_MASK (0x3)
#define BIT_SYS_LOCK_DEC_RSTN (12)
#define BIT_SYS_SRST_EN (0x1)
typedef enum{
 DDRMCAXI_CLKEN=0,
 DDRMCAHB_CLKEN,
 DDRMCCORE_CLKEN,
 DDRMCREGS_CLKEN,
 DMA_CLKEN,
 SW_TWM_CLKEN
}sys_clken_e;

typedef enum{
 DUTY_SEL_50P=0,
 DUTY_SEL_NOT_50P
}sys_ddr3_duty_e;

typedef enum{
DDRMCAXI=0,
DDRMCAHB,
DDRMCCORE,
DMAAXI,
DMAAHB,
DMACORE,
SWTIMER0,
SWTIMER1,
SWTIMER2,
SWTIMER3,
SWWDOG0,
SWWDOG1,
SWNMTXTAL,
SWMNTSOSC,
SWMNTMISC
}sys_rstn_sel_e;


#define INTF_CLKEN_REG  (SYMPHONY_CRM_REG_BASE + 0x9000)
#define INTF_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0x9004)
#define INTF_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x900C)
#define INTF_SLOCK_RSTREG (SYMPHONY_CRM_REG_BASE + 0x9010)
#define INTF_LOCK_RSTREG (SYMPHONY_CRM_REG_BASE + 0x9014)
#define INTF_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0x9018)
#define INTF_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0x901C)
#define BIT_INTF_CLKEN_MASK (0x1)
#define BIT_INTF_UART1PHY_CLKSEL_LOCK (0x1 <<20)
#define BIT_INTF_UART0PHY_CLKSEL_LOCK (0x1 <<19)
#define BIT_INTF_SDIO1_CLKSEL_LOCK (0x1 <<18)
#define BIT_INTF_SDIO0_CLKSEL_LOCK (0x1 <<17)
#define BIT_INTF_PNAND_CLKSEL_LOCK (0x1 <<16)
#define BIT_INTF_SPI1_CLKSEL_LOCK (0x1 <<15)
#define BIT_INTF_SPI0_CLKSEL_LOCK (0x1 <<14)
#define BIT_INTF_SMC_PHYCLKSEL_LOCK (0x1 <<13)
#define POS_INTF_UART1PHY_CLKSEL (10)
#define POS_INTF_UART0PHY_CLKSEL (9)
#define POS_INTF_SDIO1_CLKSEL (8)
#define POS_INTF_SDIO0_CLKSEL (7)
#define POS_INTF_PNAND_CLKSEL (5)
#define POS_INTF_SPI1_CLKSEL (3)
#define POS_INTF_SPI0_CLKSEL (1)
#define POS_INTF_SMC_PHYCLKSEL (0)
#define BIT_INTF_UART1PHY_CLKSEL_MASK (0x1 <<10)
#define BIT_INTF_UART0PHY_CLKSEL_MASK (0x1 <<9)
#define BIT_INTF_SDIO1_CLKSEL_MASK (0x1 <<8)
#define BIT_INTF_SDIO0_CLKSEL_MASK (0x1 <<7)
#define BIT_INTF_PNAND_CLKSEL_MASK (0x3 <<5)
#define BIT_INTF_SPI1_CLKSEL_MASK (0x3 <<3)
#define BIT_INTF_SPI0_CLKSEL_MASK (0x3 <<1)
#define BIT_INTF_SMC_PHYCLKSEL_MASK (0x1 <<0)
#define BIT_INTF_SRSTN_EN (0x1)
typedef enum{
INTF_CLK_CLOSED = 0,
INTF_CLK_OPEN,
}intf_clken_status_e;
typedef enum{
 SMC_CLKEN=0,
 USB0_CLKEN,
 USB1_CLKEN,
 I2C0_CLKEN,
 I2C1_CLKEN,
 I2CDEBUG_CLKEN,
 UART0_CLKEN,
 UART1_CLKEN,
 SPI0_CLKEN,
 SPI1_CLKEN,
 PNAND_CLKEN,
 SDIO0_CLKEN,
 SDIO1_CLKEN
}intf_clken_e;




typedef enum{
 INTF_SMC_RSTN=0,
 INTF_SMCPHY_RSTN,
 INTF_USB0AHB_RSTN,
 INTF_USB0AXI_RSTN,
 INTF_USB0CORE_RSTN,
 INTF_USB0PHY_RSTN,
 INTF_USB1AHB_RSTN,
 INTF_USB1AXI_RSTN,
 INTF_USB1CORE_RSTN,
 INTF_USB1PHY_RSTN,
 INTF_I2C0_RSTN,
 INTF_I2C1_RSTN,
 INTF_UART0_RSTN,
 INTF_UART1_RSTN,
 INTF_SPI0AHB_RSTN,
 INTF_SPI0CORE_RSTN,
 INTF_SPI0REG_RSTN,
 INTF_SPI1AHB_RSTN,
 INTF_SPI1AXI_RSTN,
 INTF_SPI1CORE_RSTN,
 INTF_SPI1REG_RSTN,
 INTF_PNANDAHB_RSTN,
 INTF_PNANDAXI_RSTN,
 INTF_PNANDCORE_RSTN,
 INTF_PNANDREG_RSTN,
 INTF_SDIO0AHB_RSTN,
 INTF_SDIO0AXI_RSTN,
 INTF_SDIO0CORE_RSTN,
 INTF_SDIO1AHB_RSTN,
 INTF_SDIO1AXI_RSTN,
 INTF_SDIO1CORE_RSTN
}intf_srstn_e;

#define GRA_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA100)
#define GRA_CLKSEL_REG  (SYMPHONY_CRM_REG_BASE + 0xA104)
#define GRA_SRSTN_REG  (SYMPHONY_CRM_REG_BASE + 0xA10C)
#define GRA_SLOCK_REG  (SYMPHONY_CRM_REG_BASE + 0xA118)
#define GRA_LOCK_REG  (SYMPHONY_CRM_REG_BASE + 0xA11C)

#define BIT_GRA_CORE_MASK (0x4)
#define BIT_GRA_AXI_MASK (0x2)
#define BIT_GRA_AHB_MASK (0x1)
#define BIT_GRA_CORE_LOCK (0x1 <<4)
#define BIT_GRA_AXI_LOCK (0x1 <<3)
#define BIT_GRA_AHB_LOCK (0x1 <<2)
#define BIT_GRA_CLKSEL_LOCK (0x1 <<1)
#define BIT_GRA_CLKEN_LOCK (0x1 <<0)

#define JPG_CLKEN_REG  (SYMPHONY_CRM_REG_BASE + 0xA200)
#define JPG_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA204)
#define JPG_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA20C)
#define JPG_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA218)
#define JPG_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA21C)

#define BIT_JPG_CORE_MASK (0x4)
#define BIT_JPG_AXI_MASK (0x2)
#define BIT_JPG_AHB_MASK (0x1)
#define BIT_JPG_CORE_LOCK (0x1 <<4)
#define BIT_JPG_AXI_LOCK (0x1 <<3)
#define BIT_JPG_AHB_LOCK (0x1 <<2)
#define BIT_JPG_CLKSEL_LOCK (0x1 <<1)
#define BIT_JPG_CLKEN_LOCK (0x1 <<0)

#define DISP_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA300)
#define DISP_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA304)
#define DISP_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA30C)
#define DISP_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA318)
#define DISP_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA31C)

#define BIT_DISPOSDC_CLKSEL_MASK (0x3F)
#define BIT_DISPDI_CLKSEL_MASK (0x1C7)
#define BIT_DISPCORE_CLKSEL_MASK (0x1F8)
#define BIT_DISPOSDC_MASK (0x10)
#define BIT_DISPDI_MASK (0x8)
#define BIT_DISPCORE_MASK (0x4)
#define BIT_DISPAXI_MASK (0x2)
#define BIT_DISPAHB_MASK (0x1)
#define BIT_DISPOSDC_LOCK (0x1 <<8)
#define BIT_DISPDI_LOCK (0x1 <<7)
#define BIT_DISPCORE_LOCK (0x1 <<6)
#define BIT_DISPAXI_LOCK (0x1 <<5)
#define BIT_DISPAHB_LOCK (0x1 <<4)
#define BIT_DISPOSDC_CLKSEL_LOCK (0x1 <<3)
#define BIT_DISPDI_CLKSEL_LOCK (0x1 <<2)
#define BIT_DISPCORE_CLKSEL_LOCK (0x1 <<1)
#define BIT_DISP_CLKEN_LOCK (0x1 <<0)
#define POS_DISPOSDC_CLKSEL (6)
#define POS_DISPDI_CLKSEL (3)
#define POS_DISPCORE_CLKSEL (0)


#define VDEC_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA400)
#define VDEC_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA404)
#define VDEC_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA40C)
#define VDEC_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA418)
#define VDEC_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA41C)

#define BIT_VDECCORE_CORE_MASK (0x10)
#define BIT_VDECCORE_AXI_MASK (0x8)
#define BIT_VDECCORE_MASK (0x4)
#define BIT_VDECAXI_MASK (0x2)
#define BIT_VDECAHB_MASK (0x1)

#define BIT_VDECCORE_CORE_LOCK (0x1 <<6)
#define BIT_VDECCORE_AXI_LOCK (0x1 <<5)
#define BIT_VDECCORE_LOCK (0x1 <<4)
#define BIT_VDECAXI_LOCK (0x1 <<3)
#define BIT_VDECAHB_LOCK (0x1 <<2)
#define BIT_VDEC_CLKSEL_LOCK (0x1 <<1)
#define BIT_VDEC_CLKEN_LOCK (0x1 <<0)



#define AOUT_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA500)
#define AOUT_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA504)
#define AOUT_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA50C)
#define AOUT_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA518)
#define AOUT_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA51C)

#define BIT_AOUT_SPDF_CLKEN_MASK (0x1)
#define BIT_AOUT_CLKEN_MASK (0x2)
#define BIT_AOUT_MCLK_CLKSEL_MASK (0x4)
#define BIT_AOUT_CLKSEL_MASK (0x3)
#define BIT_AOUT_ADAC_MASK (0x10)
#define BIT_AOUT_MCLK_MASK (0x8)
#define BIT_AOUTCORE_MASK (0x4)
#define BIT_AOUTAXI_MASK (0x2)
#define BIT_AOUTAHB_MASK (0x1)


#define BIT_AOUT_ADAC_LOCK (0x1 <<8)
#define BIT_AOUT_MCLK_LOCK (0x1 <<7)
#define BIT_AOUTCORE_LOCK (0x1 <<6)
#define BIT_AOUTAXI_LOCK (0x1 <<5)
#define BIT_AOUTAHB_LOCK (0x1 <<4)
#define BIT_AOUT_MCLK_CLKSEL_LOCK (0x1 <<3)
#define BIT_AOUT_CLKSEL_LOCK (0x1 <<2)
#define BIT_AOUT_SPDF_CLKEN_LOCK (0x1 <<1)
#define BIT_AOUT_CLKEN_LOCK (0x1 <<0)
#define POS_AOUT_MCLK_CLKSEL (0x2)
typedef enum{
 AOUT_MCLK_CLKSEL_DIG_MCLK=0,
 AOUT_MCLK_CLKSEL_AUDIO_DAC_CLK
}aout_mclk_clksel_e;



#define VOUT_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA600)
#define VOUT_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA604)
#define VOUT_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA60C)
#define VOUT_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA618)
#define VOUT_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA61C)

#define BIT_VOUT_HDMI_CLKEN_MASK (0x10)
#define BIT_VOUT_LCD_CLKEN_MASK (0x8)
#define BIT_VOUT_HDVENC_CLKEN_MASK (0x4)
#define BIT_VOUT_VBI_CLKEN_MASK (0x2)
#define BIT_VOUT_SDVENC_CLKEN_MASK (0x1)
#define POS_VOUT_HDMI_CLKEN (4)
#define POS_VOUT_LCD_CLKEN (3)
#define POS_VOUT_HDVENC_CLKEN (2)
#define POS_VOUT_VBI_CLKEN (1)

#define BIT_VOUT_LCD_CCLK_DIVCFG_MASK (0x7F)
#define BIT_VOUT_LCDHD_CLKSEL_MASK (0x3BF)
#define BIT_VOUT_LCD_CLKSEL_MASK (0x3C7)
#define BIT_VOUT_HDVENC_CLKSEL_MASK (0x3F8)
#define POS_VOUT_LCD_CCLK_DIVCFG (7)
#define POS_VOUT_LCDHD_CLKSEL (6)
#define POS_VOUT_LCD_CLKSEL (3)


#define BIT_VOUT_LCDC_CLK_DIVCFG_LOCK (0x1 <<8)
#define BIT_VOUT_LCDHD_CLKSEL_LOCK (0x1 <<7)
#define BIT_VOUT_LCD_CLKSEL_LOCK (0x1 <<6)
#define BIT_VOUT_HDVENC_CLKSEL_LOCK (0x1 <<5)
#define BIT_VOUT_HDMI_CLKEN_LOCK (0x1 <<4)
#define BIT_VOUT_LCD_CLKEN_LOCK (0x1 <<3)
#define BIT_VOUT_HDVENC_CLKEN_LOCK (0x1 <<2)
#define BIT_VOUT_VBI_CLKEN_LOCK (0x1 <<1)
#define BIT_VOUT_SDVENC_CLKEN_LOCK (0x1 <<0)

#define BIT_VOUT_SRSTN_MASK (0x1)
#define BIT_VOUT_SRSTN_MAP_LOCK (9)
typedef enum{
 VOUT_SRSTN_SDVENC_CORE=0,
 VOUT_SRSTN_SDVENC_AHB,
 VOUT_SRSTN_VBI,
 VOUT_SRSTN_HDVENC_AHB,
 VOUT_SRSTN_HDVENC_HD,
 VOUT_SRSTN_LCD_AHB,
 VOUT_SRSTN_LCD_CORE,
 VOUT_SRSTN_HDMI_AHB,
 VOUT_SRSTN_HDMI_CORE
}vout_srstn_sel_e;

typedef enum{
 VOUT_LCD_CCK_DIV2=0,
 VOUT_LCD_CCK_DIV4
}vout_lcd_cck_divcfg_e;


#define PNG_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA700)
#define PNG_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xA704)
#define PNG_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA70C)
#define PNG_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA718)
#define PNG_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA71C)



#define BIT_PNGCORE_LOCK (0x1 <<4)
#define BIT_PNGAXI_LOCK (0x1 <<3)
#define BIT_PNGAHB_LOCK (0x1 <<2)
#define BIT_PNG_CLKSEL_LOCK (0x1 <<1)
#define BIT_PNG_CLKEN_LOCK (0x1 <<0)
#define BIT_PNG_CLKEN_MASK (0x1)

#define BIT_PNGCORE_MASK (0x3)
#define BIT_PNGAXI_MASK (0x5)
#define BIT_PNGAHB_MASK (0x6)


#define DAI_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xA800)
#define DAI_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xA80C)
#define DAI_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA818)
#define DAI_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xA81C)

#define BIT_DAI_CLKEN_LOCK (0x1 <<0)
#define BIT_DAI_LOCK_MAP_SRSTN (1)
#define BIT_DAI_SRSTN_MASK (1)
typedef enum{
 DAI_SRSTN_AHB=0,
 DAI_SRSTN_AXI,
 DAI_SRSTN_TX,
 DAI_SRSTN_RX,
 DAI_SRSTN_PDM,
 DAI_SRSTN_DAC,
 DAI_SRSTN_ADC
}dai_srstn_e;

#define TSI_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xB000)
#define TSI_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xB004)
#define TSI_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xB00C)
#define TSI_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xB018)
#define TSI_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xB01C)

#define BIT_TS3_CLKSEL_LOCK (0x1 <<5)
#define BIT_TS2_CLKSEL_LOCK (0x1 <<4)
#define BIT_TS1_CLKSEL_LOCK (0x1 <<3)
#define BIT_TS0_CLKSEL_LOCK (0x1 <<2)
#define BIT_TSI_CLKSEL_LOCK (0x1 <<1)
#define BIT_TSI_CLKEN_LOCK (0x1 <<0)

#define BIT_TS3_CLKSEL_MASK (0x7F)
#define BIT_TS2_CLKSEL_MASK (0x19F)
#define BIT_TS1_CLKSEL_MASK (0x1E7)
#define BIT_TS0_CLKSEL_MASK (0x1FB)
#define BIT_TSI_CLKSEL_MASK (0x1FC)

#define POS_TS3_CLKSEL (7)
#define POS_TS2_CLKSEL (5)
#define POS_TS1_CLKSEL (3)
#define POS_TS0_CLKSEL (2)
#define BIT_TSI_SRSTN_MAP_LOCK (6)
#define BIT_TSI_SRSTN_MASK (0x1)


typedef enum{
 TSI_SRSTN_AHB=0,
 TSI_SRSTN_AXI,
 TSI_SRSTN_CORE,
 TSI_SRSTN_TS0,
 TSI_SRSTN_TS1,
 TSI_SRSTN_TS2,
 TSI_SRSTN_TS3,
 TSI_SRSTN_SF,
 TSI_SRSTN_TRPP,
 TSI_SRSTN_SWTSI,
 TSI_SRSTN_TSPOOL,
 TSI_SRSTN_DEMUX,
 TSI_SRSTN_SWTSI_AXI,
 TSI_SRSTN_TRPP_AXI,
 TSI_SRSTN_SF_AXI,
 TSI_SRSTN_AVSYNC_SYS,
 TSI_SRSTN_AVSYNC_PCR,
 TSI_SRSTN_AVSYNC_AHB,
 TSI_SRSTN_T2MI,
 TSI_SRSTN_SF_REG,
 TSI_SRSTN_TRPP_REG,
}tsi_srstn_e;


#define CI_CLKEN_REG  (SYMPHONY_CRM_REG_BASE + 0xB100)
#define CI_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xB104)
#define CI_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xB10C)
#define CI_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xB118)
#define CI_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xB11C)

#define BIT_CI_CORE_LOCK (0x1 <<4)
#define BIT_CI_AHB_LOCK (0x1 <<3)
#define BIT_CI_TSIN_CLKSEL_LOCK (0x1 <<2)
#define BIT_CI_CLKSEL_LOCK (0x1 <<1)
#define BIT_CI_CLKEN_LOCK (0x1 <<0)

#define BIT_CI_TSIN_CLKSEL_MASK (0x1)
#define BIT_CI_CLKSEL_MASK (0xE)
#define BIT_CI_CORE_MASK (0x2)
#define BIT_CI_AHB_MASK (0x1)
#define POS_CI_TSIN_CLKSEL (0x1)


#define SECURE_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xC000)
#define SECURE_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xC004)
#define SECURE_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0xC00C)
#define SECURE_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xC01C)
#define SECURE_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xC018)

#define BIT_SECURE_M2M_CIPHER_CLKSEL_LOCK (0x1<<9)
#define BIT_SECURE_CLKSEL_LOCK (0x1<<8)
#define BIT_SECURE_SRSTN_MAP_LOCK (10)
#define BIT_SECURE_CLKEN_MASK (0x1)
#define BIT_SECURE_SRSTN_MASK (0x1)
#define BIT_SECURE_M2M_CIPHER_CLKSEL_MASK (0xC)
#define BIT_SECURE_CKSEL_MASK (0x3)
#define POS_SECURE_M2M_CIPHER_CLKSEL (2)

typedef enum{
 SECURE_SECMISC_CLKEN=0,
 SECURE_KDF_CLKEN,
 SECURE_KL_CLKEN,
 SECURE_SECHD0_CLKEN,
 SECURE_KT_CLKEN,
 SECURE_GLITCHDET_CLKEN,
 SECURE_PKA_CLKEN,
 SECURE_M2M_CLKEN
}secure_clken_e;


typedef enum{
 SECURE_SRSTN_KL=0,
 SECURE_SRSTN_SECHD0,
 SECURE_SRSTN_KT_CORE,
 SECURE_SRSTN_KT_IBUS,
 SECURE_SRSTN_GLITCH_DET,
 SECURE_SRSTN_PKA_CORE,
 SECURE_SRSTN_PKA_IBUS,
 SECURE_SRSTN_M2M_CORE,
 SECURE_SRSTN_M2M_AXI,
 SECURE_SRSTN_M2M_AHB,
 SECURE_SRSTN_M2M_CIPHER,
 SECURE_SRSTN_DS
}secure_srstn_e;

#define IFCP_CLKEN_REG (SYMPHONY_CRM_REG_BASE + 0xC800)
#define IFCP_CLKSEL_REG (SYMPHONY_CRM_REG_BASE + 0xC804)
#define IFCP_GLB_SRSTN_REG (SYMPHONY_CRM_REG_BASE + 0x0034)
#define SHAREREG_VSCPU_RST_CTRL_REG SYMPHONY_IO_VA(0xBF4B4050)
#define IFCP_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xC818)
#define IFCP_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xC81C)

#define BIT_IFCP_CRYPTO_CLKSEL_LOCK (0x1<<3)
#define BIT_IFCP_SYS_CLKSEL_LOCK (0x1<<2)
#define BIT_IFCP_KLM_CLKEN_LOCK (0x1<<1)
#define BIT_IFCP_CRYPTO_CLKEN_LOCK (0x1<<0)
#define BIT_VSCPU_CLK_SWITCHMASK_MASK (0x1F)
#define BIT_IFCP_CRYPTO_CLKSEL_MASK (0x18)
#define BIT_IFCP_SYS_CLKSEL_MASK (0x7)
#define BIT_IFCP_KLM_CLKEN_MASK (0x2)
#define BIT_IFCP_CRYPTO_CLKEN_MASK (0x1)
#define BIT_IFCP_SRSTN_LOCK (0x10000)
#define BIT_IFCP_SRSTN_MASK (0xFFFF)
#define POS_IFCP_SRSTN (16)
#define POS_IFCP_KLM_CLKEN (0x1)
#define POS_VSCPU_CLK_SWITCH (5)
#define POS_IFCP_CRYPTO_CLKSEL (3)
#define BIT_SHAREREG_VSCPU_RST_CTRL_REG_MASK 1

typedef enum{
 VSCPU_CLK_SWICTCH_IMMEDIATELY=0,
 VSCPU_CLK_SWICTCH_IDLE
}vscpu_clk_switch_mask_e;


typedef enum{
 VSCPU_SEC_RSTN=0,
 IFCP_KLM_SRSTN=1,
 IFCP_CRYPTO_SRSTN=4,
 IFCP_CRYPTO_SRSTN1=5,
 IFCP_CRYPTO_SRSTN2=6,
 IFCP_KLM_SRSTN0=7,
 IFCP_KLM_SRSTN1=8,
 IFCP_CRYPTOFIFO_SRSTN=9
}ifcp_srstn_e;

#define EXPRST_CFG_REG (SYMPHONY_CRM_REG_BASE + 0xF004)
#define EXPWDOG0_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF008)
#define EXPWDOG1_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF00C)
#define EXPWDOG2_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF010)
#define EXPWDOG3_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF014)
#define EXPWDOG4_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF018)
#define EXPWDOG5_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF01C)
#define EXPWDOG6_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF020)
#define EXPWDOG7_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF024)
#define EXPWDOG8_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF028)
#define EXPWDOG9_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF02C)
#define EXPWDOG10_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF030)
#define EXPWDOG11_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF034)
#define EXPWDOG12_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF038)
#define EXPWDOG13_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF03C)
#define EXPWDOG14_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF040)
#define EXPWDOG15_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF044)
#define EXPWDOG16_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF048)
#define EXPWDOG17_RSTTIMERS (SYMPHONY_CRM_REG_BASE + 0xF04C)

typedef enum{
 REG_RST_CFG_REQ=0,
 REG_RST_CFG_REQ_EN=1,
}reg_rst_cfg_req_e;


#define TOPCLK_CTRL0_REG (SYMPHONY_CRM_REG_BASE + 0xF800)
#define TOPCLK_CTRL1_REG (SYMPHONY_CRM_REG_BASE + 0xF804)
#define TOPCLK_CTRL2_REG (SYMPHONY_CRM_REG_BASE + 0xF808)
#define TOPCLK_CTRL3_REG (SYMPHONY_CRM_REG_BASE + 0xF80C)
#define TOPCLK_CTRL4_REG (SYMPHONY_CRM_REG_BASE + 0xF810)
#define TOPCLK_CTRL5_REG (SYMPHONY_CRM_REG_BASE + 0xF814)
#define TOPCLK_CTRL6_REG (SYMPHONY_CRM_REG_BASE + 0xF818)
#define TOPCLK_CTRL0_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF81C)
#define TOPCLK_CTRL0_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF820)
#define TOPCLK_CTRL1_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF824)
#define TOPCLK_CTRL1_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF828)
#define TOPCLK_CTRL2_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF82C)
#define TOPCLK_CTRL2_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF830)
#define TOPCLK_CTRL3_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF834)
#define TOPCLK_CTRL3_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF838)
#define TOPCLK_CTRL4_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF83C)
#define TOPCLK_CTRL4_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF840)
#define TOPCLK_CTRL5_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF844)
#define TOPCLK_CTRL5_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF848)
#define TOPCLK_CTRL6_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF84C)
#define TOPCLK_CTRL6_LOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF850)



#define SYS_CLK_HW_EN (SYMPHONY_CRM_REG_BASE + 0xF900)
#define SYS_CLK_SW_EN (SYMPHONY_CRM_REG_BASE + 0xF904)

typedef enum{
 SYS_CLK_HW_SW_CLOSED=0,
 SYS_CLK_HW_SW_OPEN=2,
}sys_clk_hw_sw_spdma_e;



#define WDOGEXP_CFG0_REG (SYMPHONY_CRM_REG_BASE + 0xFA00)
#define WDOGEXP_CFG1_REG (SYMPHONY_CRM_REG_BASE + 0xFA04)
#define RSTSTAT_CLR_REG (SYMPHONY_CRM_REG_BASE + 0xFA08)
#define RSTSTAT_REG (SYMPHONY_CRM_REG_BASE + 0xFA0C)
#define BIT_RSTSTATE_MASK (0xFFFF)


#define DFT_CFG_REG (SYMPHONY_CRM_REG_BASE + 0xFC00)
#define BIT_DFT_APCPU_MBIST_EN_MASK (0x1)
#define BIT_DFT_MBIST_MODE_MASK (0x2)

typedef enum{
 DFT_APCPU_MBIST_CLOSED=0,
 DFT_APCPU_MBIST_OPEN=2,
}dft_apcpu_mbist_en_e;

typedef enum{
 DFT_MBIST_MODE_CLOSED=0,
 DFT_MBIST_MODE_OPEN=2,
}dft_mbist_mode_e;


#define AO_LPMCLK_REG (SYMPHONY_AO_REG_BASE + 0x3800)
#define AO_LPMRST_REG (SYMPHONY_AO_REG_BASE + 0x3804)
#define AO_IRDACLK_REG (SYMPHONY_AO_REG_BASE + 0x3808)
#define AO_IRDARST_REG (SYMPHONY_AO_REG_BASE + 0x380C)
#define AO_RTCRST_REG (SYMPHONY_AO_REG_BASE + 0x3814)
#define AO_LEDKBCLK_REG (SYMPHONY_AO_REG_BASE + 0x3818)
#define AO_LEDKBRST_REG (SYMPHONY_AO_REG_BASE + 0x381C)
#define AO_GPIOCLK_REG (SYMPHONY_AO_REG_BASE + 0x3820)
#define AO_GPIORST_REG (SYMPHONY_AO_REG_BASE + 0x3824)
#define AO_KADCCLK_REG (SYMPHONY_AO_REG_BASE + 0x3828)
#define AO_KADCRST_REG (SYMPHONY_AO_REG_BASE + 0x382C)
#define AO_ANACLK_REG (SYMPHONY_AO_REG_BASE + 0x3830)
#define AO_FPI2CCLK_REG (SYMPHONY_AO_REG_BASE + 0x3838)
#define AO_FPI2CRST_REG (SYMPHONY_AO_REG_BASE + 0x383C)
#define AO_FPSPICLK_REG (SYMPHONY_AO_REG_BASE + 0x3840)
#define AO_FPSPIRST_REG (SYMPHONY_AO_REG_BASE + 0x3844)
#define AO_RECRAMCLK_REG (SYMPHONY_AO_REG_BASE + 0x3848)
#define AO_PINMUXCLK_REG (SYMPHONY_AO_REG_BASE + 0x3850)
#define AO_PINMUXRST_REG (SYMPHONY_AO_REG_BASE + 0x3854)
#define AO_TIMERCLK_REG (SYMPHONY_AO_REG_BASE + 0x3858)
#define AO_TIMERRST_REG (SYMPHONY_AO_REG_BASE + 0x385C)
#define AO_MNTRST_REG (SYMPHONY_AO_REG_BASE + 0x3864)
#define AO_MAILBOXCLK_REG (SYMPHONY_AO_REG_BASE + 0x3868)
#define AO_MAILBOXRST_REG (SYMPHONY_AO_REG_BASE + 0x386C)
#define AO_CECCLK_REG (SYMPHONY_AO_REG_BASE + 0x3870)
#define AO_CECRST_REG (SYMPHONY_AO_REG_BASE + 0x3874)
#define AO_AVSCLK_REG (SYMPHONY_AO_REG_BASE + 0x3878)
#define AO_AVSRST_REG (SYMPHONY_AO_REG_BASE + 0x387C)
#define AO_AGTIMERCLK_REG (SYMPHONY_AO_REG_BASE + 0x3880)
#define AO_AGTIMERRST_REG (SYMPHONY_AO_REG_BASE + 0x3884)
#define AO_AOMCUCLK_REG (SYMPHONY_AO_REG_BASE + 0x3878)
#define AO_WDOGRST_REG (SYMPHONY_AO_REG_BASE + 0x388C)
#define XTAL_CLKSEL_REG (SYMPHONY_AO_REG_BASE + 0x3890)
#define AOCRM_SLOCK_REG (SYMPHONY_CRM_REG_BASE + 0xF840)
#define AOCRM_LOCK_REG (SYMPHONY_AO_REG_BASE + 0xF844)

#define BIT_AO_XTALSEL_LOCK (0x1<<19)
#define BIT_AO_WDOG_LOCK (0x1<<18)
#define BIT_AO_AOMCU_LOCK (0x1<<17)
#define BIT_AO_AGTIMER_LOCK (0x1<<16)
#define BIT_AO_AVS_LOCK (0x1<<15)
#define BIT_AO_CEC_LOCK (0x1<<14)
#define BIT_AO_MAILBOX_LOCK (0x1<<13)
#define BIT_AO_MNT_LOCK (0x1<<12)
#define BIT_AO_TIMER_LOCK (0x1<<11)
#define BIT_AO_PINMUX_LOCK (0x1<<10)
#define BIT_AO_RECRAM_LOCK (0x1<<9)
#define BIT_AO_FPSPI_LOCK (0x1<<8)
#define BIT_AO_FPI2C_LOCK (0x1<<7)
#define BIT_AO_ANA_LOCK (0x1<<6)
#define BIT_AO_KADC_LOCK (0x1<<5)
#define BIT_AO_GPIO_LOCK (0x1<<4)
#define BIT_AO_LEDKB_LOCK (0x1<<3)
#define BIT_AO_RTC_LOCK (0x1<<2)
#define BIT_AO_IRDA_LOCK (0x1<<1)
#define BIT_AO_LPM_LOCK (0x1<<0)

#define BIT_AO_RESET (0x0)
#define BIT_AO_RESET_RELEASE (0x1)
#define BIT_AO_FPSPIREG_SRSTN_MASK (0x2)
#define BIT_AO_FPSPI_SRSTN_MASK (0x1)
#define BIT_AO_MNTSOSC_SRSTN_MASK (0x2)
#define BIT_AO_MNTXTAL_SRSTN_MASK (0x1)

#define BIT_AO_XTAL_CLKSEL_MASK (0x1)

#if 0
int crm_module_reset(mt_u32 mod_id);
int crm_module_clk_enable(mt_u32 mod_id,MT_BOOL onoff);
int crm_module_clk_is_enabled(mt_u32 mod_id);
int crm_module_clk_set(mt_u32 m_id, mt_u32 type);
int crm_module_clk_get(mt_u32 m_id);
void crm_module_info_dump(void);
#endif
#endif  /*! __SYMPHONY_RESET_H_ */


