/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2018 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
/********************************************************************************************
  File Name     : drv_disp_ioctl.h
  Version       : Initial Draft
  Author        : Montage multimedia software group
  Created       : 2015/12/25
  Description   :
  History       :
  1.Date        : 2015/12/25
    Author      : 
    Modification: 

*********************************************************************************************/

#ifndef __DRV_DISP_IOCTL_H__
#define __DRV_DISP_IOCTL_H__

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

#include "mt_type.h"
#include "mt_drv_video.h"
#include "mt_drv_disp.h"

typedef struct mtDISP_ATTACH_S
{
    MT_DRV_DISPLAY_E   enMaster;
    MT_DRV_DISPLAY_E   enSlave;
}DISP_ATTACH_S;

typedef struct mtDISP_ENABLE_S
{
    MT_DRV_DISPLAY_E  enDisp;
    MT_BOOL        bEnable;
}DISP_ENABLE_S;

typedef struct mtDISP_SET_INTF_S
{
   MT_DRV_DISPLAY_E    enDisp;
   MT_DRV_DISP_INTF_S  stIntf;
}DISP_SET_INTF_S;
typedef struct mtDISP_PRIV_PARA_S
{
   MT_DRV_DISPLAY_E    enDisp;
   struct display_arg  Dis_IO_arg;
}DISP_PRIV_PARA_S;

typedef struct mtDISP_GET_INTF_S
{
   MT_DRV_DISPLAY_E    enDisp;
   mt_u32              u32IntfNum;
   MT_DRV_DISP_INTF_S *pstIntf;
   mt_s32              Revd;
}DISP_GET_INTF_S;

typedef struct mtDISP_FORMAT_S
{
    MT_DRV_DISPLAY_E  enDisp;
    MT_DRV_DISP_STEREO_MODE_E enStereo;
    MT_DRV_DISP_FMT_E enFormat;
}DISP_FORMAT_S;

typedef struct mtDISP_TIMING_S
{
    MT_DRV_DISPLAY_E           enDisp;
    MT_DRV_DISP_TIMING_S  stTimingPara;
}DISP_TIMING_S;


typedef struct mtDISP_R_EYE_FIRST_S
{
    MT_DRV_DISPLAY_E  enDisp;
    MT_BOOL  bREFirst;
}DISP_R_EYE_FIRST_S;

typedef struct mtDISP_VIRTSCREEN_S
{
    MT_DRV_DISPLAY_E  enDisp;
    mt_rect_s stVirtScreen;
}DISP_VIRTSCREEN_S;


typedef struct mtDISP_SCREENOFFSET_S
{
    MT_DRV_DISPLAY_E  enDisp;
    MT_DRV_DISP_OFFSET_S stScreenOffset;
}DISP_SCREENOFFSET_S;


typedef struct mtDISP_ZORDER_S
{
    MT_DRV_DISPLAY_E    enDisp;
    MT_DRV_DISP_ZORDER_ABS_E   ZFlag;
}DISP_ZORDER_S;

typedef struct mtDISP_ORDER_S
{
    MT_DRV_DISPLAY_E    enDisp;
    MT_DRV_DISP_LAYER_E Layer;
    mt_u32              Order;
}DISP_ORDER_S;

typedef struct mtDISP_BGC_S
{
    MT_DRV_DISPLAY_E enDisp;
    MT_DRV_DISP_COLOR_S stBgColor;
}DISP_BGC_S;

typedef struct mtDISP_COLOR_S
{
    MT_DRV_DISPLAY_E enDisp;
    MT_DRV_DISP_COLOR_SETTING_S stColor;
}DISP_COLOR_S;

typedef struct mtDISP_SCREEN_S
{
    MT_DRV_DISPLAY_E enDisp;
    mt_rect_s stRect;
}DISP_SCREEN_S;

typedef struct mtDISP_CSC_S
{
    MT_DRV_DISPLAY_E enDisp;
    mt_u32           CscValue;
}DISP_CSC_S;


typedef struct mtDISP_ALG_S
{
    MT_DRV_DISPLAY_E      enDisp;
    MT_DRV_DISP_ALG_CFG_S stAlg;
}DISP_ALG_S;


typedef struct mtDISP_VBI_S
{
    mt_handle hVbi;
    MT_DRV_DISP_VBI_DATA_S stVbiData;
}DISP_VBI_S;

typedef struct mtDISP_VBI_CREATE_CHANNEL_S
{
    MT_DRV_DISPLAY_E      enDisp;
    MT_DRV_DISP_VBI_CFG_S  stCfg;
    mt_handle hVbi;
}DISP_VBI_CREATE_CHANNEL_S;

typedef struct mtDISP_WSS_S
{
    MT_DRV_DISPLAY_E      enDisp;
    MT_DRV_DISP_WSS_DATA_S  WssData;
}DISP_WSS_S;

typedef struct mtDISP_MCRVSN_S
{
    MT_DRV_DISPLAY_E          enDisp;
    MT_DRV_DISP_MACROVISION_E eMcrvsn;
    mt_void *pPriv;
}DISP_MCRVSN_S;

typedef struct mtDISP_HDMIINF_S
{
    MT_DRV_DISPLAY_E        enDisp;
    MT_DRV_DISP_HDMI_S HDMIInf;
}DISP_HDMIINF_S;

/* CGMS parameter struct */
typedef struct mtDISP_CGMS_S
{
    MT_DRV_DISPLAY_E        enDisp;
    MT_DRV_DISP_CGMSA_CFG_S stCgmsCfg;
}DISP_CGMS_S;


/* CGMS parameter struct */
typedef struct mtDISP_OUTRECT_S
{
    MT_DRV_DISPLAY_E          enDisp;
    mt_rect_s          stOutRectCfg;
}DISP_OUTRECT_S;

typedef struct mtDISP_TCCSC_S
{
    MT_DRV_DISPLAY_E        enDisp;
    MT_BOOL        bEnable;
}DISP_TCCSC_S;

typedef struct mtDISP_ASPECT_RATIO_S
{
    MT_DRV_DISPLAY_E        enDisp;
    mt_u32 u32ARHori;
    mt_u32 u32ARVert;
}DISP_ASPECT_RATIO_S;

typedef struct mtDISP_CAST_CREATE_S
{
    MT_DRV_DISPLAY_E enDisp;
    MT_DRV_DISP_CAST_CFG_S stCfg;
    mt_handle hCast;
}DISP_CAST_CREATE_S;

typedef struct mtDISP_CAST_DESTROY_S
{
    mt_handle hCast;
}DISP_CAST_DESTROY_S;

typedef struct mtDISP_CAST_ENABLE_S
{
    mt_handle hCast;
    MT_BOOL bEnable;
}DISP_CAST_ENABLE_S;

typedef struct mtDISP_CAST_FRAME_S
{
    mt_handle hCast;
    MT_DRV_VIDEO_FRAME_S stFrame;
}DISP_CAST_FRAME_S;

typedef struct mtDISP_SNAPSHOT_FRAME_S
{
    MT_DRV_DISPLAY_E enDispLayer;
    MT_DRV_VIDEO_FRAME_S stFrame;
}DISP_SNAPSHOT_FRAME_S;

typedef enum mtDISP_EXT_ATTACH_TYPE_E
{
    EXT_ATTACH_TYPE_SRC = 0,
    EXT_ATTACH_TYPE_SINK,
    EXT_ATTACH_TYPE_BUTT
}DISP_EXT_ATTACH_TYPE_E;

typedef struct mtDISP_EXT_ATTACH_S
{
    DISP_EXT_ATTACH_TYPE_E enType;
    mt_handle hCast;
    mt_handle hMutual;
}DISP_EXT_ATTACH_S;

typedef struct mtDISP_CAST_EXT_ATTR_S
{
    mt_handle hCast;
    MT_DRV_DISP_Cast_Attr_S castAttr;
}DISP_CAST_EXT_ATTR_S;

typedef struct mtDISP_VIDEO_SIZE_S
{
    mt_u32 u32Width;
    mt_u32 u32Height;
}DISP_VIDEO_SIZE_S;

typedef struct mtDISP_ALPHA_S
{
    MT_DRV_DISPLAY_E enDisp;
    mt_u32           u32Alpha;
}DISP_ALPHA_S;

typedef struct mtDISP_SL_HDR_PARA_S
{
    MT_DRV_DISPLAY_E enDisp;
    mt_bool          transparent_mode;
    mt_u32           u32Display_Brightness;
    mt_u32           u32Tuning_level;
    mt_u32           u32Display_OETF;
}DISP_SL_HDR_PARA_S;

typedef struct mtDISP_SHOW_DS_S
{
    mt_bool         bStillLayer;
    mt_u32          bShowDsPic;
}DISP_SHOW_DS_S;

typedef enum mtIOC_DISP_E
{
    IOC_DISP_ATTACH = 0,
    IOC_DISP_DETACH,

    IOC_DISP_OPEN,
    IOC_DISP_CLOSE,

    IOC_DISP_SET_ENABLE,
    IOC_DISP_GET_ENABLE,

    IOC_DISP_ADD_INTF, //6
    IOC_DISP_DEL_INTF,
    IOC_DISP_GET_INTF,

    IOC_DISP_SET_FORMAT, //9
    IOC_DISP_GET_FORMAT,

    IOC_DISP_SET_R_EYE_FIRST,
    IOC_DISP_GET_R_EYE_FIRST,

    IOC_DISP_SET_VIRTSCREEN,
    IOC_DISP_GET_VIRTSCREEN,

    IOC_DISP_SET_SCREENOFFSET,
    IOC_DISP_GET_SCREENOFFSET,

    IOC_DISP_SET_DAC,
    IOC_DISP_GET_DAC,

    IOC_DISP_SET_TIMING,
    IOC_DISP_GET_TIMING,

    IOC_DISP_SET_ZORDER,
    IOC_DISP_GET_ORDER,

    IOC_DISP_SET_BGC,
    IOC_DISP_GET_BGC,

    IOC_DISP_SET_SCREEN,
    IOC_DISP_GET_SCREEN,
    
    IOC_DISP_SET_SMALLWINDOW,
    IOC_DISP_GET_SMALLWINDOW,
	IOC_DISP_SET_COLOR,
    IOC_DISP_GET_COLOR,
	
	IOC_DISP_SET_BRIGHT,
    IOC_DISP_GET_BRIGHT,

    IOC_DISP_SET_CONTRAST,
    IOC_DISP_GET_CONTRAST,

    IOC_DISP_SET_SATURATION,
    IOC_DISP_GET_SATURATION,

    IOC_DISP_SET_HUE,
    IOC_DISP_GET_HUE,

    IOC_DISP_SET_ALG,
    IOC_DISP_GET_ALG,

    IOC_DISP_SET_LAYER_SHOW,
    IOC_DISP_CREATE_VBI_CHANNEL,
    IOC_DISP_DESTROY_VBI_CHANNEL,
    IOC_DISP_SEND_VBI,
    IOC_DISP_SET_WSS,

    IOC_DISP_SET_MCRVSN,
    IOC_DISP_GET_MCRVSN,

    IOC_DISP_SET_HDMIINF,
    IOC_DISP_GET_HDMIINF,

    IOC_DISP_SET_CGMS,
    IOC_DISP_SET_DISP_SCREEN,
    IOC_DISP_GET_DISP_SCREEN,

    IOC_DISP_SET_DEV_RATIO,
    IOC_DISP_GET_DEV_RATIO,

    IOC_DISP_ACQUIRE_SNAPSHOT,
    IOC_DISP_RELEASE_SNAPSHOT,


    IOC_DISP_CREATE_CAST,
    IOC_DISP_DESTROY_CAST,
    IOC_DISP_SET_LOWDELAY_ENABLE,
    IOC_DISP_SET_CAST_ENABLE,
    IOC_DISP_GET_CAST_ENABLE,
    IOC_DISP_ACQUIRE_CAST_FRAME,
    IOC_DISP_RELEASE_CAST_FRAME,
    IOC_DISP_EXT_ATTACH,
    IOC_DISP_EXT_DEATTACH,
    IOC_DISP_SET_CASTATTR,
    IOC_DISP_GET_CASTATTR,
    IOC_DISP_SUSPEND,
    IOC_DISP_RESUME,
    IOC_DISP_FORCESET_DAC_ENABLE,
    IOC_DISP_SET_PARA,
    IOC_DISP_GET_PARA,
    IOC_DISP_SET_PPMODE,
    IOC_DISP_SET_LAYER_ENABLE,
    IOC_DISP_GET_LAYER_ENABLE,
    IOC_DISP_SET_LAYER_ALPHA,
    IOC_DISP_GET_LAYER_ALPHA,

	IOC_DISP_GET_VIDEO_SIZE,
    IOC_DISP_SET_CSC_ENABLE,
    IOC_DISP_SET_DENOISE_ENABLE,
    IOC_DISP_SET_AFD_ENABLE,
    IOC_DISP_SET_HDVIDEO_ENABLE,
    IOC_DISP_SET_SDVIDEO_ENABLE,
    IOC_DISP_SET_VDAC_ONOFF,
    IOC_DISP_SET_TRICK_MODE,
    IOC_DISP_SET_UNBLANK_MODE,
    IOC_DISP_SET_DI_ENABLE,
    IOC_DISP_SET_TVCAP,
    IOC_DISP_SET_SL_HDR_PARA,
    IOC_DISP_GET_SlHDR_VER,
	IOC_DISP_SET_SD_ENC_PQ_PARA,
    IOC_DISP_SET_COLORBAR,
    IOC_DISP_SET_OUTPUT_ENABLE,	
    IOC_DISP_RESET_HARDWARE,
    IOC_DISP_SET_SD_SCALER_ENABLE,
    IOC_DISP_DUMP_SCALER_TO_OSD,
	IOC_DISP_FORCE_SHOW_DS_PIC,
    IOC_DISP_SET_BUTT
}IOC_DISP_E;

#define CMD_DISP_ATTACH            _IOW(MT_ID_DISP, IOC_DISP_ATTACH, DISP_ATTACH_S)
#define CMD_DISP_DETACH            _IOW(MT_ID_DISP, IOC_DISP_DETACH, DISP_ATTACH_S)

#define CMD_DISP_OPEN              _IOW(MT_ID_DISP, IOC_DISP_OPEN, MT_DRV_DISPLAY_E)
#define CMD_DISP_CLOSE             _IOW(MT_ID_DISP, IOC_DISP_CLOSE, MT_DRV_DISPLAY_E)

#define CMD_DISP_SET_ENABLE        _IOW(MT_ID_DISP, IOC_DISP_SET_ENABLE, DISP_ENABLE_S)
#define CMD_DISP_GET_ENABLE        _IOWR(MT_ID_DISP, IOC_DISP_GET_ENABLE, DISP_ENABLE_S)

#define CMD_DISP_ADD_INTF          _IOW(MT_ID_DISP, IOC_DISP_ADD_INTF, DISP_SET_INTF_S)
#define CMD_DISP_DEL_INTF          _IOW(MT_ID_DISP, IOC_DISP_DEL_INTF, DISP_SET_INTF_S)
#define CMD_DISP_GET_INTF          _IOWR(MT_ID_DISP, IOC_DISP_GET_INTF, DISP_GET_INTF_S)

#define CMD_DISP_SET_FORMAT        _IOW(MT_ID_DISP, IOC_DISP_SET_FORMAT, DISP_FORMAT_S)
#define CMD_DISP_GET_FORMAT        _IOWR(MT_ID_DISP, IOC_DISP_GET_FORMAT, DISP_FORMAT_S)

#define CMD_DISP_SET_R_E_FIRST     _IOW(MT_ID_DISP, IOC_DISP_SET_R_EYE_FIRST, DISP_R_EYE_FIRST_S)
#define CMD_DISP_GET_R_E_FIRST     _IOWR(MT_ID_DISP, IOC_DISP_GET_R_EYE_FIRST, DISP_R_EYE_FIRST_S)


#define CMD_DISP_SET_VIRTSCREEN     _IOW(MT_ID_DISP, IOC_DISP_SET_VIRTSCREEN, DISP_VIRTSCREEN_S)
#define CMD_DISP_GET_VIRTSCREEN     _IOWR(MT_ID_DISP, IOC_DISP_GET_VIRTSCREEN, DISP_VIRTSCREEN_S)

#define CMD_DISP_SET_SCREENOFFSET     _IOW(MT_ID_DISP, IOC_DISP_SET_SCREENOFFSET, DISP_SCREENOFFSET_S)
#define CMD_DISP_GET_SCREENOFFSET     _IOWR(MT_ID_DISP, IOC_DISP_GET_SCREENOFFSET, DISP_SCREENOFFSET_S)

#define CMD_DISP_SET_DAC           _IOW(MT_ID_DISP, IOC_DISP_SET_DAC, DISP_SET_INTF_S)
#define CMD_DISP_GET_DAC           _IOR(MT_ID_DISP, IOC_DISP_GET_DAC, DISP_SET_INTF_S)

#define CMD_DISP_SET_TIMING        _IOW(MT_ID_DISP, IOC_DISP_SET_TIMING , DISP_TIMING_S)
#define CMD_DISP_GET_TIMING        _IOWR(MT_ID_DISP, IOC_DISP_GET_TIMING , DISP_TIMING_S)

#define CMD_DISP_SET_ZORDER        _IOW(MT_ID_DISP, IOC_DISP_SET_ZORDER, DISP_ZORDER_S)
#define CMD_DISP_GET_ORDER         _IOWR(MT_ID_DISP, IOC_DISP_GET_ORDER, DISP_ORDER_S)

#define CMD_DISP_SET_BGC           _IOW(MT_ID_DISP, IOC_DISP_SET_BGC, DISP_BGC_S)
#define CMD_DISP_GET_BGC           _IOWR(MT_ID_DISP, IOC_DISP_GET_BGC, DISP_BGC_S)

#define CMD_DISP_SET_SCREEN        _IOW(MT_ID_DISP, IOC_DISP_SET_SCREEN, DISP_SCREEN_S)
#define CMD_DISP_GET_SCREEN        _IOWR(MT_ID_DISP, IOC_DISP_GET_SCREEN, DISP_SCREEN_S)
#define CMD_DISP_SET_SMALLWINDOW        _IOW(MT_ID_DISP, IOC_DISP_SET_SMALLWINDOW, DISP_VIRTSCREEN_S)
#define CMD_DISP_GET_SMALLWINDOW        _IOWR(MT_ID_DISP, IOC_DISP_GET_SMALLWINDOW, DISP_VIRTSCREEN_S)

#define CMD_DISP_SET_COLOR        _IOW(MT_ID_DISP, IOC_DISP_SET_COLOR, DISP_COLOR_S)
#define CMD_DISP_GET_COLOR        _IOWR(MT_ID_DISP, IOC_DISP_GET_COLOR, DISP_COLOR_S)

#define CMD_DISP_SET_COLORBAR      _IOW(MT_ID_DISP, IOC_DISP_SET_COLORBAR, DISP_ENABLE_S)
#define CMD_DISP_SET_OUTPUT_ENABLE _IOW(MT_ID_DISP, IOC_DISP_SET_OUTPUT_ENABLE, DISP_ENABLE_S)

#define CMD_DISP_SET_BRIGHT        _IOW(MT_ID_DISP, IOC_DISP_SET_BRIGHT, DISP_CSC_S)
#define CMD_DISP_GET_BRIGHT        _IOWR(MT_ID_DISP, IOC_DISP_GET_BRIGHT, DISP_CSC_S)

#define CMD_DISP_SET_CONTRAST      _IOW(MT_ID_DISP, IOC_DISP_SET_CONTRAST, DISP_CSC_S)
#define CMD_DISP_GET_CONTRAST      _IOWR(MT_ID_DISP, IOC_DISP_GET_CONTRAST, DISP_CSC_S)

#define CMD_DISP_SET_SATURATION    _IOW(MT_ID_DISP, IOC_DISP_SET_SATURATION, DISP_CSC_S)
#define CMD_DISP_GET_SATURATION    _IOWR(MT_ID_DISP, IOC_DISP_GET_SATURATION, DISP_CSC_S)

#define CMD_DISP_SET_HUE           _IOW(MT_ID_DISP, IOC_DISP_SET_HUE, DISP_CSC_S)
#define CMD_DISP_GET_HUE           _IOWR(MT_ID_DISP, IOC_DISP_GET_HUE, DISP_CSC_S)

#define CMD_DISP_SET_ALG           _IOW(MT_ID_DISP, IOC_DISP_SET_ALG, DISP_ALG_S)
#define CMD_DISP_GET_ALG           _IOWR(MT_ID_DISP, IOC_DISP_GET_ALG, DISP_ALG_S)

#define CMD_DISP_SET_LAYER_SHOW           _IOW(MT_ID_DISP, IOC_DISP_SET_LAYER_SHOW, DISP_LAYERSHOW_S)

#define CMD_DISP_CREATE_VBI_CHANNEL   _IOWR(MT_ID_DISP, IOC_DISP_CREATE_VBI_CHANNEL, DISP_VBI_CREATE_CHANNEL_S)
#define CMD_DISP_DESTROY_VBI_CHANNEL  _IOW(MT_ID_DISP, IOC_DISP_DESTROY_VBI_CHANNEL, mt_handle)
#define CMD_DISP_SEND_VBI             _IOW(MT_ID_DISP, IOC_DISP_SEND_VBI, DISP_VBI_S)
#define CMD_DISP_SET_WSS              _IOW(MT_ID_DISP, IOC_DISP_SET_WSS, DISP_WSS_S)

#define CMD_DISP_SET_MCRVSN        _IOW(MT_ID_DISP, IOC_DISP_SET_MCRVSN, DISP_MCRVSN_S)
#define CMD_DISP_GET_MCRVSN        _IOWR(MT_ID_DISP, IOC_DISP_GET_MCRVSN, DISP_MCRVSN_S)

#define CMD_DISP_SET_HDMI_INTF     _IOW(MT_ID_DISP, IOC_DISP_SET_HDMIINF, DISP_HDMIINF_S)
#define CMD_DISP_GET_HDMI_INTF     _IOWR(MT_ID_DISP, IOC_DISP_GET_HDMIINF, DISP_HDMIINF_S)

#define CMD_DISP_SET_CGMS          _IOW(MT_ID_DISP, IOC_DISP_SET_CGMS, DISP_CGMS_S)

#define CMD_DISP_GET_DISP_SCREEN     _IOWR(MT_ID_DISP, IOC_DISP_GET_DISP_SCREEN, DISP_OUTRECT_S)
#define CMD_DISP_SET_DISP_SCREEN     _IOW(MT_ID_DISP, IOC_DISP_SET_DISP_SCREEN, DISP_OUTRECT_S)

#define CMD_DISP_SET_DEV_RATIO  _IOW(MT_ID_DISP, IOC_DISP_SET_DEV_RATIO, DISP_ASPECT_RATIO_S)
#define CMD_DISP_GET_DEV_RATIO  _IOWR(MT_ID_DISP, IOC_DISP_GET_DEV_RATIO, DISP_ASPECT_RATIO_S)


#define CMD_DISP_CREATE_CAST         _IOWR(MT_ID_DISP, IOC_DISP_CREATE_CAST,  DISP_CAST_CREATE_S)
#define CMD_DISP_DESTROY_CAST        _IOW(MT_ID_DISP, IOC_DISP_DESTROY_CAST, DISP_CAST_DESTROY_S)
#define CMD_DISP_SET_LOWDELAY_ENABLE _IOW(MT_ID_DISP, IOC_DISP_SET_LOWDELAY_ENABLE, DISP_LOWDELAY_ENABLE_S)
#define CMD_DISP_SET_CAST_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_CAST_ENABLE, DISP_CAST_ENABLE_S)
#define CMD_DISP_GET_CAST_ENABLE     _IOWR(MT_ID_DISP, IOC_DISP_GET_CAST_ENABLE, DISP_CAST_ENABLE_S)
#define CMD_DISP_ACQUIRE_CAST_FRAME  _IOWR(MT_ID_DISP, IOC_DISP_ACQUIRE_CAST_FRAME, DISP_CAST_FRAME_S)
#define CMD_DISP_RELEASE_CAST_FRAME  _IOW(MT_ID_DISP, IOC_DISP_RELEASE_CAST_FRAME, DISP_CAST_FRAME_S)
#define CMD_DISP_EXT_ATTACH          _IOWR(MT_ID_DISP, IOC_DISP_EXT_ATTACH, DISP_EXT_ATTACH_S)
#define CMD_DISP_EXT_DEATTACH          _IOWR(MT_ID_DISP, IOC_DISP_EXT_DEATTACH, DISP_EXT_ATTACH_S)

#define CMD_DISP_SET_CASTATTR        _IOWR(MT_ID_DISP, IOC_DISP_SET_CASTATTR, DISP_CAST_EXT_ATTR_S)
#define CMD_DISP_GET_CASTATTR        _IOWR(MT_ID_DISP, IOC_DISP_GET_CASTATTR, DISP_CAST_EXT_ATTR_S)
#define CMD_DISP_ACQUIRE_SNAPSHOT    _IOWR(MT_ID_DISP, IOC_DISP_ACQUIRE_SNAPSHOT,  DISP_SNAPSHOT_FRAME_S)
#define CMD_DISP_RELEASE_SNAPSHOT    _IOW(MT_ID_DISP, IOC_DISP_RELEASE_SNAPSHOT,  DISP_SNAPSHOT_FRAME_S)

#define CMD_DISP_SUSPEND  _IOW(MT_ID_DISP, IOC_DISP_SUSPEND, ulong)
#define CMD_DISP_RESUME   _IOW(MT_ID_DISP, IOC_DISP_RESUME, ulong)

#define CMD_DISP_FORCESET_DAC_ENABLE  _IOW(MT_ID_DISP, IOC_DISP_FORCESET_DAC_ENABLE, MT_BOOL)
#define CMD_DISP_SET_PARA  _IOW(MT_ID_DISP, IOC_DISP_SET_PARA, DISP_PRIV_PARA_S)
#define CMD_DISP_GET_PARA  _IOWR(MT_ID_DISP, IOC_DISP_GET_PARA, DISP_PRIV_PARA_S)
#define CMD_DISP_SET_PPMODE           _IOW(MT_ID_DISP, IOC_DISP_SET_PPMODE, DISP_PP_S)
#define CMD_DISP_SET_LAYER_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_LAYER_ENABLE, MT_BOOL)
#define CMD_DISP_GET_LAYER_ENABLE     _IOWR(MT_ID_DISP, IOC_DISP_GET_LAYER_ENABLE, MT_BOOL)
#define CMD_DISP_GET_VIDEO_SIZE       _IOWR(MT_ID_DISP, IOC_DISP_GET_VIDEO_SIZE, DISP_VIDEO_SIZE_S)
#define CMD_DISP_SET_LAYER_ALPHA           _IOW(MT_ID_DISP, IOC_DISP_SET_LAYER_ALPHA, DISP_ALPHA_S)
#define CMD_DISP_GET_LAYER_ALPHA           _IOWR(MT_ID_DISP, IOC_DISP_GET_LAYER_ALPHA, DISP_ALPHA_S)
#define CMD_DISP_SET_CSC_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_CSC_ENABLE, MT_BOOL)
#define CMD_DISP_SET_DENOISE_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_DENOISE_ENABLE, MT_BOOL)
#define CMD_DISP_SET_AFD_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_AFD_ENABLE, MT_BOOL)
#define CMD_DISP_SET_HDVIDEO_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_HDVIDEO_ENABLE, MT_BOOL)
#define CMD_DISP_SET_SDVIDEO_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_SDVIDEO_ENABLE, MT_BOOL)
#define CMD_DISP_SET_VDAC_ONOFF          _IOW(MT_ID_DISP, IOC_DISP_SET_VDAC_ONOFF, DISP_VDACOUTPUT_S)
#define CMD_DISP_SET_TRICK_MODE		_IOW(MT_ID_DISP, IOC_DISP_SET_TRICK_MODE, DISP_TRICK_MODE_E)
#define CMD_DISP_SET_UNBLANK_MODE		_IOW(MT_ID_DISP, IOC_DISP_SET_UNBLANK_MODE, MT_DRV_DISP_UNBLANK_MODE_E)

#define CMD_DISP_SET_DI_ENABLE     _IOW(MT_ID_DISP, IOC_DISP_SET_DI_ENABLE, MT_BOOL)
#define CMD_DISP_SET_TVCAP           _IOW(MT_ID_DISP, IOC_DISP_SET_TVCAP, MT_DRV_DISP_HDMI_MODE_E)
#define CMD_DISP_SET_SL_HDR_PARA           _IOW(MT_ID_DISP, IOC_DISP_SET_SL_HDR_PARA, DISP_SL_HDR_PARA_S)
#define CMD_DISP_GET_SlHDR_VER   _IOWR(MT_ID_DISP, IOC_DISP_GET_SlHDR_VER, ulong)

#define CMD_DISP_SET_SD_ENC_PQ_PARA           _IOW(MT_ID_DISP, IOC_DISP_SET_SD_ENC_PQ_PARA, DISP_SD_ENC_PQ_PARA_S)
#define CMD_DISP_RESET_HARDWARE     _IOW(MT_ID_DISP, IOC_DISP_RESET_HARDWARE, MT_BOOL)
#define CMD_DISP_SET_SD_SCALER_ENABLE   _IOW(MT_ID_DISP, IOC_DISP_SET_SD_SCALER_ENABLE, MT_BOOL)
#define CMD_DISP_DUMP_SCALER_TO_OSD   _IOW(MT_ID_DISP, IOC_DISP_DUMP_SCALER_TO_OSD, MT_DRV_DISP_DUMP_SCALER_PARA_S)

#define CMD_FORCE_SHOW_DS_PIC     _IOW(MT_ID_DISP, IOC_DISP_FORCE_SHOW_DS_PIC, DISP_SHOW_DS_S)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __DRV_DISP_IOCTL_H__ */

