/********************************************************************************************/
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/* Montage Proprietary and Confidential                                                     */
/* Copyright (c) 2018 Montage Technology Group Limited and its affiliated companies         */
/********************************************************************************************/
#ifndef __DRV_HDMI_IOCTL_H__
#define __DRV_HDMI_IOCTL_H__

//#include "mt_common_id.h"
#include "mt_module.h"
//#include "mt_common_log.h"
#include "mt_debug.h"

#include "mt_unf_hdmi.h"
#include "mt_error_mpi.h"
//#include "mt_mpi_hiao.h"
#include "mt_drv_hdmi.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

/*
** HDMI IOCTL Data Structure
*/
typedef struct mtHDMI_OPEN_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_DEFAULT_ACTION_E enDefaultMode;
	mt_u32 u32ProcID;
	MT_UNF_HDMI_INIT_PARAM initParam;
} HDMI_OPEN_S;

typedef struct mtHDMI_DEINIT_S {
	mt_u32 NoUsed;
} HDMI_DEINIT_S;

typedef struct mtHDMI_INIT_S {
	mt_u32 NoUsed;
} HDMI_INIT_S;

typedef struct mtHDMI_COLSE_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 NoUsed;
} HDMI_CLOSE_S;

typedef struct mtHDMI_START_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 NoUsed;
} HDMI_START_S;

typedef struct mtHDMI_STOP_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 NoUsed;
} HDMI_STOP_S;

typedef struct mtHDMI_POLL_EVENT_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_EVENT_TYPE_E Event;
	mt_u32 u32ProcID;
} HDMI_POLL_EVENT_S;

typedef struct mtHDMI_SINK_CAPABILITY_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_EDID_BASE_INFO_S SinkCap;
} HDMI_SINK_CAPABILITY_S;

typedef struct mtHDMI_PORT_ATTR_S {
	MT_UNF_HDMI_ID_E enHdmi;
	HDMI_APP_ATTR_S stHdmiAppAttr;
} HDMI_PORT_ATTR_S;

typedef struct mtHDMI_INFORFRAME_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_INFOFRAME_TYPE_E enInfoFrameType;
	MT_UNF_HDMI_INFOFRAME_S InfoFrame;
} HDMI_INFORFRAME_S;

typedef struct mtHDMI_AVMUTE_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 AVMuteEnable;
} HDMI_AVMUTE_S;

typedef struct mtHDMI_VIDEOTIMING_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 VideoTiming;
	MT_DRV_DISP_STEREO_E enStereo;
} HDMI_VIDEOTIMING_S;

typedef struct mtHDMI_PREVIDEOTIMING_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 VideoTiming;
} HDMI_PREVIDEOTIMING_S;

typedef struct mtHDMI_DEEPCOLOR_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_DEEP_COLOR_E enDeepColor;
} HDMI_DEEPCOLORC_S;

typedef struct mtHDMI_COLORSPACE_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_VIDEO_MODE_E enColorSapce;
} HDMI_COLORSPACE_S;

typedef struct mtHDMI_SET_XVYCC_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 xvYCCEnable;
} HDMI_SET_XVYCC_S;

typedef struct mtHDMI_CEC_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_CEC_CMD_S CECCmd;
	mt_u32 timeout;
} HDMI_CEC_S;

typedef struct {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_CEC_STATUS_S stStatus;
} HDMI_CEC_STATUS;

typedef struct mtHDMI_EDID_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u8 u8EdidValid;
	mt_u32 u32Edidlength;
	//mt_u8                           u8Edid[512];
	mt_unf_hdmi_edid_t stEdidParsed;
} HDMI_EDID_S;

typedef struct mtHDMI_PLAYSTAUS_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 u32PlayStaus;
} HDMI_PLAYSTAUS_S;

typedef struct mtHDMI_CEC_ENABLE_S {
	mt_u32 NoUsed;
} HDMI_CEC_ENABlE_S;

typedef struct mtHDMI_CEC_DISABLE_S {
	mt_u32 NoUsed;
} HDMI_CEC_DISABLE_S;

typedef struct mtHDMI_HDCP_ENABLE_S {
	mt_u32 NoUsed;
} HDMI_HDCP_ENABlE_S;

typedef struct mtHDMI_HDCP_DISABLE_S {
	mt_u32 NoUsed;
} HDMI_HDCP_DISABLE_S;

typedef struct mtHDMI_REGCALLBACKFUNC_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 u32CallBackAddr;
} HDMI_REGCALLBACKFUNC_S;

typedef struct mtHDMI_LOADKEY_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_LOAD_KEY_S stLoadKey;
} HDMI_LOADKEY_S;

typedef struct mtHDMI_GETPROCID_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 u32ProcID;
} HDMI_GET_PROCID_S;

typedef struct mtHDMI_GETAOATTR_S {
	MT_UNF_HDMI_ID_E enHdmi;
	HDMI_AUDIO_ATTR_S stAudAttr;
} HDMI_GETAOATTR_S;

typedef struct mtHDMI_STATUS_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_STATUS_S stStatus;
} HDMI_STATUS_S;

typedef struct mtHDMI_SETFMT_DELAY_S {
	MT_UNF_HDMI_ID_E enHdmi;
	MT_UNF_HDMI_DELAY_S stDelay;
} HDMI_DELAY_S;

typedef struct mtHDMI_OUTPUT_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 outEnable;
} HDMI_OUTPUT_S;

typedef struct mtHDMI_REG_DUMP_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 NoUsed;
} HDMI_REG_DUMP_S;

typedef struct mtHDMI_REG_WRITE_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 addr;
	mt_u32 data;
} HDMI_REG_WRITE_S;

typedef struct mtHDMI_REG_READ_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32  addr;
	mt_u32  *data;
} HDMI_REG_READ_S;


typedef struct mtHDMI_RAW_EDID_INFO_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u8 rawEdidInfo[1024];
} HDMI_RAW_EDID_INFO_S;

typedef struct mtHDMI_CLK_CFG_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u32 clk;  //tmds clk
	mt_u32 ssc_on;
	mt_u32 pdpi_on;
	mt_u32 vout_clk_gate_on;
	mt_u32 clk_os;  //os clk
} HDMI_CLK_CFG_S;

typedef struct mtHDMI_DOCMD_S {
	MT_UNF_HDMI_ID_E enHdmi;
	hdmi_io_cmd_t cmd;
	mt_u32 data1;
	mt_u32 data2;
	mt_u32 resered;
} HDMI_DOCMD_S;

typedef struct mtHDMI_OSD_NAME_S {
	MT_UNF_HDMI_ID_E enHdmi;
	mt_u8 osdName[15]; //osd name max length 14 + "\0" = 15
} HDMI_OSD_NAME_S;

enum mtIOCTL_HDMI_E {
	IOCTL_HDMI_INIT = 0X01,
	IOCTL_HDMI_DEINIT,
	IOCTL_HDMI_OPEN,
	IOCTL_HDMI_CLOSE,
	IOCTL_HDMI_START,
	IOCTL_HDMI_STOP,
	IOCTL_HDMI_SINK_CAPABILITY,
	IOCTL_HDMI_POLL_EVENT,
	IOCTL_HDMI_GET_ATTR,
	IOCTL_HDMI_SET_ATTR,
	IOCTL_HDMI_GET_INFORFRAME,
	IOCTL_HDMI_SET_INFORFRAME,
	IOCTL_HDMI_AVMUTE,
	IOCTL_HDMI_VIDEO_TIMING,
	IOCTL_HDMI_GET_DEEPCOLOR,
	IOCTL_HDMI_SET_DEEPCOLOR,
	IOCTL_HDMI_GET_COLORSPACE,
	IOCTL_HDMI_SET_COLORSPACE,
	IOCTL_HDMI_XVYCC,
	IOCTL_HDMI_SET_CEC,
	IOCTL_HDMI_GET_CEC,
	IOCTL_HDMI_CECSTATUS,
	IOCTL_HDMI_PRE_VIDEO_TIMING,
	IOCTL_HDMI_FORCE_GET_EDID,
	IOCTL_HDMI_GET_HDMI_PLAYSTAUS,
	IOCTL_HDMI_CEC_ENABLE,
	IOCTL_HDMI_CEC_DISABLE,
	IOCTL_HDMI_REG_CALLBACK_FUNC,
	IOCTL_HDMI_LOADKEY,
	IOCTL_HDMI_GET_PROCID,
	IOCTL_HDMI_RELEASE_PROCID,
	IOCTL_HDMI_GET_AO_ATTR,
	IOCTL_HDMI_AUDIO_CHANGE,
	IOCTL_HDMI_GET_STATUS,
	IOCTL_HDMI_GET_DELAY,
	IOCTL_HDMI_SET_DELAY,
	IOCTL_HDMI_SET_DEFAULT_VIDEO,
	IOCTL_HDMI_SET_DEFAULT_AUDIO,
	IOCTL_HDMI_SET_VIDEO,
	IOCTL_HDMI_SET_AUDIO,
	IOCTL_HDMI_SET_NOTIFY,
	IOCTL_HDMI_OUTPUT_SET,
	IOCTL_HDMI_REGISTERS_DUMP,
	IOCTL_HDMI_REGISTER_WRITE,
	IOCTL_HDMI_REGISTER_READ,

	IOCTL_HDMI_GET_RAW_EDID_INFO,
	IOCTL_HDMI_CLK_CFG,

	ICTRL_HDMI_DOCMD,
	IOCTL_HDMI_HDCP_ENABLE,
	IOCTL_HDMI_HDCP_DISABLE,
	IOCTL_HDMI_SET_OSDNAME,

	IOCTL_HDMI_MAX,
};

/*
**IOCTRL Between User/Kernel Level
*/
#define CMD_HDMI_INIT _IOWR(MT_ID_HDMI, IOCTL_HDMI_INIT, HDMI_INIT_S)
#define CMD_HDMI_DEINIT _IOWR(MT_ID_HDMI, IOCTL_HDMI_DEINIT, HDMI_DEINIT_S)
#define CMD_HDMI_OPEN _IOWR(MT_ID_HDMI, IOCTL_HDMI_OPEN, HDMI_OPEN_S)
#define CMD_HDMI_CLOSE _IOWR(MT_ID_HDMI, IOCTL_HDMI_CLOSE, HDMI_CLOSE_S)
#define CMD_HDMI_START _IOWR(MT_ID_HDMI, IOCTL_HDMI_START, HDMI_START_S)
#define CMD_HDMI_STOP _IOWR(MT_ID_HDMI, IOCTL_HDMI_STOP, HDMI_STOP_S)
#define CMD_HDMI_SINK_CAPABILITY _IOWR(MT_ID_HDMI, IOCTL_HDMI_SINK_CAPABILITY, HDMI_SINK_CAPABILITY_S)
#define CMD_HDMI_POLL_EVENT _IOWR(MT_ID_HDMI, IOCTL_HDMI_POLL_EVENT, HDMI_POLL_EVENT_S)
#define CMD_HDMI_GET_ATTR _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_ATTR, HDMI_PORT_ATTR_S)
#define CMD_HDMI_SET_ATTR _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_ATTR, HDMI_PORT_ATTR_S)
#define CMD_HDMI_GET_INFORFRAME _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_INFORFRAME, HDMI_INFORFRAME_S)
#define CMD_HDMI_SET_INFORFRAME _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_INFORFRAME, HDMI_INFORFRAME_S)
#define CMD_HDMI_SET_AVMUTE _IOWR(MT_ID_HDMI, IOCTL_HDMI_AVMUTE, HDMI_AVMUTE_S)
#define CMD_HDMI_VIDEO_TIMING _IOWR(MT_ID_HDMI, IOCTL_HDMI_VIDEO_TIMING, HDMI_VIDEOTIMING_S)
#define CMD_HDMI_GET_DEEPCOLOR _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_DEEPCOLOR, HDMI_DEEPCOLORC_S)
#define CMD_HDMI_SET_DEEPCOLOR _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_DEEPCOLOR, HDMI_DEEPCOLORC_S)
#define CMD_HDMI_GET_COLORSPACE _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_COLORSPACE, HDMI_COLORSPACE_S)
#define CMD_HDMI_SET_COLORSPACE _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_COLORSPACE, HDMI_COLORSPACE_S)
#define CMD_HDMI_SET_XVYCC _IOWR(MT_ID_HDMI, IOCTL_HDMI_XVYCC, HDMI_SET_XVYCC_S)
#define CMD_HDMI_GET_CEC _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_CEC, HDMI_CEC_S)
#define CMD_HDMI_SET_CEC _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_CEC, HDMI_CEC_S)
#define CMD_HDMI_CECSTATUS _IOWR(MT_ID_HDMI, IOCTL_HDMI_CECSTATUS, HDMI_CEC_STATUS)
#define CMD_HDMI_PREVTIMING _IOWR(MT_ID_HDMI, IOCTL_HDMI_PRE_VIDEO_TIMING, HDMI_PREVIDEOTIMING_S)
#define CMD_HDMI_FORCE_GET_EDID _IOWR(MT_ID_HDMI, IOCTL_HDMI_FORCE_GET_EDID, HDMI_EDID_S)
#define CMD_HDMI_GET_RAW_EDID_INFO _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_RAW_EDID_INFO, HDMI_RAW_EDID_INFO_S)
#define CMD_HDMI_GET_HDMI_PLAYSTAUS _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_HDMI_PLAYSTAUS, HDMI_PLAYSTAUS_S)
#define CMD_HDMI_CEC_ENABLE _IOWR(MT_ID_HDMI, IOCTL_HDMI_CEC_ENABLE, HDMI_CEC_ENABlE_S)
#define CMD_HDMI_CEC_DISABLE _IOWR(MT_ID_HDMI, IOCTL_HDMI_CEC_DISABLE, HDMI_CEC_DISABLE_S)
#define CMD_HDMI_REG_CALLBACK_FUNC _IOWR(MT_ID_HDMI, IOCTL_HDMI_REG_CALLBACK_FUNC, HDMI_REGCALLBACKFUNC_S)
#define CMD_HDMI_LOADKEY _IOWR(MT_ID_HDMI, IOCTL_HDMI_LOADKEY, HDMI_LOADKEY_S)
#define CMD_HDMI_GET_PROCID _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_PROCID, HDMI_GET_PROCID_S)
#define CMD_HDMI_RELEASE_PROCID _IOWR(MT_ID_HDMI, IOCTL_HDMI_RELEASE_PROCID, HDMI_GET_PROCID_S)
#define CMD_HDMI_GET_AO_ATTR _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_AO_ATTR, HDMI_GETAOATTR_S)
#define CMD_HDMI_AUDIO_CHANGE _IOWR(MT_ID_HDMI, IOCTL_HDMI_AUDIO_CHANGE, HDMI_GETAOATTR_S)
#define CMD_HDMI_GET_STATUS _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_STATUS, HDMI_STATUS_S)
#define CMD_HDMI_GET_DELAY _IOWR(MT_ID_HDMI, IOCTL_HDMI_GET_DELAY, HDMI_DELAY_S)
#define CMD_HDMI_SET_DELAY _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_DELAY, HDMI_DELAY_S)
#define CMD_HDMI_SET_DEFAULT_VIDEO _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_DEFAULT_VIDEO, mt_void *)
#define CMD_HDMI_SET_DEFAULT_AUDIO _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_DEFAULT_AUDIO, mt_void *)
#define CMD_HDMI_SET_VIDEO _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_VIDEO, mt_void *)
#define CMD_HDMI_SET_AUDIO _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_AUDIO, mt_void *)
#define CMD_HDMI_SET_NOTIFY _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_NOTIFY, mt_void *)
#define CMD_HDMI_OUTPUT_SET _IOWR(MT_ID_HDMI, IOCTL_HDMI_OUTPUT_SET, HDMI_OUTPUT_S)
#define CMD_HDMI_REGISTERS_DUMP _IOWR(MT_ID_HDMI, IOCTL_HDMI_REGISTERS_DUMP, HDMI_REG_DUMP_S)
#define CMD_HDMI_REGISTER_WRITE _IOW(MT_ID_HDMI, IOCTL_HDMI_REGISTER_WRITE, HDMI_REG_WRITE_S)
#define CMD_HDMI_REGISTER_READ _IOWR(MT_ID_HDMI, IOCTL_HDMI_REGISTER_READ, HDMI_REG_READ_S)
#define CMD_HDMI_CLK_CFG _IOW(MT_ID_HDMI, IOCTL_HDMI_CLK_CFG, HDMI_CLK_CFG_S)
#define CMD_HDMI_DOCMD _IOWR(MT_ID_HDMI, ICTRL_HDMI_DOCMD, HDMI_DOCMD_S)
#define CMD_HDMI_HDCP_ENABLE _IOWR(MT_ID_HDMI, IOCTL_HDMI_HDCP_ENABLE, HDMI_HDCP_ENABlE_S)
#define CMD_HDMI_HDCP_DISABLE _IOWR(MT_ID_HDMI, IOCTL_HDMI_HDCP_DISABLE, HDMI_HDCP_DISABLE_S)
#define CMD_HDMI_SET_OSDNAME _IOWR(MT_ID_HDMI, IOCTL_HDMI_SET_OSDNAME, HDMI_OSD_NAME_S)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif
