include ${SDK_DIR}/build/script/base.mk

.PHONY: all clean install uninstall distclean

all:
	$(MAKE) -C mingetty-1.08

clean:
	$(MAKE) -C mingetty-1.08 clean

install:
	$(MAKE) -C mingetty-1.08 install

uninstall:
	$(MAKE) -C mingetty-1.08 uninstall

distclean:
	$(MAKE) -C mingetty-1.08 distclean
