#!/bin/sh
case "$1" in
  start)
    echo "Starting OpenVPN client..."
    nohup openvpn --config /etc/openvpn/client.ovpn --daemon --log /var/log/openvpn.log &
    ;;
  stop)
    echo "Stopping OpenVPN client..."
    pkill openvpn
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
